### ISSUE TITLE
transfer to separate GitHub org

### ISSUE THREAD

**Issue by afeld** [GSA/data.gov#1079]
Running list, in rough order:

- [x] Create the org - @usdatagov
- [x] [Enforce 2FA](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization)
- [x] [Enable third-party access restriction](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/enabling-oauth-app-access-restrictions-for-your-organization)
- [ ] Add @afeld @its-a-lisa @JJediny @tts-bot as Owners
- [ ] Accept invite from @tts-bot 
- [ ] [Share CircleCI plan](https://circleci.com/docs/2.0/faq/#is-there-a-way-to-share-plans-across-organizations-and-have-them-billed-centrally) from 18F
- [ ] Add to [list of TTS GitHub organizations](https://handbook.18f.gov/github/#organizations)
- [-] If you need a paid plan: [Submit micropurchase request](https://handbook.18f.gov/software/#step-2-use-the-micropurchase-request-form-to-make-a-request)
- [-] If you need a paid plan: Add billing info
- [ ] Transfer repositories [manually](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) or [through the API](https://developer.github.com/v3/repos/#transfer-a-repository)
- [ ] Add to [GitHub government orgs list](https://government.github.com/community/)

**Comment by adborden** [comment]
Documenting a few reasons why the GSA GH org is problematic ([slack conversation](https://gsa-tts.slack.com/archives/CH0PJ6F3R/p1570813770012900) from October):
- CircleCI is configured to only build from org users. This makes it more difficult for the public and our partners to collaborate.
- GSA policy for managing the GH org limits us to adding only users with an @gsa.gov address, which excludes some of our contractors and our OMB/NARA/etc partners.
- Paying for third-party services like CircleCI are tied to the org, so if TTS pays for CircleCI then they end up paying for all of GSA usage.
- TTS admins have limited visibility and we manually need to add the tts-admin team to Data.gov repos (we have over 100). This probably could be automated.
- Cannot use GitHub actions (GSA is currently migrating billing to enable this)

**Comment by mogul** [comment]
> CircleCI is configured to only build from org users. This makes it more
difficult for the public and our partners to collaborate.

Note this is fairly typical for build-systems pointing at public-facing
repositories. For example, you don't want randos to be able to make a PR
which includes code that ships deployment credentials back to them, and
allow that to run without someone at a higher level of trust OK'ing it.
CircleCI does have a setting for building forks, without supplying secure
credentials to them.
https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests

I checked the docs and couldn't find anything about settings specifically
based on GitHub org membership... Got a reference on that? (I would hope
there's still something to say it's OK to build from committers even if
they're not in the org.)

**Comment by adborden** [comment]
I have not been able to find any docs on what settings are available at the owner or org level within CircleCI, which is why this is frustrating. Maybe there is no org-level configuration. In trying to debug why Yaditi's branches weren't building, [changing her org membership to public](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1575487527388200) in GH was the only thing that worked.

So I might be jumping the gun pointing at pointing the finger at GSA's configuration, maybe this would be better to say: "Debugging configuration issues is challenging without admin access to CircleCI and GitHub".

Besides debugging Yaditi's issue, we also spent some time investigating why GH actions weren't working and why we couldn't setup builds on Docker Hub. Definitely those products deserve the bulk of the blame for poor messaging about the underlying error but I believe that the time debugging would've been reduced if we had our own GH organization, or at least have TTS managing it.

**Comment by adborden** [comment]
GSA recently moved to GH Enterprise with an updated configuration. This means we now have an additional step when adding outside contributors to content repos (e.g. [GSA/data-strategy](https://github.com/GSA/data-strategy) or [GSA/resources.data.gov](https://github.com/GSA/resources.data.gov)) to request access via an email to GH org admins. One more reason to switch.
