### ISSUE TITLE
capture actual user agent IP in logs

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#132]
capture the actual user agent IP in the logs that get fed into the EFK stack

**Comment by JJediny** [comment]
@kvuppala @dano-reisys I think I'd rather just manually add the inventory tag in the fluentd [1:2] should be enough to distinguish from others no? Otherwise, we'd have to pull that from the AWS temporary creds and/or have to use some other external lookup... Plus if an instance goes down it will come up with a new IP I'd rather correlate logs overtime per service rather than random IP

**Comment by vasili4** [comment]
@JJediny the problem here is to log Visitor IP address in logs. Now all the requests come with loadbalancer ip in REMOTE_ADDR. The issue here is to set [X-Forwarded-For](https://en.wikipedia.org/wiki/X-Forwarded-For) header on NetScaler side and capture it with nginx/apache
