### ISSUE TITLE
Duplicate datasets in USDA harvest of data.json

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1326]
USDA open data lead reporting multiple versions of dataset in catalog for USDA, but has confirmed only a single entry is in their data.json

## How to reproduce

1. See example dataset in screenshot Range Allotment: (Feature Layer)

## Expected behavior

There should be only one dataset

## Actual behavior

There appear to be multiple versions of other datasets too--see screenshot
![USDA duplicates](https://user-images.githubusercontent.com/3236989/73693066-8ac4fa80-46a3-11ea-89b4-e95890240527.png)

**Comment by hkdctol** [comment]
Other possible duplicates:

"This data set from the forest service – https://catalog.data.gov/dataset/fstopo-pbs-reference-quadrangle-feature-layer-d1910
is old and should be completely removed from the data.gov site.

The new one is https://catalog.data.gov/dataset/fstopo-pbs-reference-quadrangle-feature-layer-92c19
and is harvested from USDA JSON."

**Comment by hkdctol** [comment]
Another duplicate:

"This dataset – https://catalog.data.gov/dataset/range-wild-horse-and-burro-territory-feature-layer-0d6a0

is old and should be removed completely.

This one – https://catalog.data.gov/dataset/range-wild-horse-and-burro-territory-feature-layer-0d6a0
is the correct dataset and is harvested from USDA JSON"

Perhaps there were old versions in the catalog, and at the reharvest it is not an updating an existing record but adding a new record for same dataset?

**Comment by ydave-reisys** [comment]
@hkdctol Duplicate issue can be fixed with changing cron run frequency on production. The issue i ran into is harvester for USDA will result in no of errors because of { in some of the datasets url. I tried to encode url but that also didn't solve the problem. Currently testing if changing jsonschema module version will fix the issue. We don't need to reach out to USDA at the moment.

If you are ok with some datasets not being harvested i can clear and rerun USDA harvester on PROD with changed cron settings.
