### ISSUE TITLE
Continuous deployment of datagov-deploy to sandbox

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1519]
## User Story

In order to shorten the cycle between committing changes and identifying problems that might impact release, we want the datagov-deploy playbook to be continuously deployed in the sandbox environment.

## Acceptance Criteria
- [x] WHEN a commit lands on the `develop` branch in the `datagov-deploy` repository \
  THEN the ansible playbook is run in the sandbox environment
- [x] WHEN there are problems with the `datagov-deploy` deployment \
  THEN the team is notified in Slack.

**Comment by adborden** [comment]
Picked up this story since https://github.com/GSA/datagov-ckan-multi/issues/287 requires that the docker container is built, which is part of the datagov-deploy pipeline.

Without a lot of effort, I was able to get PRs together to hook the pipeline together and identify some fixes and updates that would get deployment from Jenkins working.

The piece that is remaining is the notifications. GSA/TTS blocks the webhook slack add-on, making it difficult to integrate with slack. If Jenkins could send email, we could use the email integration but that would require an SMTP service. Still looking at options.

**Comment by adborden** [comment]
@mogul had the bright idea to simply create a new GH issue when the deploy fails. Since issues are also posted to Slack, this should be a reasonable first-pass for notifications on build failure.
