### ISSUE TITLE
Support FCS in catalog database upgrade to 9.5

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1548]
FCS has notified us that AWS is dropping support for PostgreSQL 9.4 on April 20th. Currently staging is already running 9.5 but production must be upgraded to at least 9.5.

AWS considers this a [major version update](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html). Documentation on [read replicas](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_PostgreSQL.Replication.ReadReplicas.html) is also relevant.

### Pre-upgrade tasks

- [x] Notify #datagov-comms approximately when the work is happening so it can be tweeted/published.
- [x] Stop the catalog workers

### Upgrade tasks

1. FCS notifies data.gov that they're ready to start.
1. data.gov ensures the harvesters are paused.
1. FCS takes a snaphost, instantiates new master and replicas, notifies data.gov when complete.
1. data.gov [upgrades the postgis extensions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions.95x) on the new database instances, verifies the upgrade.
    ```
    ALTER EXTENSION postgis UPDATE TO "2.5.2";
    ALTER EXTENSION postgis_tiger_geocoder UPDATE TO "2.2.5";
    ALTER EXTENSION postgis_topology UPDATE TO "2.2.5";
    ```
1. data.gov updates the catalog configuration to point to the new instances, notifies FCS.
    ```
    # update ansible variables for production
    ansible-playbook catalog.yml
    ```
1. FCS destroys the old database instances

### Post-upgrade tasks

- [x] Confirm the catalog workers are running

**Comment by adborden** [comment]
Just reading up on the process for a major RDS upgrade and related documentation for read replicas. It looks like we're going to need to coordinate a little closer than I expected. The AWS docs say that it's not possible to perform a major upgrade on read replicas, so we need to either promote them or destroy/re-create them. Since the promotion is not automatic, we should use the destroy/re-create method.

We have four web instances that connect to the read replicas. They are partitioned, two read exclusively from readreplica1, two read from readreplica2. We'll want to destroy/re-create the read replicas one at a time as mentioned in the upgrade documentation so that there's always at least one replica available.

Besides that, our application does use the postgis extensions, but I think we can upgrade those extensions ourselves.

I've update the description to capture the upgrade steps and the coordination with FCS.

**Comment by adborden** [comment]
We're currently running PostgreSQL 9.4.20 on production. I'm going to ask FCS to do a minor version update.

postgis_tiger_geocoder and postgis_topology version is 2.1.8 (latest). postgis version is 2.1.8 but [should be updated to 2.5.2](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions.94x). We'll need the minor upgrade to PostgreSQL to 9.4.24 first.

Relevant queries:

```
SELECT * FROM version();
SELECT * FROM pg_extension;
SELECT * FROM pg_available_extension_versions ORDER BY name;
```

**Comment by adborden** [comment]
@jbrown-xentity @FuhuXia and I just spoke with FCS who suggested a simplified plan. Since most of our write load comes from harvesters, if we pause that, we'll be able to create a new master and replicas from a snapshot. Once the upgrade is complete on the new instances, we'll just simply cut over to the new instances and re-enable the harvesters.

FCS checked that we're not using any custom parameter groups for catalog staging or production.

For the postgis extensions, upgrading them before a major update is only required if we're skipping a major version, which we're not. Since the minor update also requires downtime, we can skip this to avoid extra downtime and coordination.

**Comment by adborden** [comment]
I've disabled `harvest run` on catalog-harvester1p.

**Comment by adborden** [comment]
As part of disabling worker processes, I realized that as part of https://github.com/GSA/datagov-deploy/issues/499, we cleaned up the `geodatagov clean-deleted` job https://github.com/GSA/ckanext-geodatagov/pull/115 but we never re-enabled the job. There are likely many rows that can be cleaned up and we should look at prioritizing #499 in order to improve database performance.

**Comment by FuhuXia** [comment]
Looking at the action items of this task, it demos the necessity of an equivalently sized database running on staging or sandbox environments, on which we can do some performance testing, or dry-run some heavy operations and become aware of their impact before executing them on live production database. This operations include vacuum, rebuilding index, or debugging `clean-deleted` job.

**Comment by adborden** [comment]
No longer high priority since the upgrade itself is complete. I'll write up some additional details and next steps.

**Comment by adborden** [comment]
### Timeline
[Slack thread](https://gsa-tts.slack.com/archives/C2N85536E/p1587139183351800)
[FCS Chat](https://chat.google.com/room/AAAAWZheV54)

@FuhuXia  and I were pairing for most of this. @jbrown-xentity  joined to help out during the
outage.

_Times are PDT._

- **Apr 17, 9:16 AM PDT** FCS began creation of a new primary database from
  snapshot.
- **Apr 17, 10:52 AM** Primary creation is complete. Aaron inspected the
  database checking tables existed, data existed, and then performed an upgrade
  of the PostGIS extensions.
- **Apr 17, 11:01 AM** FCS began creations of replicas from snapshot of the new
  primary.
- **Apr 17, 11:14 AM** Aaron asked if a VACUUM was performed by FCS. This was
  discussed with FCS, but did not make it into the written plan. The VACUUM must
  be done by Data.gov team since FCS does not have psql access. We decided to go
  ahead without the VACUUM.
- **Apr 17, 11:22 AM** Replica creation was complete. Aaron deployed the DB
  configuration change to catalog-admin using catalog.yml playbook.
- **Apr 17, 11:33 AM** Aaron began rolling out the configuration change to
  catalog-web hosts via catalog.yml playbook.
- **Apr 17, 12:11 PM** Web hosts were looking good. Aaron started catalog.yml
  deploy to workers.
- **Apr 17, 12:15 PM** Uptrends began alerting on catalog.data.gov, reporting
  HTTP 503 errors.
- **Apr 17, 12:22 PM** Identified database latency as the primary cause via New
  Relic. Response time averaging 10+ seconds, even up to 200 seconds. Seeing
  timeouts in the CKAN logs (generics Apache timeouts to CKAN/wsgi).
  
  ![Screen Shot 2020-04-17 at 12 22 50 PM](https://user-images.githubusercontent.com/509703/80264836-50d41680-864a-11ea-997b-59ee0ce53d77.png)

  

- **Apr 17, 12:28 PM** FCS identified high CPU 80-100% on the RDS replicas.
- **Apr 17, 12:30 PM** DB configuration was rolled back on catalog-web[1:2]p,
  catalogb-web[1:2]p still connecting to the new replica2. We saw request time
  drop to more reasonable levels. FCS saw CPU drop to 16% on replica1 which was
  no longer in use. Uptrends alerts recovered. The outage was approximately 20
  minutes.
- **Apr 17, 12:28 PM** FCS identified high CPU and high Read IOPS on replica2
  when compared with the old replica1.
- **Apr 17, 12:53 PM** We moved catalogb-web2p back to the old replica2.
  Current state:
  - catalog-web1p -> old replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> old replica2

  At this point, the plan is to wait for
  new replica2 to "warm up" and then start warming up new replica1.

- **Apr 17, 2:17 PM** Still not seeing much improvement on replica2. We
  restarted apache2 on catalogb-web1p hoping to give replica2 a moment to breath
  and flush connections/transactions/replication changes.
- **Apr 17, 2:33 PM** Saw Read IOPS near zero, started up catalogb-web1p again.
  Replica stats were not much better. Still seeing high CPU (50%), high Read
  IOPS, and high Read Throughput on replica2.
- **Apr 17, 3:01 PM** FCS added a new replica3. We updated catalogb-web1p to
  point to replica3.
  Current state:
  - catalog-web1p -> old replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica3
  - catalogb-web2p -> old replica2

  At this point, we are thinking there is something wrong with the snapshots the original
  new replicas were created from.

- **Apr 17, 3:33 PM** We identified that catalogb-web1p throughput was only
  50rpm compared to 1k rpm total across the four web instances.
- **Apr 17, 3:39 PM** We started identifying long running queries in New Relic
  and testing directly against the databases. This was effective as a test case
  to see concrete query times on new replicas vs old replicas. We were also able
  to see differences in the query plans between replicas.
- **Apr 17, 5:23 PM** Switched catalogb-web1p back to the old replica2.
  Current state:
  - catalog-web1p -> old replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> old replica2
  - catalogb-web2p -> old replica2
- **Apr 17, 5:28 PM** FCS decided to start over, we removed the replicas and
  created a new master. The plan was to do some analysis on the master and then
  add fresh replicas when things looked good.
- **Apr 17, 5:50 PM** We started looking into DB parameter group in case we
  missed something. Everything looked correct.
- **Apr 17, 6:01 PM** Ran `VACUUM ANALYZE tracking_summary` to optimize the
  tracking_summary table where we were seeing the most problematic queries. The
  operation took about 5 minutes and reduced the query time to 3.5ms, a major
  difference. We perfomed a `VACUUM` operation, which is applied to the entire
  database.
- **Apr 17, 8:02 PM** `VACUUM` was complete. FCS re-created the replicas.
- **Apr 17, 9:51 PM** We reconfigured catalogb-web1p to point to the new
  replica2 but still seeing high response times on catalogb-web1p so the change
  was rolled back.

  After reading up on `VACUUM ANALYZE` vs `VACUUM`, we realized this was
  a step that was missed. [AWS calls out running `ANALYZE`](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html) after the major
  upgrade in order to populate `pg_statistic` which is used by the query planner. We ran an `ANALYZE` operation to populate these tables. This made a significant difference.

  Going back to the query plans, we realized that some indexes weren't being
  used when they should. Specifically for tracking_summary query, it was using
  tracking_summary_date index instead of tracking_summary_url. We started
  looking at what optimization steps might have been missed.  We rebuilt
  tracking_summary_url with `REINDEX tracking_summary_url`.
  The reindex seemed to improve the outliers for tracking_summary queries.
  We were still seeing spikes in some queries on the product table, but after
  looking at these query plans, the latency didn't seem to come from a missed
  index. Further analysis could be done but at this point performance was
  looking "good enough".
- **Apr 17, 10:53 PM** With performance looking reasonable, we added another
  instance onto the new replicas.
  Current state:
  - catalog-web1p -> new replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> old replica2
- **Apr 18, 9:53 AM**
  Current state:
  - catalog-web1p -> new replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> new replica2
- **Apr 18, 10:43 AM**
  Current state:
  - catalog-web1p -> new replica1
  - catalog-web2p -> new replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> new replica2
- **Apr 20 9:50 AM** Things are still looking good. FCS provided metrics on the
  replicas.
  **replica1**
  ![graphs of replica1 performance stats](https://user-images.githubusercontent.com/509703/80264862-66e1d700-864a-11ea-81fe-7e6f8e90c5c9.png)
  **replica2**
  ![graphs of replica2 performance stats](https://user-images.githubusercontent.com/509703/80264867-6e08e500-864a-11ea-81c8-496d2b7194af.png)

**Comment by adborden** [comment]
We've scheduled a postmortem to analyze what we could've done better for this database upgrade.

Given that we were short on time, we didn't do as much optimization as we'd have liked. Created https://github.com/GSA/datagov-deploy/issues/1599 with some follow up ideas.

**Comment by mogul** [comment]
data.gov RDS DB upgrade post-mortem notes
===

## What happened

Wednesday BSP notified us that they needed to have our DB upgraded by Monday afternoon. The Monday deadline was due to AWS' end-of-life policy. Monday was the "last moment" before AWS would do the upgrade on their own.

The upgrade did not go as expected and we ended up in an urgent state (eg after hours/weekend work) to get the DB upgrade accomplished. We don't like to work like that so we're treating this like an incident.



## Timeline

[Reference](https://github.com/GSA/datagov-deploy/issues/1548#issuecomment-619282232)

[Slack thread](https://gsa-tts.slack.com/archives/C2N85536E/p1587139183351800)
[FCS Chat](https://chat.google.com/room/AAAAWZheV54)

@FuhuXia  and I were pairing for most of this. @jbrown-xentity  joined to help out during the
outage.

_Times are PDT._

- **Apr 15** BSP notified data.gov of the situation around 10am.
- **Apr 15** Aaron drafted a team-level plan Wednesday afternoon. 
- **Apr 16** BSP suggested an improved plan, with earliest availability on Friday. There wasn't much time to validate the plan (eg test the plan in staging or with a new DB)
- **Apr 17, 9:16 AM PDT** FCS began creation of a new primary database from
  snapshot.
- **Apr 17, 10:52 AM** Primary creation is complete. Aaron inspected the
  database checking tables existed, data existed, and then performed an upgrade
  of the PostGIS extensions (per plan).
- **Apr 17, 11:01 AM** FCS began creations of replicas from a snapshot of the new
  primary.
- **Apr 17, 11:14 AM** Aaron asked if a VACUUM was performed by FCS. This was
  discussed with FCS, but did not make it into the written plan. The VACUUM must
  be done by Data.gov team since FCS does not have psql access. We decided to go
  ahead without the VACUUM.
- **Apr 17, 11:22 AM** Replica creation was complete. Aaron deployed the DB
  configuration change to catalog-admin using catalog.yml playbook.
- **Apr 17, 11:33 AM** Aaron began rolling out the configuration change to
  catalog-web hosts via catalog.yml playbook.
- **Apr 17, 12:11 PM** Web hosts were looking good. Aaron started catalog.yml
  deploy to workers.
- **Apr 17, 12:15 PM** Uptrends began alerting on catalog.data.gov, reporting
  HTTP 503 errors.
- **Apr 17, 12:22 PM** Identified database latency as the primary cause via New
  Relic. Response time averaging 10+ seconds, even up to 200 seconds. Seeing
  timeouts in the CKAN logs (generics Apache timeouts to CKAN/wsgi).
  
  ![Screen Shot 2020-04-17 at 12 22 50 PM](https://user-images.githubusercontent.com/509703/80264836-50d41680-864a-11ea-997b-59ee0ce53d77.png)

  

- **Apr 17, 12:28 PM** FCS identified high CPU 80-100% on the RDS replicas.
- **Apr 17, 12:28 PM** FCS identified high CPU and high Read IOPS on replica2
  when compared with the old replica1.
- **Apr 17, 12:30 PM** DB configuration was rolled back on catalog-web[1:2]p,
  catalogb-web[1:2]p still connecting to the new replica2. We saw request time
  drop to more reasonable levels. FCS saw CPU drop to 16% on replica1 which was
  no longer in use. Uptrends alerts recovered. The outage was approximately 20
  minutes.
- **Apr 17, 12:53 PM** We moved catalogb-web2p back to the old replica2.
  Current state:
  - catalog-web1p -> old replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> old replica2

  At this point, the plan is to wait for
  new replica2 to "warm up" and then start warming up new replica1.

- **Apr 17, 2:17 PM** Still not seeing much improvement on replica2. We
  restarted apache2 on catalogb-web1p hoping to give replica2 a moment to breathe
  and flush connections/transactions/replication changes.
- **Apr 17, 2:33 PM** Saw Read IOPS near zero, started up catalogb-web1p again.
  Replica stats were not much better. Still seeing high CPU (50%), high Read
  IOPS, and high Read Throughput on replica2.
- **Apr 17, 3:01 PM (_note 6pm ET!_)** FCS added a new replica3. We updated catalogb-web1p to
  point to replica3.
  Current state:
  - catalog-web1p -> old replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica3
  - catalogb-web2p -> old replica2

  At this point, we are thinking there is something wrong with the snapshots the original
  new replicas were created from.

- **Apr 17, 3:33 PM** We identified that catalogb-web1p throughput was only
  50rpm compared to 1k rpm total across the four web instances.
- **Apr 17, 3:39 PM** We started identifying long running queries in New Relic
  and testing directly against the databases. This was effective as a test case
  to see concrete query times on new replicas vs old replicas. We were also able
  to see differences in the query plans between replicas.
- **Apr 17, 5:23 PM** Switched catalogb-web1p back to the old replica2.
  Current state:
  - catalog-web1p -> old replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> old replica2
  - catalogb-web2p -> old replica2
- **Apr 17, 5:28 PM** FCS decided to start over, we removed the replicas and
  created a new master. The plan was to do some analysis on the master and then
  add fresh replicas when things looked good.
- **Apr 17, 5:50 PM** We started looking into DB parameter group in case we
  missed something. Everything looked correct.
- **Apr 17, 6:01 PM** Ran `VACUUM ANALYZE tracking_summary` to optimize the
  tracking_summary table where we were seeing the most problematic queries. The
  operation took about 5 minutes and reduced the query time to 3.5ms, a major
  difference. We perfomed a `VACUUM` operation, which is applied to the entire
  database. _<-- Start of resolution!_
- **Apr 17, 8:02 PM** `VACUUM` was complete. FCS re-created the replicas.
- **Apr 17, 9:51 PM** We reconfigured catalogb-web1p to point to the new
  replica2 but still seeing high response times on catalogb-web1p so the change
  was rolled back.

  After reading up on `VACUUM ANALYZE` vs `VACUUM`, we realized this was
  a step that was missed. [AWS calls out running `ANALYZE`](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html) after the major
  upgrade in order to populate `pg_statistic` which is used by the query planner. We ran an `ANALYZE` operation to populate these tables. This made a significant difference. _<-- an oversight that hurt us here_

  Going back to the query plans, we realized that some indexes weren't being
  used when they should. Specifically for tracking_summary query, it was using
  tracking_summary_date index instead of tracking_summary_url. We started
  looking at what optimization steps might have been missed.  We rebuilt
  tracking_summary_url with `REINDEX tracking_summary_url`.
  The reindex seemed to improve the outliers for tracking_summary queries.
  We were still seeing spikes in some queries on the product table, but after
  looking at these query plans, the latency didn't seem to come from a missed
  index. Further analysis could be done but at this point performance was
  looking "good enough".
- **Apr 17, 10:53 PM** With performance looking reasonable, we added another
  instance onto the new replicas.
  Current state:
  - catalog-web1p -> new replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> old replica2
- **Apr 18, 9:53 AM**
  Current state:
  - catalog-web1p -> new replica1
  - catalog-web2p -> old replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> new replica2
- **Apr 18, 10:43 AM**
  Current state:
  - catalog-web1p -> new replica1
  - catalog-web2p -> new replica1
  - catalogb-web1p -> new replica2
  - catalogb-web2p -> new replica2
- **Apr 20 9:50 AM** Things are still looking good. FCS provided metrics on the
  replicas.
  **replica1**
  ![graphs of replica1 performance stats](https://user-images.githubusercontent.com/509703/80264862-66e1d700-864a-11ea-81fe-7e6f8e90c5c9.png)
  **replica2**
  ![graphs of replica2 performance stats](https://user-images.githubusercontent.com/509703/80264867-6e08e500-864a-11ea-81c8-496d2b7194af.png)

## Observations

* Notices from AWS go to BSP rather than us, so we're totally dependent on them.
* BSP gave us a lot less notice than they have in the past, and certainly less than they should have (eg one sprint's at minimum, and a month would be better).
* We didn't have a great understanding of the actual process required (eg VACUUM)
* The appearance of the problem was about 30 minutes removed from the start of the change deployment.
* Load balancer rerouting traffic around unhealthy instances causes delays in perceiving errors or downtime when doing one-by-one instance upgrades

## Contributing factors

* We don't VACUUM (or VACUUM ANALYZE) as a matter of course (eg as part of normal deployment, much less major upgrades).
* Reliance on FCS for a level of RDS expertise that wasn't there.
* No alerting on database performance
* Short time to think it through up front, and no ability to pause and think about things once we'd started.
* "Data in place" was deemed enough for the cutover
  * We didn't know what a "healthy" database looks like.


## Learnings to take away
* We shouldn't rely on FCS for the details on RDS workings; we need to understand them ourselves.
* We should do a dry-run even when other teams are involved (eg in our sandbox)
* We only have "real" data (data volume, upgrade status, traffic load) in production
* We didn't follow the incident response process.
  * Aaron was both communicating and doing technical work, no one was taking notes as things went. 
  * We didn't use the "incident commander" pattern 
  we're supposed to, and hence had to do a lot of 
  after-the-fact reconstruction of the timeline.
  * **We didn't recognize and treat this as an incident until after it was over.**
  * We can consider including "gonna have to work
outside hours" to be an incident signifier.


## Followup actions

- [ ] (Hyon) We should schedule a meeting with FCS to figure out why the notice came so late and with such a short deadline
- [ ] (Aaron) We should add a process to the runbook covering the key points we know we have to hit next time (eg do a dry-run in the sandbox, run `VACUUM` and `VACUUM ANALYZE`)
- [ ] (Fuhu) Identify whether there are any DB-specific steps we should be adding to our deployment or O&M process
- [x] (James) Add to an issue about alerting in New Relic for database performance
- [x] (Bret) Add an issue covering the ability to simulate production-like load in non-prod environments (https://github.com/GSA/datagov-deploy/issues/1624)
