### ISSUE TITLE
Inconsistent Permissions for /var/run/apache2

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1573]
### How to Reproduce
It's unclear how to consistently reproduce.

After running playbooks, you might get an error such as `Permission denied Unable to connect to WSGI daemon process 'ckan' on '/var/run/apache2/wsgi.5116.0.0.sock`. 

![image.png](https://images.zenhubusercontent.com/5e1cbcd08dced94b250ef061/fb93a31f-382d-40d1-bd4d-65b8b5f2cf01)

### Expected Behaviors
Running playbooks or rebooting instances shouldn't cause a permission denied error in `var/run/apache2`

### Acceptance Criteria

- [ ] Discover if this is a reboot issue or if there is a bug in the ansible playbooks
- [ ] Correct error and run in playbooks

### Current workarounds
Run `ansible -m file -a 'path=/var/run/apache2 owner=root group=root mode=0755' <host-pattern>`

**Comment by adborden** [comment]
This was originally fixed in https://github.com/GSA/datagov-deploy-apache2/pull/4 and then updated in https://github.com/GSA/datagov-deploy-apache2/pull/9 but it seems that fix isn't complete.

The tmpfiles.d service is supposed to ensure that `/var/run/apache2` is created at boot time (/var/run and /run are a tmpfs) with the correct permissions. It seems that there is some sort of race condition where apache2 starts up before the directory is created, in which case `/var/run/apache2` is created with the system's hardened `027` umask, and then www-data can't list the directory in order to write to the socket.

This gets stranger because assuming apache2 started up correctly at boot time, running the playbook much later sometimes runs into this error. That would mean that something is changing the permissions on that directory (or deleting and recreating it). I'm not aware of anything in our playbooks that touch `/var/run`, so I doubt it's something in our playbooks. Not sure what other actions might on the OS might cause this... perhaps an apt upgrade to apache2, which is incredibly rare.

**Comment by adborden** [comment]
I suspect this only affects Trusty.

**Comment by FuhuXia** [comment]
Couldn't replicate the issue. Tried running the `common.yml` playbook alone, or removing apache2 and letting `catalog.yml` to reinstall apache2 again. In either case the directory `/var/run/apache2/` permission stays correct. I think we will simply add a task in our playbook to ensure the correct directory permission.
