### ISSUE TITLE
Truncated file download from Inventory using gunicorn

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1708]
User reported xlsx file downloaded from Inventory couldn't be open. File appears to be corrupted. I tried a few times.  For 1-2 out of 10 times, the file downloaded appeared to be complete but the file size was slightly smaller than what it should be. When trying to open the file of smaller size, I got similar file corrupted error message. 

## How to reproduce

1. Go to [FY 2018 Federal Real Property Profile Data for Civilian Agencies](https://catalog.data.gov/dataset/fy-2018-federal-real-property-profile-data-for-civilian-agencies) on catalog.
2. Under 'Downloads & Resources', click 'Download' Button to download the xlsx file a few times.
3. Compare the file sizes, if any file is found smaller than others, try to open it.

## Expected behavior

File sizes are consistent after multiple download. 
## Actual behavior
Some download is smaller than others. Got error message when open it.

![Screenshot 2020-05-27 16 50 28](https://user-images.githubusercontent.com/1392461/83074324-f4488a80-a03f-11ea-88a3-13c5d210fa77.png)

**Comment by FuhuXia** [comment]
This seems to be a newly surfaced issue. By its timing, maybe it is related to the Gunicorn we deployed recently? or maybe it is totally coincidence.

**Comment by adborden** [comment]
We're getting inconsistent results when downloading data from the public internet. Running this command gives me a different and incorrect checksum each time. The expected MD5 checksum is `bfaa4e572e2ecea38ce3fa723b5bb58e`.

```
$ curl --silent 'https://inventory.data.gov/dataset/78b921cf-d865-44b6-84bc-9df85a5de642/resource/da3a910a-14f3-42b4-80d2-be3ce1360a5d/download/frpppublicdatasetfy1805232019.xlsx' | md5sum
```

```
0a4954bc558de0914c43390260fb9fc5  -
37a09a0922dc84d3d2cb0048ca5b9b3b  -
4cbeeaa62a30eff9c7e20e7fe4cc3194  -
```

From within our AWS environment in FAS Cloud Services, the command gives the correct checksum, both from the host as well as through Netscaler.

```
$ curl --silent -H 'Host: inventory.data.gov' http://localhost/dataset/78b921cf-d865-44b6-84bc-9df85a5de642/resource/da3a910a-14f3-42b4-80d2-be3ce1360a5d/download/frpppublicdatasetfy1805232019.xlsx | md5sum
bfaa4e572e2ecea38ce3fa723b5bb58e  -
```

```
$ curl --silent -H 'Host: inventory.data.gov' https://inventory.data.gov/dataset/78b921cf-d865-44b6-84bc-9df85a5de642/resource/da3a910a-14f3-42b4-80d2-be3ce1360a5d/download/frpppublicdatasetfy1805232019.xlsx | md5sum
bfaa4e572e2ecea38ce3fa723b5bb58e  -
```

So far, it does seem to be specific to the above URL. Other datasets seem to download consistently.

```
$ curl --silent https://inventory.data.gov/dataset/1222bd0e-66b1-4e89-b185-298767a75837/resource/f0dadca9-d688-48d7-af0e-62bb4913b8be/download/irisbuildingestimateactive.csv | md5sum
656a514574d6ea7820514b7c20d8bc55  -

 $ curl --silent https://inventory.data.gov/dataset/1222bd0e-66b1-4e89-b185-298767a75837/resource/f0dadca9-d688-48d7-af0e-62bb4913b8be/download/irisbuildingestimateactive.csv | md5sum
656a514574d6ea7820514b7c20d8bc55  -
```

**Comment by adborden** [comment]
Hmm... I opened an incident with FCS but I haven't received a ticket number or an email.

**Comment by adborden** [comment]
INC3111314 has been created.

**Comment by jbrown-xentity** [comment]
Noted this when doing the security review for inventory log, seemed relevant:

```inventory1p.prod-ocsit.bsp.gsa.gov: [Wed May 27 18:51:43.378075 2020] [proxy_http:error] [pid 10770:tid 139632155944704] (70008)Partial results are valid but processing is incomplete: [client 173.79.65.163:4756] AH01110: error reading response, referer: https://catalog.data.gov/dataset/fy-2018-federal-real-property-profile-data-for-civilian-agencies```

**Comment by adborden** [comment]
Thanks @jbrown-xentity, I think @FuhuXia's intuition is right in that it's related to the gunicorn change. The proxy error above says to me that the response from gunicorn to apache2 was incomplete for some reason. I don't see any errors that would indicate _why_. My google-fu has also failed to come up with any clues.

Here's what we know so far:
- It's inconsistent
- Seems like the file is being truncated during transfer, rather than "corrupted"
- The response completes successfully despite the partial response.
- The truncation seems more likely the bigger the file and the higher the latency. Here in California, every request is truncated, but in N Virginia, @FuhuXia sees the truncation 20-50% of the time. From inventory1p/inventory2p, I will see **zero** truncations in 3000 requests. Smaller datasets (I've tested up to 4Mb) don's see the truncation either. We've only seen the truncation in this one 54Mb dataset and I haven't been able to find another dataset that large to test with.

I've enabled gunicorn's `--access-logfile` option and for requests that are truncated, the request never appears in gunicorn's access log but it does appear in apache's. This makes it seem like gunicorn's response never completes and so it doesn't get logged but apache thinks the response has ended before it has and then logs the error about the partial response.

Unfortunately, still no leads on what the right fix could be.

**Comment by adborden** [comment]
I reverted back to mod_wsgi on staging 😞 , and I'm getting the correct checksum. We'll go with this as a mitigation until we can dig into the gunicorn issue.

```
$ curl --silent 'https://inventory-datagov.dev-ocsit.bsp.gsa.gov/dataset/b65dd661-7382-465c-b8f1-23730750
cf0f/resource/56ab494f-f988-4a12-acda-cf2645e8d37c/download/frpppublicdatasetfy1805232019.xlsx' | md5sum
bfaa4e572e2ecea38ce3fa723b5bb58e  -
```

**Comment by jbrown-xentity** [comment]
Could it be a timeout issue? https://stackoverflow.com/questions/47217880/critical-worker-timeout-error-on-gunicorn-django

**Comment by adborden** [comment]
Something to try.

**Comment by adborden** [comment]
The mitigation is now live and seems to be working correctly. I'm going to move this back to the Product Backlog so that we can dig into it and resolve the root cause.

**Comment by adborden** [comment]
What I would test next on this is instead of using the built-in paste integration, I would use an explicit wsgi script. There's a lot of unknowns with how the paste integration works and our older version of paste.

Also, since we want to hook in New Relic early, we'll want to use the wsgi script method anyway rather than figure out how to hook in New Relic to the paste integration.

**Comment by mogul** [comment]
Aaron believes this can be reproduced in the sandbox by pulling the data in question over from production.

**Comment by mogul** [comment]
When we are investigating this, we should reference the [improved docs upstream](https://github.com/ckan/ckan/pull/5406) to see if there are obvious configuration differences.

**Comment by FuhuXia** [comment]
Tested on local. Here are the results and some interesting findings:
* **Download is fine when Gunicorn + Nginx**
* Download truncated when Gunicorn + Apache
* Download truncated when Gunicorn alone

When download is truncated:
* Chrome download gives 'failed - network error'. But you can click resume to complete download.
* wget client will auto resume.

When download is truncated behind BSP load balancer:
*  Chrome and wget downloading appears to be completed but ends up with the truncated file, which is what we observed on production.

**Comment by adborden** [comment]
Thanks @FuhuXia! In your tests, were you using the [default synchronous workers](https://docs.gunicorn.org/en/stable/design.html#choosing-a-worker-type)? I've heard anecdotal evidence that async workers generally have fewer issues with downloads/uploads and handling of large or slow buffers. nginx/apache is supposed to shield gunicorn from those issues, but my gut is that we should be using one of the async options given this issue.

**Comment by FuhuXia** [comment]
@adborden 👍  Test shows if we use async worker, the issue is resolved without any other changes.
