### ISSUE TITLE
Nessus 06/17/2020

### ISSUE THREAD

**Issue by pjsharpe07** [GSA/data.gov#1764]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.1iced5x7fav9)._

**Date of report:** 06/17/2020
**Severity:** High
**Due date:** 07/17/2020

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

### Brief description
[Nessus Scan 137300](https://docs.google.com/spreadsheets/d/1mAhihB3rT9gteTriRh_87_5VZUGw6oIkTEc-R2ioBK8/edit#gid=1145654805)

### Disclosure

Vulnerability class issue: Unpatched system with multiple CVEs present that are addressed in updates

### Description
These are the Solr v2 hosts. It looks like the host hasn’t been getting normal Ubuntu updates.
Remediation
Should just be a matter of running updates, and ensuring the hosts are set to auto-update.

Any notes on remediation for this vulnerability class:
How did they get in this state? We expect all hosts are auto-updating. Investigating unattended-upgrades would be a good starting point

**Comment by adborden** [comment]
solr-v2 hosts are now running Linux 5.3.0-1023-aws.

**Comment by adborden** [comment]
I've resolved this manually by rebooting the solr-v2 hosts.

These hosts did in fact have the common.yml playbook applied successfully and were updating correctly. The issue is that they were never rebooted to pickup the kernel and other critical service updates.

Because the work to add the solr-v2 hosts to the Ansible inventory (https://github.com/GSA/datagov-deploy/pull/1774) was not completed, these hosts were not rebooted as part of the routine reboot.yml playbook maintenance.

The work was started [Friday May 22](https://github.com/GSA/datagov-deploy/pull/1697) and was essentially complete. By late afternoon, I remember waiting for the staging playbook run to complete. But by Monday, the context was lost and this fell through the cracks.

Not sure if others have ideas on what we might do to improve this. One thing that comes to mind is having automated reminders for open PRs, or regularly going through open PRs as part of our sprint rituals. I had closed the original PR, but if this had been left open in draft state, having more visibility on it would've helped.
