### ISSUE TITLE
Jenkins.yml playbook fails to install pipenv when running with python3

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1791]
This issue only affects sandbox where python3 is installed to work around https://github.com/GSA/datagov-infrastructure-modules/issues/32.

Install pipenv task fails with error:

No module setuptools

**Work around** is to install python3-setuptools manually on the Jenkins host

    $ apt-get install python3-setuptools

## How to reproduce

1. ansible-playbook jenkins.yml

## Expected behavior

Task is successful, pipenv is installed with python2 interpreter.

## Actual behavior

Task fails, pipenv attempts to install with python3 interpreter and fails with missing setuptools.

**Comment by mogul** [comment]
Icebox'ing since this doesn't happen often and we have a workaround. Also might be better to tackling the difference between sandbox and BSP environments instead.

**Comment by nickumia-reisys** [comment]
No more Jenkins.  No more Ansible.  No pipenv.  No equivalent issue on cloud.gov.
- https://github.com/GSA/data.gov/issues/3710
- (Tangentially related) The pipenv mentioned in this issue was for ansible specific things.  But we did try to use pipenv for our main ckan app requirements management too.  It didn't work out haha..
  - https://github.com/GSA/data.gov/issues/3415
