### ISSUE TITLE
Increase StN ratio on high memory alerts

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1815]
## User Story

In order to reduce the incidence of high memory alerts, we want to adjust our alert conditions to improve the signal-to-noise ratio.

## Acceptance Criteria

- [x] WHEN I look at the data.gov New Relic configuration \
  THEN I see that memory alerts are set at 90%.
- [x] WHEN I look at O&M alert stats \
  THEN I see high memory alerts declined as of the date of the New Relic change.

## Background

We have four catalog web instances. Two of them are `c4.2xlarge`, the other two are `c4.xlarge`. With our current alert settings, we are seeing high memory alerts from the `c4.xlarge` instances, about five alerts every other day. The condition appears transitory and does not indicate an imminent crash.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
No security impact.

## Sketch

- Bump the threshold for alerting up to 90% utilization across the board.

**Comment by adborden** [comment]
Probably should be m5.xlarge, t3.xlarge or smaller. Definitely not c4, which is compute optimized. Web traffic tends to be more bursty than sustained load.

**Comment by jbrown-xentity** [comment]
The 90% threshold is already set. The only other false positives I see currently are in Amazon, where the 5xx fires many times daily and the 4xx alarm fires regularly. [Changed alarm](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarmsV2:alarm/awscloudfront-AWS-CloudFront-High-5xx-Error-Rate?) to only fire after error rate is above threshold for 5 minutes instead of 1 minute, will re-evaluate at end of sprint for final tweaks.
