### ISSUE TITLE
Harvester "Validation Error: missing tags"

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1828]
Harvester fails various geospatial metadata records for not having "tags" that are in fact registered similar to other passing geospatial data records. A good example can be found [here on sandbox](https://catalog.sandbox.datagov.us/harvest/nesdis-ngdc-mgg-nos-h06001-h08000/job/last), and you can find a complete list [here](https://docs.google.com/spreadsheets/d/1Afgx0nGPcsNu0-nIvhcQ3RRAJkcesaCPdcDqT4fIaBI/edit#gid=0). Will need to evaluate how the datasets differ, and if changes need to be made at the data source or in our code to better handle.

## How to reproduce

1. See harvest logs on sandbox or re-harvest to evaluate

## Expected behavior

Harvester completes with minimal errors and no "Missing Tags" errors

## Actual behavior

Harvester fails with many errors

**Comment by jbrown-xentity** [comment]
Aaron suggested testing on CKAN-next to see if moving to 2.8 solves the problem

**Comment by FuhuXia** [comment]
Same issue replicated on catalog-next. So moving to ckan 2.8 does not solve it. Taking a closer look at the difference between successful harvested datasets and failed ones to see what causes the issue.

**Comment by FuhuXia** [comment]
Fixed in the commit above. The issue happened to tags containing 2+ consecutive `&gt;`.  For example, for tag:

`EARTH     SCIENCE > ATMOSPHERE > > ATMOSPHERIC    ELECTRICITY > ATMOSPHERIC CONDUCTIVITY`

We want to split the tag with string `>`. Previous code has a bug that will create an empty string due to the `> >` therefore the error  message`Missing Tags`. New change has this fixed and generate a list of tags as:

`earth science, atmosphere, atmospheric electricity, atmospheric conductivity`
