### ISSUE TITLE
Snyk account upgrade required for data.gov

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#1868]
Got email from snyk:

**Subject**: Snyk account upgrade required for data.gov
**Content**: ...you have exceeded the free Snyk test limit this month for your data.gov org...

Before this email we have occasionally got emails about "You've reached the Snyk test limit for data.gov" over last a few months. In the [usage dashboard](https://app.snyk.io/org/data.gov/manage/usage?utm_campaign=test_limit_reached&utm_medium=email&utm_source=ReviewUsage) It show we are running **241** tests even our plan allows **200** tests /month.

**Comment by adborden** [comment]
@jbrown-xentity did some investigation into this.

**Comment by jbrown-xentity** [comment]
We had 3 repositories that were running scans each day and on every merge that were being run privately, and counting against those 200 tests per month. We removed a duplicate test for resources.data.gov, removed another repository that was not part of data.gov mission, and setup datagov-deploy to have the public repository linked so that the tests run do not count against the 200 private test limit. We no longer have any private tests that should be run, and should not hit this issue starting next month.

**Comment by mogul** [comment]
Likely mitigated by the changes above. We'll `Icebox` this for now, and resurrect it later if necessary.

**Comment by jbrown-xentity** [comment]
All repositories confirmed open source, issue is resolved.
