### ISSUE TITLE
Dept of Transportation POC getting harvest reports of only one of 2 harvest sources for DOT

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#1937]
Dan Morgan is CDO for Dept of Transportation. He's on the list to receive harvest report. For some reason he has stopped receiving harvest report for main harvest source, the DOT data.json.

## How to reproduce

Occurring daily in recent days - where Dan receives harvest report for a geospatial harvest source but not main DOT source data.json

## Expected behavior

Harvest report email list is at agency level, not by harvest source, so unclear why one would go through and not the other. Suggests it is not the typical problem of agency rejecting all no reply emails from datagov

## Actual behavior

Getting only one harvest report, and not the main one "DOT Socrata data.json" Dan Morgan is listed to get harvest reports for DOT sources
![Screen Shot 2020-07-28 at 6 25 29 PM](https://user-images.githubusercontent.com/3236989/88728748-643ac600-d100-11ea-9f72-a089879e2f48.png)
![Screen Shot 2020-07-28 at 6 25 40 PM](https://user-images.githubusercontent.com/3236989/88728765-6c930100-d100-11ea-8729-b923f05c543c.png)

**Comment by mogul** [comment]
Notable: Hyon is seeing both emails. So the question is, why does he get report but not the other?

**Comment by FuhuXia** [comment]
@hkdctol I Inspected two sample emails. As we discussed in slack, I suspect the emails were going out no problem, it is the user receiving end that has problem delivering them to user's inbox. Comparing the message bodies of the two emails, the one received by user has fairly clean message (not many links embedded). The one not received has larger message body with many hyper links and detailed technical messages due to the many dataset validation errors, which is often picked up by some anti-spam or anti-phishing filtering product deployed on some email servers. If user can talk to the email server provider and find a way to access those filtered-out emails, most likely those missing emails will be found there.

The image below shows many links in the message body.
![](https://user-images.githubusercontent.com/1392461/89211976-acd70100-d590-11ea-9baf-544e7ce6cd15.png).


In the meanwhile, if the harvest source can address those validation errors and fix the datasets, it will make the report cleaner and not likely to be filtered out.

**Comment by hkdctol** [comment]
![Screen Shot 2020-08-03 at 7 40 51 PM](https://user-images.githubusercontent.com/3236989/89237635-b9278200-d5c1-11ea-9a5a-a47d61300a21.png)
No obvious link between when DOT first reported not getting harvest reports (early July) and harvest reports and number of errors. Meanwhile, @jbrown-xentity - the two harvest jobs on top of each other -- that seems to be the pattern going back more than a year.

**Comment by FuhuXia** [comment]
@hkdctol Ok, the theory is that it may not be the amount of errors that triggers filtering. It is some particular pattern from some particular dataset error message that triggers the filtering. It may be too much hassle to compare the filtered-in report and filtered-out report to find the pattern. Let us first get the source dataset validation error fixed first.

For the mentioned behavior that the two consecutive jobs one following right after the other, that is because we break any json harvesting into two jobs, stand-alone and parent datasets harvested first, followed by children datasets harvesting.
