### ISSUE TITLE
[Research 2d]: Notify/alert operators based on events from application event/log stream

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1960]
## User Story

In order to notify/alert operators when any system requires an operator action to be taken, data.gov operators want a notification service that hooks into our application event streams.

## Acceptance Criteria/Tasks
- [ ] GIVEN an application has a condition that needs a human operator to take an action
  AND an operator adds this condition to the notification service
  WHEN the condition occurs within the event stream
  THEN the notification service will send the appropriate alert to operators

## Background
As we move our applications to 12factor, we move closer to having an single [event stream](https://12factor.net/logs) that we can use to monitor and alert. Even if we don't have a centralized, aggregated event stream, we can still treat our log files as individual streams of time-ordered events.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None.

## Questions to address

- [ ] How can we write conditions that would cover these concrete scenarios?
    - Dashboard crawl task has a fatal error (https://github.com/GSA/datagov-deploy/issues/1150)
    - Dashboard crawl takes longer than 24 hours
    - harvest-run takes longer than 24 hours (https://github.com/GSA/datagov-deploy/issues/1958)
    - catalog-web was restarted due to high memory (https://github.com/GSA/datagov-deploy/issues/1449)
    - harvest jobs are older than X days
    - a cron job fails
- [ ] How can we configure different conditions to apply to different notification channels e.g. Alert condition vs Warning condition?
- [ ] Is there a solution that will work for BSP and cloud.gov? For this story we at least want to address BSP).

## Sketch
[monit]() has a [FILE CONTENT](https://mmonit.com/monit/documentation/monit.html#FILE-CONTENT-TEST) test which tails a file looking for a regexp. It can ALERT or even take another [action](https://mmonit.com/monit/documentation/monit.html#ACTION) like restarting a service or running a script.

Monit could be done as a side-car for cloud.gov, but the cloud.gov event stream is really logs.fr.cloud.gov, an ELK stack. Something like Elastalert might be a better solution.

**Comment by mogul** [comment]
> Monit could be done as a side-car for cloud.gov, but the cloud.gov event stream is really logs.fr.cloud.gov, an ELK stack. 

logs.fr.cloud.gov is more of a log collection system rather than a stream we'd directly want to alert on. For Monit purposes, we probably want it watching something more like [`log-cache`](https://www.youtube.com/watch?v=9xJ6QW5ZA3M).

I spoke to Adam about a potential design for a Monit "service". You'd have two components:

1. A standalone Monit app that watches the logs and metrics streaming out of all the applications that it's bound to
1. A Monit sidecar process which periodically grabs a centralized config (from a URL in the bound service credentials), then watches for noteworthy local events and takes appropriate responses inside the container according to that config.

I haven't thought about  how we might do this outside cloud.gov, but it seemed like a pretty solid way to use the provided extension points in CF.

**Comment by mogul** [comment]
By the way: 
> Something like Elastalert might be a better solution.

We're unable to run our own ES stuff like Elastalert in the shared logs.fr.cloud.gov instance. It's multi-tentant, but only just barely and we don't have enough access to configure Elastalert just for us.

If we do want to alert based on collected (rather than streamed) logs+metrics, then the way to do it is to broker our own instance of [AWS Elasticsearch](https://aws.amazon.com/elasticsearch-service/), set our logs to drain there, then use [the Alerting plugin](https://opendistro.github.io/for-elasticsearch/features/alerting.html).

**Comment by mogul** [comment]
Note AJ [did a bunch of work](https://github.com/18F/vuls-cloudfoundry-buildpack/pull/13) on the vuls buildpack which basically makes it fit this description.

**Comment by mogul** [comment]
> If we do want to alert based on collected (rather than streamed) logs+metrics, then the way to do it is to broker our own instance of [AWS Elasticsearch](https://aws.amazon.com/elasticsearch-service/), set our logs to drain there, then use [the Alerting plugin](https://opendistro.github.io/for-elasticsearch/features/alerting.html).

In the time since this was written, cloud.gov began supporting brokering of AWS Elasticsearch. This is probably the best way to get what we want for the centralized alerting at this point, rather than running a custom Monit process in the management space. We may still want a local Monit sidecar deployed alongside applications to watch container-internals for signs of compromise.

**Comment by mogul** [comment]
Going to consider this closed/Done since we have pretty much already made the determination that we'll go forward with the brokered AWS Elasticsearch.

**Comment by adborden** [comment]
https://github.com/GSA/datagov-deploy/issues/2814
