### ISSUE TITLE
Inventory-next DB initialization

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#2038]
## User Story

As a data.gov developer, I want the inventory-next DB initialized and notes describing the process so that inventory-next DB will work.

## Acceptance Criteria

- [ ] GIVEN inventory-next is setup properly \
  WHEN an admin runs `ckan db init` on inventory-next sandbox \
  THEN the database is configured \
  AND implementation notes/manual steps are documented

## Background
Related to #1678. Blocks #1675.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
None

## Sketch
Will want to test and run manually. The datastore extension may need to be fully configured/setup or removed from the `production.ini` file for testing.

As an output, please place relevant manual steps here as they may need to be run on staging and production, highlighting those that are different from the documentation...

Relevant documentation:
 - [The normal DB setup process](https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html#setup-a-postgresql-database)
 - [Creating CKAN tables](https://docs.ckan.org/en/2.8/maintaining/installing/install-from-source.html#create-database-tables)
 - [The datastore access will need to be setup](https://docs.ckan.org/en/2.8/maintaining/datastore.html#setting-up-the-datastore)

**Comment by adborden** [comment]
Might be helpful reference:

as part of the [cloud.gov work]( https://github.com/GSA/inventory-app/compare/master...feature/cloud.gov#diff-be986f3c48184d9f0712c77428dc060b), there was some effort done to handle db and datastore initialization to the startup scripts.

.. and of course the [CKAN docs](https://docs.ckan.org/en/2.5/maintaining/datastore.html#set-up-the-database).

**Comment by FuhuXia** [comment]
An [inventory-db-init.py](https://github.com/GSA/datagov-deploy/blob/f022ccb3193bff1e9d512a575cde2c8682c16ea8/ansible/roles/software/ckan/inventory/files/inventory-db-init.py) python script is created to  

1. Connnect to a blank postgres database,
2. Creates necessary CKAN and Datastore databases, roles, and set permissions, and finally 
3. Run `sudo ckan db init` command to initialize the ckan database.

It assumes the database is blank. If the CKAN or Datastore databases, or some of the roles already exist, the script will exit without making any further changes.

There are some minor but necessary modifications from official CKAN db set up procedure, due to how the master role is set up in AWS RDS without full privilege. We addressed it by some temporary workaround such as grant Datastore user `createdb` permission, but later in the process we revert those workaround changes to make sure the db is in the same state as if it was created with official CKAN procedure.

To run this script, 
```
sudo inventory-db-init.py
```

**Comment by FuhuXia** [comment]
More changes to `inventory-db-init.py`
1. Making the script more flexible and forgiving, since the AWS DB may come with an initial database created.
2. Dealing with issues when CKAN database and Datastore database are on different hosts. In [CKAN official docs](https://docs.ckan.org/en/2.9/maintaining/datastore.html) this scenario is supported but the `paste datastore set-permissions` will generate some errors, as reported upstream https://github.com/ckan/ckan/issues/5598.
