### ISSUE TITLE
SNYK vulnerability found in resources.data.gov

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2041]
_Please keep any sensitive details in [Google Drive](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.fhr89vwohzbq)._

**Date of report:** 08/17/2020
**Severity:** High
**Due date:** 09/17/2020

_Due date is based on severity and described in RA-5. 15-days for Critical, 30-days for High, and 90-days for Moderate and lower._

- [x] Analysis has been performed and an issue has been linked to address other occurrences for this class of vulnerability\* (_link_)

_\* When a finding is identified, we create two issues. One to address the specific instance identified in the report. The other is to identify and address all other occurrences of this vulnerability within the application._

### Brief description
[Google Doc](https://docs.google.com/document/d/1rW0VOzfCrjXOI0O1gTAOm225_fTbu5Cjrg7yJTYYBBg/edit#heading=h.fhr89vwohzbq)

**Comment by chris-macdermaid** [comment]
This vulnerability is caused by node-sass requiring an old version (2.25) of sass-graph which requires version 4.17.19 of lodash. According to https://github.com/sass/node-sass/issues/2863, it should be resolved in version 5 but there is no date for version 5 to be released.

There is a package that potentially fixes the issue, but don't think it would stop the vulnerability from continuing to be reported.
https://www.npmjs.com/package/no-pollution

**Comment by chris-macdermaid** [comment]
The vulnerability is caused by node-sass requiring an old version (2.25) of sass-graph which requires version 4.17.19 of lodash. According to sass/node-sass#2863, it should be resolved in version 5 but there is no date for version 5 to be released.
There is a package that potentially fixes the issue, but don't think it would stop the vulnerability from continuing to be reported.
 https://www.npmjs.com/package/no-pollution

**Comment by chris-macdermaid** [comment]
Updated to lodash to version 4.17.20 by removing concurrently, gulp-sass, and lodash. Then installed concurrently followed by gulp-sass.

https://github.com/GSA/resources.data.gov/pull/241
