### ISSUE TITLE
Setup Role for Host Hardening and Baseline Configuration - CIS Ubuntu Benchmark

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#22]
https://github.com/GSA/cis-ubuntu-ansible
http://cis-ubuntu-ansible.readthedocs.io/en/latest/CIS_Ubuntu/

Center for Internet Security Benchmark for Ubuntu 14.04 is a set of Best Practices on "hardening" the Host Operating System. This Baseline image is then used to build applications on top of  
- [ ] Fix or Remove currently failing/skipped tasks
- [ ] Use Ansible tags to map tasks to NIST-800-53 security control groups for future auditing

**Comment by neilhunt1** [comment]
@JJediny almost done here, only thing I am still stuck on is AppArmor in section04. I can get it to run correctly, but then host is unreachable after restart. So I need to figure out what's going on with this (unless you say we can disable AppArmor for some reason). Otherwise I created an AMI with all patches applied to succeed in sections 1-3 and 5-13.

**Comment by neilhunt1** [comment]
AMI now passing all CIS tests. I am trying to build final image with Packer via Jenkins, looks like the hardening process locked down some dirs that Packers uses so working those out
