### ISSUE TITLE
[Research] Inventory-next anonymous user sees dataset page

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#2314]
Inventory-next displays dataset page to anonymous user.

## How to reproduce

Open chrome in incognito mode, go to inventory-next page on sandbox or staging.

## Expected behavior

See message "You are not authorized to do this" and a **Log in** button.

## Actual behavior

See the dataset list.

#### First Step:

- As a team, decide if we want `actual behavior` or `expected behavior`

**Comment by mogul** [comment]
Needs discussion as to whether this is more desirable behavior in any case. This may be more about documenting acceptable/recommended usage of inventory.data.gov for users who might be trying to use it for distributing private data.

**Comment by mogul** [comment]
Summary: We need to investigate why the behavior is different from the previous version, but we also need to decide if the previous behavior is what we wanted.

**Comment by adborden** [comment]
These are alternative issues that I think we should consider instead of this issue. We know the existing behavior on inventory-classic is incorrect/incomplete. Instead I think we want to consider making datasets explicitly public and tweak the draft behavior:

https://github.com/GSA/datagov-deploy/issues/2096
https://github.com/GSA/datagov-deploy/issues/2095
https://github.com/GSA/datagov-deploy/issues/1863

**Comment by mogul** [comment]
We should also research how/if the redaction feature is being used as-is.

**Comment by jbrown-xentity** [comment]
Questions:
 - Are agencies putting any private data (metadata fields or data files or existence of data itself) on inventory?
    - In your use of inventory, do you have any data or metadata that should not be viewable by the public?
    - Would you utilize a feature in the future that could restrict access to the public for specific metadata fields or data files?
 - If inventory will be publicly available, should we add a robots.txt file to limit/stop search engines from indexing?

**Comment by hkdctol** [comment]
@jbrown-xentity I think the two questions you have as sub-bullets are good to send out as-is--does that sound ok? I can get it to inventory users today

**Comment by jbrown-xentity** [comment]
@hkdctol sounds good to me!

**Comment by hkdctol** [comment]
@jbrown-xentity reviewed 12 google form responses and a few others that came by Word doc. We also sent again today to open data listserv. A fair amount of interest in being able to store non public information going forward. Doesn't seem that anyone is using it for non-public information right now. Let's see if we get more responses in the next few days.

**Comment by mogul** [comment]
Hyon's giving this a couple more days before we make some decisions.

**Comment by mogul** [comment]
Survey results summary:
- People are interested in using inventory for non-public information.
- People seem confused about what that actually means.

We are all still confused about which settings apply, and what the norms should be, so Hyon is scheduling a meeting for us to talk in more detail.

**Comment by adborden** [comment]
Questions to be answered:
- Where are all the bits of code in inventory-classic that are affecting this observed behavior (links to commits in USMetadata, ckan, ckanext-saml2)?
- Does CKAN configuration support defaulting new datasets to private? Does the new metadata form use CKAN's default value for `private`?
- Do we need to fix the [Draft status behavior](https://github.com/GSA/datagov-deploy/issues/2095)?

**Comment by jbrown-xentity** [comment]
Found this discussion detailing how to [allow access to CKAN datasets only when logged in](https://stackoverflow.com/questions/27360247/ckan-with-data-access-only-after-login#27932651), leaving it here in case we need it. 
CKAN does not have a [configuration option](https://docs.ckan.org/en/2.8/maintaining/configuration.html) for detailing if created packages are public or private by default, not sure what the default is in code...

**Comment by adborden** [comment]
@adborden and @chris-macdermaid to circle up on next steps.

**Comment by jbrown-xentity** [comment]
> 
> 
> Questions to be answered:
> 
>     * Where are all the bits of code in inventory-classic that are affecting this observed behavior (links to commits in USMetadata, ckan, ckanext-saml2)?
TODO
> 
>     * Does CKAN configuration support defaulting new datasets to private? Does the new metadata form use CKAN's default value for `private`?
No, this is not supported in [CKAN configuration](https://docs.ckan.org/en/2.8/maintaining/configuration.html). Unknown for new metadata form. [This logic to make datasets public](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L691-L698) is part of the classic and next inventory backend, with a standard [disclaimer banner at the top of the resource edit page for inventory classic](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/templates/package/snippets/resource_form.html#L4) (I don't believe there is a similar feature in inventory-next).
Unknown if new metadata form defaults to `private` for datasets otherwise.
> 
>     * Do we need to fix the [Draft status behavior](https://github.com/GSA/datagov-deploy/issues/2095)?
Already addressed.

**Comment by jbrown-xentity** [comment]
Items left for discovery:
- Identify how datasets were created by default private in classic, and verify in inventory-next (and when data is added, dataset is made public)
- An anonymous user should be redirected to a `login needed` or `access denied` type page

**Comment by jbrown-xentity** [comment]
The code that was handling the redirects and locking out anonymous users is [here](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L581-L603).
This code was first [commented](https://github.com/datopian/USMetadata/commit/bc63833d94b81887ec929b6a3dd9b5663a21c2fe) and then [removed](https://github.com/datopian/USMetadata/commit/bfd2a356d0ae10843daa9b032f3b346d54ec0128) for the [usmetadata ckan-2-8 branch](https://github.com/GSA/USMetadata/blob/ckan-2-8/ckanext/usmetadata/plugin.py).
I believe this was originally edited because this is no longer how we should handle authorization.
The next step should be to read through the [CKAN docs on IAuthFunctions interface](https://docs.ckan.org/en/2.8/extensions/tutorial.html#implementing-the-iauthfunctions-plugin-interface) and establishing where this code should be implemented (new extension, etc).

**Comment by jbrown-xentity** [comment]
[This logic](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L689-L696) makes datasets that are private into public when a resource is loaded onto inventory (so that users can view/download the resource).
[This logic](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/plugin.py#L999-L1017) combined with the [old template](https://github.com/GSA/USMetadata/blob/master/ckanext/usmetadata/templates/package/snippets/package_basic_fields.html#L90-L94) defaulted all datasets to private, and hid any configuration from users. We will need to do something similar in the dcat_usmetadata extension that when the [package_create api is called](https://docs.ckan.org/en/2.8/api/index.html#module-ckan.logic.action.create) we default to `private=True`. The logic would seem to be added [here](https://github.com/GSA/ckanext-dcat_usmetadata/blob/master/metadata-app/src/api/index.js#L293-L314), but some of the logic seems wrong (why are we setting the bureau_code and program_code at this level, shouldn't that be user defined?).
We will let [this work](https://github.com/GSA/datagov-ckan-multi/issues/422) be complete before suggesting any changes.

**Comment by jbrown-xentity** [comment]
Research is complete, new tickets created as necessary.
