### ISSUE TITLE
Bad link for Montana in https://www.data.gov/open-gov/ U.S. States List View

### ISSUE THREAD

**Issue by ndevine** [GSA/data.gov#2320]
The link listed for Montana under https://www.data.gov/open-gov/  U.S. States link under List view is listed as `https://data.datamontana.us/browse` - this is incorrect. It takes you to a one-page site in French.

`<a data-toggle="modal" data-target="#data_table_1" rel="noopener noreferrer">U.S. States</a>`

## How to reproduce

1. Go to `https://www.data.gov/open-gov/ `
2. Click on the link under `List View` for `U.S. States`
3. Observe the listed link for Montana and click on the link to navigate to the listed site

## Expected behavior

Go to the actual site for the U.S. State of Montana for open data

## Actual behavior

Go to https://data.datamontana.us/browse which is a site in French that has nothing to do with the U.S. State of Montana

**Comment by jbrown-xentity** [comment]
Probably should be https://data.mt.gov/

**Comment by jbrown-xentity** [comment]
We thought this was fixed with the above PR, but that just fixes the data on the map. The data in the csv download is correct, however the data in the table is created from [this script](https://github.com/GSA/data.gov/blob/ae96936bec3c66446ae0b20f1cab47835be3a575/roots-nextdatagov/templates/content-opengov.php#L30). The setting for that URL is found on the [wordpress admin settings page](https://www.data.gov/wp/wp-admin/options.php) (under `us_states_open_data`). This points to a [csv file on the FCS s3 bucket](https://s3.amazonaws.com/bsp-ocsit-prod-east-appdata/datagov/wordpress/2016/10/us_states.csv). Still not sure how to edit/update that file.

**Comment by jbrown-xentity** [comment]
The current dataset was updated by the following:

- Search `us_states` on the [wordpress media page](https://www.data.gov/wp/wp-admin/upload.php?search=us_states) and taking the most recent (top left) file and downloading this file
- Edit the necessary fields locally
- Re-upload this edited file (you may need to utilize the workaround detailed [here](https://github.com/GSA/datagov-deploy/issues/1830)). 
- Get the access/download link from this latest upload (view the details)
- Insert that value into the corresponding value on the [settings page](https://www.data.gov/wp/wp-admin/options.php) (in this case, `us_states_open_data`, found [here](https://github.com/GSA/data.gov/blob/ae96936bec3c66446ae0b20f1cab47835be3a575/roots-nextdatagov/templates/content-opengov.php#L8-L10))
- Clear the cache on [cloudfront]( https://console.aws.amazon.com/cloudfront/home?region=us-east-1#distribution-settings:EY7DTNZQD0CRG)
