### ISSUE TITLE
Submission on data.gov/contact form not going to datagov@gsa.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2504]
The form on https://data.gov/contact is designed to go to datagov@gsa.gov, the general public feedback google group.

## How to reproduce

Go to https://data.gov/contact and fill out a test submission

## Expected behavior

Members of datagov group should get the submission as an email in their inboxes. The submission should also appear in the datagov google group view.

## Actual behavior

Submissions not in inbox or in group view. An individual emailing the datagov@gsa.gov address directly does reach the datagov group through inbox and group view.

**Comment by adborden** [comment]
This looks like our FROM address for the contact form has not been updated from https://github.com/GSA/datagov-deploy/issues/507 and so mail is being rejected after the handoff to GSA.

I'm going through each [contact from](https://www.data.gov/wp/wp-admin/admin.php?page=wpcf7) and updating the FROM address. We now see a configuration warning that the sending address does not match the site domain, but this is okay because of how our SMTP servers are configured.

**Comment by adborden** [comment]
I updated our wiki with more information on [Email](https://github.com/GSA/datagov-deploy/wiki/Email) and [Topics](https://github.com/GSA/datagov-deploy/wiki/Topics).

**Comment by adborden** [comment]
There might be a record of the dropped emails in wordpress.
