### ISSUE TITLE
Existing inventory users can authenticate using login.gov 

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2533]
## User Story

As Data.gov PMO, we want to make sure that the new CKAN 2.8 version of inventory has authentication through login.gov for all the current agency users so that agency users can use inventory.data.gov without interruption at the upgrade. 

## Acceptance Criteria

- [ ] GIVEN CKAN 2.8 version of inventory.data.gov is live AND login.gov authentication has been deployed
  WHEN a current inventory user logs in through login.gov 
  THEN the agency inventory user is able to use the new inventory.data.gov as before in their assigned roles (mostly Editor, with a few Admin)
  

## Background
There are approximately 80 users of inventory.data.gov across many agencies. Users currently authenticate through OMB MAX with 2FA, and mostly have Editor roles for their organization, with a few users as Admin, and Sysadmin for Data.gov PMO.

## Sketch
- [ ] Contact inventory users and inform them of upcoming change to login.gov and provide instructions on creating login accounts
- [ ] Migrate information about current accounts and roles from current inventory to new inventory.data.gov
- [ ] Communicate with users about launch date of new inventory.data.gov
- [ ] Launch new inventory.data.gov
- [ ] Encourage users to try log in using login.gov accounts and test their access of new inventory.data.gov
- [ ] Work with individual users who report not having the expected access

**Comment by hkdctol** [comment]
Closing as duplicative of #2220

**Comment by adborden** [comment]
Need to re-groom about this being how to migrate the users and update #2220 to take that part out.

**Comment by FuhuXia** [comment]
Existing users (CKAN native or MAX.gov) can seamlessly get authenticated with login.gov after the new Inventory 2.8 integrated with login.gov. The extension `ckanext-saml2auth` is using email address found in the saml info passed from login.gov to query CKAN user table, the query is equivalent to 
```
SELECT * FROM user
WHERE email = 'fuhu.xia@gsa.gov' 
ORDER BY name
```
If multiple user entries found in the database, it picks the first one.  If the picked user is in `deleted` state, it activates it. That is the only change `ckanext-saml2auth` will do to the user table, all other user's info including activity history, editor role... remains intact.

In order to prepare inventory's SSO IdP switch from MAX.gov(with ckanext-saml2) to login.gov (with `ckanext-saml2auth`), we need to make sure email addresses in Inventory CKAN user table are unique, and are all lower case. A separate issue will be created for this housecleaning task.
