### ISSUE TITLE
Deploy www app on cloud.gov

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2605]
## User Story

In order to reduce the operation and maintenance burden of `www.data.gov`, the data.gov team wants the `www.data.gov` application deployed on cloud.gov.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] WHEN I commit a change to the `main` branch in the [GSA/datagov-wp-boilerplate](https://github.com/GSA/datagov-wp-boilerplate) repository \
  AND I browse to [the GitHub Actions tab](https://github.com/GSA/datagov-wp-boilerplate/actions)
  THEN I see a deployment pipeline kick off \
  AND the pipeline completes successfully \
  AND the change is visible at https://www-data-gov.app.cloud.gov
- [ ] If any manual preparation of the target space was necessary, then an issue exists about automating that setup in future.

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
We are deploying from the `main` branch to the `gsa-datagov/production` space only. Other branches and spaces are considered out of scope here. Note cronjobs are also out of scope for now.

Cloud.gov has an [example on how to deploy wordpress](https://github.com/cloud-gov/cf-ex-wordpress)

Our repository is already based on the 12-factor-friendly [Bedrock WP boilerplate](https://roots.io/bedrock/).

For migrating S3 content, use [these instructions](https://cloud.gov/docs/services/s3/#interacting-with-your-s3-bucket-from-outside-cloudgov) to avoid tunneling through cloud.gov.

For migrating DB content, use [these instructions from cloud.gov](https://cloud.gov/docs/services/relational-database/#exporting-a-database), and make it easier on yourself with the [service-connect plugin](https://github.com/cloud-gov/cf-service-connect).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
None. This work is being done in an environment completely separate from the existing deployment, and only open source and open data are implied.

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]

- [ ] Rename the `master` branch if necessary
- [x] Bring any existing cloud-gov branch up to date
- [x] Create any necessary services in the target space with `cf create-service`
- [x] Create a manifest.yml capturing any settings or bindings
- [x] Practice a hand-driven deployment
- [x] Ensure environment settings are installed from `$VCAP_SERVICES`
- [x] Make sure the health check is correct and passing
- [x] Make sure the homepage comes up
- [x] The README.md should have instructions for hand-deployment
- [ ] Add CircleCI or GitHub Action config for deployment to the `production` space

**Comment by jbrown-xentity** [comment]
@adborden @mogul could use some direction on the approach for environment setup here. I'm trying to merge the [cloud.gov wordpress deployment example](https://github.com/cloud-gov/cf-ex-wordpress#installation) with the [roots deployment docs](https://roots.io/docs/bedrock/master/configuration/) and struggling on how to do the setup dynamically. Do I want to add a `.profile` script that parses vcap services? I'm assuming for [salts and keys](https://github.com/cloud-gov/cf-ex-wordpress/blob/master/setup.sh.example) I should setup a secret...
There is also this [setup.json](https://github.com/cloud-gov/cf-ex-wordpress/blob/master/setup.json.example), which has admin usernames and passwords but also theme, plugin info, etc... Should I make a base one and edit it on startup with jq in the `.profile`? Or something else I'm not thinking of?

**Comment by jbrown-xentity** [comment]
@mogul it's working, see draft PR and live staging site [here](https://wordpress-stage-datagov.app.cloud.gov/). Still a lot of things to configure and should test db backup install soon, but looking good! Thanks for your help!

**Comment by mogul** [comment]
We've decided to avoid tangled technical debt work on simpleSAMLphp and instead plunge head-first into converting over to a static site. 

- [x] @jbrown-xentity is going to park the existing work on a branch and document it here (for potential future use as a better example of running WordPress on cloud.gov
- [x] @mogul will remove references to www from the data.gov SSP
- [x] @mogul will `Icebox` this issue

**Comment by jbrown-xentity** [comment]
Our current work is in the `feature/cloud.gov` branch on [datagov-wp-boilerplate](https://github.com/GSA/datagov-wp-boilerplate/tree/feature/cloud.gov).  The work as is can deploy an instance, however the styling is all wrong. It was determined that the setup needed to occur before the server application starts up as in the [cloud.gov wordpress example](https://github.com/cloud-gov/cf-ex-wordpress). From where the application is on this branch, we would want to 

- Better parse the VCAP_SERVICES environment variables in the `lib/application.php` file similar to the [cloud.gov example](https://github.com/cloud-gov/cf-ex-wordpress/blob/master/wp-config.php), and remove the `bootstrap.sh` file and `options.json` `ADDITIONAL_PREPROCESS_CMDS` flag. You could test this locally by grabbing the environment from a cloud.gov deployment and putting the VCAP_SERVICES variable into the docker environment.
- Add an extension similar to [cloud.gov example](https://github.com/cloud-gov/cf-ex-wordpress/blob/master/.extensions/wordpress/extension.py) to download and install wordpress. Need to make sure that the compose install has already been run (so you don't need to install wp-cli), so you might need to run under [service_environments](https://github.com/cloudfoundry/php-buildpack#method-order) instead of compile (which is when [composer runs](https://github.com/cloudfoundry/php-buildpack#extensions)).

We already handled bundling all components into composer, installing all themes, moving all non-public files (vendor, etc) into the `/lib` folder.

**Comment by mogul** [comment]
I've scrubbed all references to WordPress and www.data.gov from the SSP, and [replaced them with equivalent information about fgdc2iso](https://github.com/GSA/datagov-deploy/issues/2746). The www-specific diagrams are left in place but will be replaced by fgdc2iso-specific diagrams in the course of completing that issue.

**Comment by mogul** [comment]
We have decided not to migrate www.data.gov to cloud.gov. Instead, we'll be reimplementing the Wordpress site as a static site under Federalist, and leveraging the GSA ATO for Federalist.
