### ISSUE TITLE
Production CI/CD Pipeline

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#28]
Packer may or may not be available to us in the new environment @dano-reisys @neilhunt1 lets  re-propose all alternative approach(es) for discussionn:

Including but not limited too:
- Replacing Packer with Jenkins/Ansible for AMI Creation (not efficient but neither is not using Terraform for infrastructure creation :8ball: )
- Spectrums of using Jenkins (100%) <-> Ansible (80%) 

Digging deeper and deeper into the rabbit hole of all options and approaches... CI/CD with ansible has two core approaches with no downtime:
- Pre-baking Images (AMI) to an AWS Auto-Scaling Group.
- Rolling updates to a Highly Available set of services for each app - and coordinating with a web proxy to offload traffic to the to be or being provisioned machine then cycling through instances until all are updated.
### Pros
- Simplest approach to vertically scale the application
- Most cost effective (as compared to having to run application in High Availability with a preferably odd  number of (3-5) instances per service/application. While not a best practice,  for rolling updates,  can be done on 1 load balancer/proxy to 2 apps servers - particularly if you have a mirror of the same setup in another region/availability zone. That's still 6 @ 24/7 instances for rolling updates compared to 2-3 minimum with x^ max completely managed by traffic demands, cpu/memory thresholds, or time of day which is more economical
- AMI(s) are their own artifact
- Immutable/fault tolerant when scaled exponentially
- Talks AWS native speak to ELBs.
- Everything is ready to run out of the gate (near 0 downtime)
### Cons
- System state is a nightmare if system needs state.
- Is rigged to A/B Testing Scenarios
- Doesn't pay to invest in if the "service" for a "Service" could otherwise have been handled by one instance running over a day or week... especially if cpu/memory depends aren't related to daily traffic and production code is push infrequently.
- Images are large and cumbersome to be used to push out for minor code updates. 
- Expensive in the cheap sense - they are heavy to make but only when code is uptaken to Jenkins and then offloaded to s3 for 5x revert ready roll backs. Counter intuitive with last point - this is a pro or con depending on the reality of traffic/update frequency.

```
Git --> [ Jenkins {ansible} Jenkins ] ---> AMI [ ] --->  |  <---[ ASG ]--->   |  ----> S3

OR

             [ Ansible ]         
        /       /        \       \    
   [ X ]    [ X ]    [ X ]   [ X ]
     2\        4\         6\        8\
[ 1 ][ 2 ] [ 3 ][ 4 ] [ 5 ][ 6 ] [ 7 ][ 8 ] 

              .... Then.....

             [ Ansible ]         
        /       /        \       \    
   [ X ]    [ X ]    [ X ]   [ X ]
    /1         /3         /5        /7
[ 1 ][ 2 ] [ 3 ][ 4 ] [ 5 ][ 6 ] [ 7 ][ 8 ] 

```

**Comment by JJediny** [comment]
For development phase we can continue, just need to document the alternative methods we will need post-migration

**Comment by neilhunt1** [comment]
We need to understand Jenkins and Ansible Tower environments better. Dan and I discussed this Monday. Here are some questions to consider in determining if we want to bake a new AMI every time or consider some other deployment process:

1.       How will we maintain AMI library? If we bake an AMI on every single build, the library will get quite large as these aren’t small files?
2.       Do we have any incremental alternatives, such as Docker, or CodeDeploy, or some other process? If Ansible Tower can do this, definitely we should consider that. Each AMI right now is 40GB; are there options to use an existing AMI but deploy a new version of the code to it? Otherwise, we’d be creating 40+GB AMIs on every single build, just to change a single code file. Not saying we can’t or shouldn’t do that, just opening some discussion.
3.       Archive: what level of archiving do we want? How long do we keep our previously deployed artifacts? Presumably this may be different for DEV builds than higher environment builds? Regardless, we will want to find a way to automate this archival process.
4.       With a build-once/deploy-many pipeline, we will presumably have (at least) two AWS accounts, possibly even with multiple regions. If we need an AMI for each of these accounts, we will depend on Jenkins to push at the appropriate stage to the right account? It’s certainly capable of doing that, but we’ll need to have the appropriate slaves setup within the correct accounts and VPCs to do this (unless BSP gives us AWS keys ourselves to manage, but I’m assuming this won’t be the case)
5.       Have we clarified with BSP on how we will do this? My understanding of mode 1 is that BSP provisions the resources, but we handle app deployments. However, all they give us is a jumpbox with SSH access into the various boxes for the deployment, and we handle the deployment ourselves. Doing a full AMI replacement will require higher level AWS calls beyond SSH access. So in order to be able to execute an automated ASG update, presumably through Jenkins, we would need the correct slave configuration for this as well.

**Comment by neilhunt1** [comment]
@JJediny and I spoke today and at a high level, here are the options on the table for handling playbook deployments

1. Bake an AMI each time that runs the playbook as part of the AMI creation process; use AWS keys on the Jenkins slave to update/create new infrastructure based on the new AMI; that would require write-capable AWS keys
2. Jenkins calls ansible natively on the slave; would require correct SSH keys to connect to the instances on which we're running the play and a read-only AWS key to at least be able to read the AWS tags as ansible would handle dynamic infrastructure by reading those tags. Jenkins would use the playbook checked out of git
3. Jenkins would call Ansible Tower REST API; that would require that Jenkins has some ansible tower credentials; pro is that ansible tower continues to be master ansible deployment tool and this would presumably be most consistent with other mode 3 deployments. Cons are we'd need to learn and understand Ansible Tower and more importantly, how to use its REST API from Jenkins
4. We could consider using AWS CodeDeploy to orchestrate the playbook deployments. Pros to this are that it natively ties into AWS tags to do deployments and works out-of-the-box with autoscaling groups; also it's free and hosted by AWS so nothing to setup on our side; cons are, if BSP is already using Ansible Tower, then it would be preferable to follow their convention so all deployments happen same way (e.g. use option 3 instead of this one)

**Comment by afeld** [comment]
Is there a branch/repository for the Jenkins work?

**Comment by neilhunt1** [comment]
Yep, take a look at our master-demo branch Jenkins folder: https://github.com/GSA/catalog-deploy/tree/master-demo/jenkins

**Comment by adborden** [comment]
Closing as this is not relevant to our current stack.
