### ISSUE TITLE
USGS Combined Vector Downloadable Data -- harvest source not harvesting

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2906]
This is a valid harvest source we confirmed with USGS rep.

## How to reproduce

Check new catalog on this source.

## Expected behavior

Old catalog shows 929 datasets associated with this source.

## Actual behavior

Source is in new catalog under USGS but with no datasets

## Sketch
-Try manual harvest
Name: USGS Combined Vector Downloadable Data Collection
URL: http://thor-f5.er.usgs.gov/ngtoc/metadata/waf/combined/vector/
See notes in line 1083 of this worksheet: https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?usp=sharing

**Comment by mogul** [comment]
Waiting on conversation with USGS

**Comment by mogul** [comment]
Pinged USGS rep today; no response yet.

**Comment by hkdctol** [comment]
Created a new root record harvest source.

**Comment by hkdctol** [comment]
Harvest of the root only record did not work - with the errors seen below![Screen Shot 2021-05-11 at 11.40.45 AM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/5f90efd8-ea19-4c75-95da-87b2a5f6e7f3)

**Comment by FuhuXia** [comment]
Checked in the DB. There is `265680` datasets harvested, but all harvested as private datasets, that is why it shows as 0 on the UI. We might need to create a separated issue investigating why it was set as `private`. 

As far as harvesting goes, it is just slow, no other particular issues with this harvest source. We had to stop this harvest job because it take too long to finish and slow down all other harvest jobs.

Detailed discussion in [Slack](https://gsa-tts.slack.com/archives/C2N85536E/p1620660679005300?thread_ts=1620399039.002500&cid=C2N85536E).
