### ISSUE TITLE
Logo is added to organization in catalog but does not display on dataset page

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2983]
NCUA was added as an organization to catalog, with a URL for logo:  https://www.ncua.gov/files/graphics/ncua_seal_blue_web.gif

## How to reproduce

Go to https://catalog.data.gov/dataset/publicly-available-financial-performance-data-for-federally-insured-credit-unions

## Expected behavior

Logo should appear on upper left on dataset page

## Actual behavior

No logo appears
![NCUA dataset](https://user-images.githubusercontent.com/3236989/110851225-c060ed80-827e-11eb-946e-d3fe27e6ac45.png)

**Comment by jbrown-xentity** [comment]
Start with the function [get_bureau_info in ckanext-datagovtheme](https://github.com/GSA/ckanext-datagovtheme/search?q=get_bureau_info). This is used to render the image on the package page:
https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/templates_new/snippets/organization.html#L14-L50
Something is going wrong here with the image url being defaulted too, need to investigate further. Something might have changed in CKAN2.9.

**Comment by btylerburton** [comment]
@jbrown-xentity what is the process for adding logos to https://github.com/GSA/ckanext-datagovtheme/tree/main/ckanext/datagovtheme/fanstatic_library/images/logos directory? As that's the location `get_bureau_info` is trying to pull from.

This dataset works, for example: https://catalog.data.gov/dataset/chemical-phytoplankton-zooplankton-benthic-organisms-and-other-data-from-moored-current-me

Because https://catalog.data.gov/images/logos/006-48.png exists

**Comment by jbrown-xentity** [comment]
If someone wants to add their bureau logo, then we add it (basically on a request basis).
In this case, someone setup the organization to have a link to their logo: https://catalog.data.gov/organization/national-credit-union-administration (you can inspect the page to see the image is actually from ncua.gov) The would expect that image to show up on their dataset pages (as is standard on CKAN), but it doesn't: https://catalog.data.gov/dataset/ncua-active-federally-insured-credit-unions-list-59c68
My guess is something changed in the data such that https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/templates/templates_new/snippets/organization.html#L47 doesn't work anymore, maybe the organization data isn't right? Or something else we can't see possibly... We should be able to customize for each bureau, but the default ckan should still work. It looks similar upstream: https://github.com/ckan/ckan/blob/2.9/ckan/templates/snippets/organization.html#L30

**Comment by btylerburton** [comment]
yeah, for some reason `organization.image_display_url` is no longer available at the dataset level. just `organization.image_url`. should have a draft branch up shortly.

**Comment by btylerburton** [comment]
>but the default ckan should still work. It looks similar upstream: https://github.com/ckan/ckan/blob/2.9/ckan/templates/snippets/organization.html#L30

now that's weird and i'm perplexed 😬

**Comment by btylerburton** [comment]
this looks relevant
https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_dictize.py#L439

    image_url = result_dict.get('image_url')
    result_dict['image_display_url'] = image_url

**Comment by hkdctol** [comment]
Putting back in icebox for now given other priorities

**Comment by btylerburton** [comment]
https://github.com/GSA/ckanext-datagovtheme/pull/124/files

This PR addressed one part of the problem, however viewing collections did not contain an `image_url` on the organization object so this did not address the root cause, which was `image_display_url` not being bubbled up to the dataset level.

**Comment by hkdctol** [comment]
saved image to catalog; external URL provided by agency; logos stored in S3; could it be related to bureau/program code-it's the parameter?

**Comment by FuhuXia** [comment]
New findings: The logo image uploaded to organization is not supposed to work, since it is uploaded to the disk on the current app instance, it is gone after a restart.  

+++++++++
[Update:] This PR https://github.com/GSA/ckanext-datagovtheme/pull/153 solved it.

**Comment by jbrown-xentity** [comment]
An example of a dataset who's organization has a logo, but the dataset pages don't: https://catalog.data.gov/dataset/er-asthma-age-0-to-4-a5647.
This line seems to show that the default publisher image is being used, even though it should be rolling to the organization field that points to the organization image URL:
` <li><a href="/organization/"><img style="height:18px; margin-top:-5px;" src="/images/icon-publisher.png" alt="Default Publisher Icon"></a></li>`

**Comment by FuhuXia** [comment]
We have a custom template file organization.html with code change dated 8 years ago. The customization is mostly for bureau_logo and organization_type labeling, which is defunct since the template still mostly based on ckancore 2.3. Will remove the template in order to fix the missing logo issue. will work with other ticket to bring the customization back.

**Comment by FuhuXia** [comment]
Dataset now has org logo displayed.

![image](https://user-images.githubusercontent.com/1392461/217898683-3acc413c-eb5e-4592-9915-047c61290972.png)

**Comment by FuhuXia** [comment]
Organization label is added back.
![image](https://user-images.githubusercontent.com/1392461/218191007-f55c8c85-0e86-495e-a477-9e6882498043.png)
