### ISSUE TITLE
Implement process for upgrading old service instances on cloud.gov

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3083]
## User Story

In order to ensure existing instances get updates relating to compliance or security, the SSB should include a mechanism for updating existing instances, or helping clients migrate between plans.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN I have provisioned an EKS instance INSTANCENAME \
  AND a the SSB is updated to include a new brokerpak version implementing a new feature \
  WHEN I run `cf update-service INSTANCENAME` \
  THEN I can see the new feature is available in INSTANCENAME

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

The CSB team is implementing this functionality upstream. See [this epic in Pivotal Tracker and the set of stories attached to it](https://www.pivotaltracker.com/epic/show/4787376).

[The feature is now available, but is behind a feature flag we need to enable.](https://github.com/cloudfoundry/cloud-service-broker/issues/171#issuecomment-1081862541)

**Comment by mogul** [comment]
The CSB is [implementing this capability upstream](https://www.pivotaltracker.com/epic/show/4787376), and should be shipping it any day now.

**Comment by mogul** [comment]
[Surprise! ](https://cloudfoundry.slack.com/archives/C0164KKEZGX/p1648471408928239?thread_ts=1648148068.771139&cid=C0164KKEZGX)
![image](https://user-images.githubusercontent.com/47762/160448585-d2e67cb5-64c1-40d3-bbe5-d1db69767c17.png)

**Comment by jbrown-xentity** [comment]
@nickumia-reisys can you add link to upstream documentation

**Comment by nickumia-reisys** [comment]
There actually isn't a good central location where this is documented.  Various links,
- [Slack Discussion](https://cloudfoundry.slack.com/archives/C0164KKEZGX/p1648471408928239?thread_ts=1648148068.771139&cid=C0164KKEZGX) (referenced above) from cloud foundry support.
- Upstream [Github Issue](https://github.com/cloudfoundry/cloud-service-broker/issues/171) 
- Upstream [Pivotal Issue](https://www.pivotaltracker.com/epic/show/4787376)
- Upstream [0.10.0 Release Notes](https://github.com/cloudfoundry/cloud-service-broker/releases/tag/v0.10.0)

**Comment by hkdctol** [comment]
This is relevant only if/when we move to EKS broker so moving to Icebox for now.

**Comment by nickumia-reisys** [comment]
As a summary of how this works:
- Before:
  - When a Service was created, it gets a copy of the terraform code from the Broker.
  - The Service instance code can be different from the Broker code.
  - When the Broker is updated, the Service instance code remains unchanged.
  - Running an `update-service` on an existing Service just re-activated the existing terraform code with new configuration parameters.
  - If the code in the Broker was updated, then new Service instances would get the code changes, but existing instances would not.
- After:
  - When a Service is created, it gets a copy of the terraform code from the Broker.
  - The Service instance code can be different from the Broker code.
  - When the Broker is updated, the Service instance code remains unchanged.
  - Running an `update-service` on an existing Service installs the most recent code from the Broker into the Service instance and then activates the new code.
  - If the code in the Broker was updated, then new Service instances would get the code changes.  Existing instances will not get updated unless the `update-service` is run.

Because we made this the default behavior, to achieve the old behavior of leaving the terraform code unchanged on `update-service`, the `BROKERPAK_UPDATES_ENABLED` variable would need to be disabled on the Broker and restarted before the `update-service` occurs.

This feature was critical in pushing updates to existing production instances without downtime.
- Before:
  - There was a service instance in production with production data.
  - To get the newest code into the service, a new service would need to be created, loaded with the data and then swapped for no downtime.  
  - For our CKAN application, the only way to load the data was to connect to production and rebuild the data from scratch.  For this reason, having no downtime was impractical.
- After:
  - There was a service instance in production with production data.
  - To get the newest code into the service, a simple `update-service` would update the existing architecture with the new changes.  As long as the terraform code was non-destructive in the persistent storage resources, minutes-level downtime or less was possible.
  - Example of minutes-level downtime:
    - https://github.com/GSA/datagov-ssb/pull/154
  - Example of days-level downtime:
    - https://github.com/GSA/datagov-ssb/pull/147
    - https://github.com/GSA/datagov-ssb/pull/149

Very much related to
- https://github.com/GSA/data.gov/issues/3826
- https://github.com/GSA/data.gov/issues/2778
- https://github.com/GSA/inventory-app/pull/386
- https://github.com/GSA/data.gov/issues/3697
- https://github.com/GSA/data.gov/issues/3523
- Lots of EKS Brokerpak issues that are not centrally linked to an epic or main issue.  Anytime a new feature was added the the EKS Brokerpak (prior to this ticket), a new service needed to be created. Example: https://github.com/GSA/data.gov/issues/3744

**Comment by nickumia-reisys** [comment]
🖖 Big shoutout to @mogul for keeping on top of the Brokerpak community and mentoring me through this!
