### ISSUE TITLE
Provide Persistent Volumes for brokered services in k8s

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3127]
## User Story

In order to support durable storage for k8s workloads, the EKS brokerpak should configure persistent storage to satisfy Persistent Volume Claims.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background
We're currently using [ephemeral storage for SolrCloud](https://github.com/GSA/datagov-deploy/issues/3071#issuecomment-820606574), which is limited to 20GB and isn't going to get us to production for Catalog.

```
$ sudo du -sh /data/solr5/data/{catalog,inventory}-next
23G     /data/solr5/data/catalog-next
86M     /data/solr5/data/inventory-next
```

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch
[Notes or a checklist reflecting our understanding of the selected approach]
Summary of [this article](https://aws.amazon.com/blogs/containers/running-stateful-workloads-with-amazon-eks-on-aws-fargate-using-amazon-efs/):
- Create EFS filesystem
- Create EFS access point
- Create ingress security group
- Create EFS mount targets in each subnet used by the Fargate profile
- Create PVC (use kubectl to start)

**Comment by mogul** [comment]
Still keeping an eye on this... It looks like it's now possible to [dynamically configure EFS volumes in response to PVCs](https://aws.amazon.com/blogs/containers/introducing-efs-csi-dynamic-provisioning/) without any manual intervention up front. There may still be some restrictions; [the GitHub issue about this capability](https://github.com/aws/containers-roadmap/issues/891#issuecomment-805168629) is not especially clear: The post says they're still working on EKS, but then unceremoniously closes the issue, and the blog post doesn't mention the EKS restriction. 🤷

**Comment by mogul** [comment]
Oh, here's where the confusion is: You can't (yet) run the EFS CSI controller on Fargate. The referenced capability is being discussed [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/313).
![image](https://user-images.githubusercontent.com/47762/120533693-de2d8280-c395-11eb-9ef1-de56342ea3e8.png)

**Comment by mogul** [comment]
Related issue: [Make the size of the Fargate local volume configurable above 20GB](https://github.com/aws/containers-roadmap/issues/384)

**Comment by mogul** [comment]
Looks like [it's now possible to configure up to 200GB ephemeral storage](https://github.com/aws/containers-roadmap/issues/384#issuecomment-914627296).

**Comment by mogul** [comment]
[Persistent Volumes via EBS are now supported via an EKS add-on.](https://aws.amazon.com/about-aws/whats-new/2021/12/eks-add-ons-ebs-csi-driver/)

**Comment by mogul** [comment]
> Looks like [it's now possible to configure up to 200GB ephemeral storage](https://github.com/aws/containers-roadmap/issues/384#issuecomment-914627296).

Unfortunately I misread this... [Fargate can be configured to attach up to 200GB of storage in ECS, not in EKS!](https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-ecs-aws-fargate-configure-size-ephemeral-storage-tasks/)

**Comment by mogul** [comment]
Next steps...

# Enable PVCs in the eks-brokerpak

- [Add the EBS CSI EKS add-on](https://aws.amazon.com/about-aws/whats-new/2021/12/eks-add-ons-ebs-csi-driver/)
  - This enables us to create PersistentVolumes in k8s, and then bind them to pods via PersistentVolumeClaims
- Test that it works (eg create a PersistentVolume)
- Push a tag for a new minor release of the EKS brokerpak that incorporates this change
- [Update the version of the eks-brokerpak installed by the SSB deployment](https://github.com/GSA/datagov-ssb/blob/7261e274181c02a67f33187bca22d11e5f31ac25/app-setup-eks.sh#L5)

# Enable use of PVCs in the solr-brokerpak

- Change the solr-broker to [configure the `persistent` dataStorage option](https://artifacthub.io/packages/helm/apache-solr/solr#data-storage-options) when [deploying the solr helm chart](https://github.com/GSA/datagov-brokerpak-solr/blob/e3fb638328e3d07871f07c10c4a78b8a4df6cbe6/terraform/provision/main.tf#L40)
- Expose the [`dataStorage.capacity` parameter](https://artifacthub.io/packages/helm/apache-solr/solr#data-storage-options) for configuration by the broker's users and use that parameter when provisioning the Helm chart.
- Push a tag for a new minor release of the solr brokerpak that incorporates this change
- [Update the version of the solr-brokerpak installed by the SSB deployment](https://github.com/GSA/datagov-ssb/blob/7261e274181c02a67f33187bca22d11e5f31ac25/app-setup-solr.sh#L5)

**Comment by nickumia-reisys** [comment]
A PR has been started to incorporate this capability.  There were concerns with Fargate compatibility and IAM role permissions.  A glimpse of it working has been witnessed with managed node groups provisioned along with choosing the following option,
![image](https://user-images.githubusercontent.com/85196563/148625387-3518d0c6-0414-4bc5-8fd3-0c9725cbcc98.png)

This work has been postponed due to a workaround with shard implementations for Solr.  

The next steps for this issue,
- [x] Figure out issue regarding https://stackoverflow.com/questions/70171641/aws-eks-nodes-creation-failure
- [x] See an `ACTIVE` status on cluster addon page
![image](https://user-images.githubusercontent.com/85196563/148625589-d15aba4d-1faf-4f17-8b4c-bc002d1a345a.png)
- [x] Consider testing an example persistent volume https://github.com/kubernetes-sigs/aws-ebs-csi-driver#examples
- [x] Merge and Tag eks-brokerpak PR
- [ ] Enable persistent volumes in solr-brokerpak

**Comment by nickumia-reisys** [comment]
It turns out that we need this because of https://github.com/apache/solr-operator/issues/365

**Comment by nickumia-reisys** [comment]
# Current Status:
- EBS has easy integration with EKS through the [EKS EBS addon](https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html)
- EBS only works with Manged nodes, not Fargate.
  - Attempt w/o managed nodes: https://github.com/GSA/datagov-brokerpak-eks/actions/runs/1746251184
  - Attempt w/ managed nodes: https://github.com/GSA/datagov-brokerpak-eks/actions/runs/1670062549
- EBS connects individually to each node and are not shared between nodes.
  - We can't used managed nodes for everything because that would defeat the purpose of being in Fargate.
- EFS is a shared filesystem across all nodes in a cluster.
- EFS does not have an addon, it must be installed via a [Helm Chart](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html#efs-install-driver)
- EFS does not support dynamic provisioning, only static provisioning in Fargate.
![image](https://user-images.githubusercontent.com/85196563/151020711-69b5ccbf-4a77-4de4-b9c5-972f28b7d57b.png)

- The [example ](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html#efs-create-filesystem)creates an EFS in the main cluster which means that the EFS would need to be provisioned in the EKS brokerpak.
- There are two options:
  1. Follow example, create static EFS in EKS brokerpak.
    - Design considerations:
      - Each eks cluster would have shared storage across all nodes, so if two Solrs are brokered in the staging space, their collection memory would overlap if they were named the same thing.
      - The total size of desired memory would need to be known prior to creating the EKS cluster.
  2. Fetch EKS config from the Solr brokerpak and do the provisioning alongside the creation of solr.
    - Design considerations:
      - I don't know if we can manipulate the EKS cluster from the Solr brokerpak.
      - I prefer this method.

# Resources needed alongside the EFS volume:
- Data sources:
  - VPC id (EKS-specific)
  - Cluster CIDR range (EKS-specific)
- Resources:
  - Security groups and additional rules (EKS-specific)
  - EFS driver (EKS-specific)
  - EFS volume 
  - Mount volume into nodes

**Comment by nickumia-reisys** [comment]
List of Related Resources:
- https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/810#issuecomment-804997331
- https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/104
- https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html
- https://aws.amazon.com/blogs/aws/new-aws-fargate-for-amazon-eks-now-supports-amazon-efs/
  > With this new update, for Fargate this step is not required and you do not need to install the EFS CSI driver, as it is installed in the Fargate stack and support for EFS is provided out of the box. Customers can use EFS with Fargate for EKS without spending the time and resources to install and update the CSI driver.
- [EFS Driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver)

**Comment by nickumia-reisys** [comment]
Tentative Final Design
- EFS Statically Provisioned alongside EKS Cluster
  - https://github.com/GSA/datagov-brokerpak-eks/pull/64
- Solr-operator-enabled PV for solrclouds
  - https://github.com/GSA/datagov-brokerpak-solr/pull/32
- Unique Solr Collection names
  - TODO

**Comment by mogul** [comment]
Another key reference: The [k8s documentation on persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/).
