### ISSUE TITLE
Tests ensure datagovtheme does proper sanitization of URL parameters

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3253]
## User Story

In order to ensure that no other XSS vulnerabilities exist within the ckanext-datagovtheme javascript, data.gov wants to add tests for proper handling of URL parameters.

## Acceptance Criteria
- [ ] WHEN I review the list of passing tests for this extension \
  THEN I see explicit tests for sanitization of parameters that accept URLs

## Background
This is to address any potential XSS in ckanext-datagovtheme https://github.com/GSA/datagov-deploy/issues/2998

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
This is proactive work to eliminate the potential recurrence of a class of error we've seen lead to a security vulnerability in the past.

## Sketch
* Add the tests!

**Comment by FuhuXia** [comment]
After the [H1 findings](https://github.com/GSA/datagov-deploy/issues/2998), it appears that Netscaler WAF has increased security policies. Request such as this `https://catalog.data.gov/dataset?q=<onerror=alert()>` will be blocked by the WAF.

**Comment by nickumia-reisys** [comment]
It should be noted that this is still a concern; but we closed it because we didn't see a good way of implementing and/or maintaining this feature.  I don't know the entire history of this issue; however, from my standpoint, there are too many routes that take in parameters that do not get filtered/sanitized from a central location.  So the first step would be to figure out how to properly sanitize all URL parameters.  We didn't know what exactly we were testing if we were to take this on.
