### ISSUE TITLE
Validating CKAN2.9 & Python3 framework with catalog

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3401]
## User Story

In order to increase confidence that we are ready to run in a Python 3 environment, the team wants to validate our applications with all their extensions under Py3.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN All relevant ckan extension is upgraded to CKAN 2.9 + PY3 \
  When The testing environment for catalog.data.gov supports CKAN 2.9 + PY3 \
  THEN the catalog.data.gov tests can run and pass \

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]
Since they're not all consistent, we want to make sure we're using all the right branches/versions of the various extensions in inventory and catalog, and ensure they're all at least minimally working correctly in an integrated deployment.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None.

## Sketch

Any necessary changes go on main (we have no expectation to backport to CKAN 2.8/Py2)
- [x] Use the cloud.gov-provided Python buildpack (which is Py3)
- [x] If we need an integration test to validate each extension is working correctly, we add it
- [x] The local test environment is updated to use the openknowledge foundation ckan-dev image

**Comment by jbrown-xentity** [comment]
I debated about trying to use the current bats tests vs moving to cypress tests. After adding cypress basic tests, they were definitely the way to go. Already found bugs in downstream extension templates that we will need to resolve, using API would not have found these bugs.

**Comment by jbrown-xentity** [comment]
Harvests are working in tests. Note that the harvest will complete with the correct number of harvested datasets, but the harvest source will show no datasets associated with the source. If a reindex is run (`ckan search-index rebuild`), then the datasets are associated appropriately. Not sure why at this time.

**Comment by jbrown-xentity** [comment]
See final PR here: https://github.com/GSA/catalog.data.gov/pull/328
This represents some major changes in catalog dev environment, including:

- OKFN base image (2.9 with Py3)
- Cypress testing over bats testing
- requirements management (pip instead of poetry)
- CKAN command usage
- Deprecate usage of the following extensions: report, archiver, and qa

**Comment by nickumia-reisys** [comment]
### Summary of Related Work

It was an honor to be a part of this Python 3 migration/upgrade effort because of how cross-platform, cross-disciplinary, open-source and integrated CKAN is in the overall data community.  This was a very large effort because of the various communities that rely on the software and the various software abstractions that exist from Python, Front-end Technologies (React, HTML/JS/CSS), web networking, Database Integrations, Search Integration, External services (harvesting methodologies, S3 integration, and more).  Even the main data.gov web apps are wrapped in a cloud.gov app that has further layers of abstraction.  The following list encompasses the highlights associated with Python 3 compatability,

- Main App Upgrades:
  - https://github.com/GSA/catalog.data.gov/pull/328
  - https://github.com/GSA/inventory-app/pull/359
- GSA-specific Extenstion Upgrades:
  - https://github.com/GSA/ckanext-datagovcatalog/pull/25
  - https://github.com/GSA/ckanext-datagovtheme/pull/88
  - https://github.com/GSA/ckanext-datajson/pull/100
  - https://github.com/GSA/ckanext-geodatagov/pull/190
  - https://github.com/GSA/ckanext-googleanalyticsbasic/pull/6
  - https://github.com/GSA/ckanext-dcat_usmetadata/pull/266
  - https://github.com/GSA/ckanext-usmetadata/pull/53
  - https://github.com/GSA/ckanext-envvars/pull/1
- Community Upgrades:
  - [Main CKAN](https://github.com/ckan/ckan/projects/3)
  - https://github.com/ckan/ckanext-dcat/pull/174
  - https://github.com/ckan/ckanext-harvest/pull/392
  - https://github.com/keitaroinc/ckanext-saml2auth/pull/23
  - https://github.com/ckan/ckanext-spatial/pull/249
  - https://github.com/asl2/PyZ3950/pull/5
  - https://github.com/ckan/ckanext-xloader/pull/113

Note: There were various bug fixes after these initial passes were complete.
