### ISSUE TITLE
Replace DCAT-US validator

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3503]
## User Story

In order to ensure the dashboard can be deprecated, data.gov admins want a validator of DCAT-US files built into catalog (ckanext-datajson extension).

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]
- [x] GIVEN an endpoint exists in catalog to validate DCAT-US files  \
  WHEN a URL to a file (or file) is provided with a DCAT-US format \
  THEN the user is provided with meaningful output of valid and invalid format 
- [x] #4001
    THEN my browser is redirected to the new validator location

## Background
Current dashboard validator exists [here](https://labs.data.gov/dashboard/validate).
An API route already exists (but is never used/tested) to validate pod files [here](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L419-L420).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
Need to ensure the SSRF protections currently in the dashboard are also in this implementation. 

## Sketch

Would involve investigating the following:
- Current implementation [doesn't seem to work](https://catalog.data.gov/pod/validate), should investigate why locally and check logs.
- What security is in place on the `/pod/validate` route?
  - Try converting some of [the existing SSRF tests](https://github.com/GSA/project-open-data-dashboard/blob/main/application/tests/helpers/api_helper_test.php) over 
- What options does the `/pod/validate` route provide?
- Can we create a basic, simple html page to hit the above api?
- Do we need to provide a "prettified" format of the code? Or would we need to implement the inverse (a JSON response), as [the code seems to return html](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L377)?
    - The previous implementation does have a JSON output option [which is used for tests](https://github.com/GSA/project-open-data-dashboard/blob/main/tests/validation.bats); not clear whether there's other clients of that functionality.

**Comment by nickumia-reisys** [comment]
### The route does work on a local version of CKAN

![image](https://user-images.githubusercontent.com/85196563/193896564-10373932-e096-4361-a683-038039fdf6db.png)

**Comment by nickumia-reisys** [comment]
So... the current state of this is that the route works in the `datajson` extension, but isn't getting recognized by the catalog main app.  We will eventually fix this.  However, the more pressing issue is that the main `do_validation` function is not checking the right schema.  

The general flow steps are:
- [[LINK](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L404-L405)] Hit the flask route at `/pod/validate` and get redirected to the `validator` function
- [[LINK](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L331-L333)] Parse the data.json link from the POST request.
- [[LINK](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L341-L352)] Download the file and make sure it is a valid `JSON`.
- [[LINK](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L354-L360)] Validate it is a proper `DATA.JSON`.
  - [[LINK](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajsonvalidator.py#L95-L404)] The function that does the "validation"

The problem is in the `do_validation` function.  It tries to make sure the data.json is a `list` (which is wrong).  It should be a `dict`.

@FuhuXia pointed me to the [`validate_schema`](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L37-L40) function.  But this function isn't actually doing the validation of the schema.  It is just doing the validation that the schema is valid name of a schema.

The closest thing that is doing the validation is the [`_validata_dataset`](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L335) function which is part of the [`DatasetHarvesterBase`](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/datajson.py#L43) class.  However, I don't know if we want to use the Harvester class to do data.json validation.

----

@FuhuXia @jbrown-xentity
- [x] Do we need the old `do_validation` function if it is validating the wrong things?
- [x] Can you please help me find the right function that should be doing the data.json validation?

**Comment by jbrown-xentity** [comment]
You're probably right, the validation is embedded in the harvester class.
We do not need the old `do_validation` if it is wrong.
I would consider pulling out the validation from the harvester in some way, and having the harvester code and the validate code reference the same function. If that is difficult because of the way the validation has to be implemented for the harvester, maybe there is a way to "break out" the validation into small chunks that can be shared in some way.
For the record, this "feature" of ckanext-datajson is poorly documented and not sure how well it ever worked (certainly not since ckan2.8), so it's entirely possible that most of the current logic will need to be thrown out...

**Comment by jbrown-xentity** [comment]
What I didn't say is: the validation that occurs in the harvester logic does seem to be solid, and has worked fine in the past. So the logic there should be able to be kept.

**Comment by nickumia-reisys** [comment]
Got it!  That all makes sense to me.  I like the idea of throwing out a bunch of stuff.  My tentative plan:
- [ ] Throw out the old `do_validation` code
- [ ] Strip out the validation code from the harvester (and add unit tests)
- [ ] Integrate with Inventory and make sure the `export data.json` function still works

🚧

**Comment by nickumia-reisys** [comment]
Just for the record ➡️ I removed the `do_validation` function and all references to it and the tests are still passing which means that we were never testing it (no surprise, but still just saying haha..) 

- https://github.com/GSA/ckanext-datajson/pull/122/commits/4b69c66cf35a04fafcb5e5dce186ddf4d7dd2360
![image](https://user-images.githubusercontent.com/85196563/194107301-d7058806-1c90-4651-8bdd-a199932735b8.png)

**Comment by nickumia-reisys** [comment]
Scratch that... the current logic is very very .... very complicated.   Turns out the do_validation function was doing the right thing, just at the `dataset` level and not the `catalog` level.

![image](https://user-images.githubusercontent.com/85196563/194131178-05000c9c-1ca8-422a-9b60-49b2065a4003.png)

**Comment by nickumia-reisys** [comment]
I'm going to start documenting and cleaning up things.

**Comment by nickumia-reisys** [comment]
Okay.  I didn't do much documentation (...yet).  But here's the updates:
- The `/pod/validate` route works
- The original validation function "works".  It validates the datasets, but it doesn't validate the head matter.
- Unit tests have been written for good and bad cases.

TODO...
- [x] Testing on catalog develop
- [x] @jbrown-xentity @FuhuXia Do we want to validate the top head matter?  The stuff below ⬇️ 
```json
  "@type": "dcat:Catalog",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
```

**Comment by nickumia-reisys** [comment]
Also, do want want to change the route? @jbrown-xentity @FuhuXia @hkdctol  @Jin-Sun-tts @btylerburton @jbrown-xentity 

As it stands right now, the public route (not available yet) would be https://catalog.data.gov/pod/validate... do we want to make it something more meaningful?  
- https://catalog.data.gov/datajson/validator
- https://catalog.data.gov/datajson/validate
- https://catalog.data.gov/datajsonvalidator

**Comment by nickumia-reisys** [comment]
### Deployed to `develop`

![image](https://user-images.githubusercontent.com/85196563/194168809-81b24464-deba-4775-9082-5c97c36f7371.png)

**Comment by nickumia-reisys** [comment]
### GSA data.json seemed to process extremely fast.

It's only 336 datasets; but still.  Will test a larger data.json to see if there are memory issues or anything like that.

![image](https://user-images.githubusercontent.com/85196563/194168911-c342df34-7f3b-4cde-99f2-f3a1fd430bf1.png)

**Comment by nickumia-reisys** [comment]
### Answering the questions in the ticket:
> - Current implementation [doesn't seem to work](https://catalog.data.gov/pod/validate), should investigate why locally and check logs.

Per previous comments, the current implementation does work.  The [`datajson` plugin](https://github.com/GSA/catalog.data.gov/blob/ad0d97a8b9ad48c0af3a5409075db3208a0c39ae/ckan/setup/ckan.ini#L134) just wasn't being loaded into production (along with small bugs in the `ckanext-datajson` extension).

> - What security is in place on the `/pod/validate` route?
>   - Try converting some of [the existing SSRF tests](https://github.com/GSA/project-open-data-dashboard/blob/main/application/tests/helpers/api_helper_test.php) over 

Most of the old tests are useless now because they were testing that `curl` wouldn't go do something stupid.  The `datajson` implementation uses the [built-in `urllib`](https://docs.python.org/3/library/urllib.html) python library which isn't as susceptible to the same things.  Tests have been added as necessary.

> - What options does the `/pod/validate` route provide?

The [GET] route displays an empty form page (with some helper text) asking for url input.  The [POST] route takes only one input (i.e. 'url') and does the work to validate it.

> - Can we create a basic, simple html page to hit the above api?

The page already exists and it is not an api route.

> - Do we need to provide a "prettified" format of the code? Or would we need to implement the inverse (a JSON response), as [the code seems to return html](https://github.com/GSA/ckanext-datajson/blob/main/ckanext/datajson/blueprint.py#L377)?
>      - The previous implementation does have a JSON output option [which is used for tests](https://github.com/GSA/project-open-data-dashboard/blob/main/tests/validation.bats); not clear whether there's other clients of that functionality.

There is no JSON output for the results.  If we want to output that, that would be a new feature of `datajson`.

**Comment by jbrown-xentity** [comment]
> Also, do want want to change the route? @jbrown-xentity @FuhuXia @hkdctol @Jin-Sun-tts @btylerburton @jbrown-xentity
> 
> As it stands right now, the public route (not available yet) would be https://catalog.data.gov/pod/validate... do we want to make it something more meaningful?
> 
> * https://catalog.data.gov/datajson/validator
> * https://catalog.data.gov/datajson/validate
> * https://catalog.data.gov/datajsonvalidator

I would use `/dcat-us/validator`. I don't like the branding has become datajson, I hate that. It's like a naming convention merged with a file type, not a standard...

**Comment by nickumia-reisys** [comment]
TODO:
- [x] Deprecate old `do_validation` function AND Replace all references with the new jsonschema pod validation stuff
- [x] Change route from `pod/validator` to `dcat-us/validator`
- [ ] ~Change route from `data.json` to `dcat-us/data.json`~
- [x] Move validation route to new plugin, `datajson_validator`, in `datajson` extension

**Comment by nickumia-reisys** [comment]
# Form is live at: https://catalog.data.gov/dcat-us/validator

![image](https://user-images.githubusercontent.com/85196563/194625098-23366d4e-5c85-4fb1-86f8-210d0133c3de.png)

**Comment by jbrown-xentity** [comment]
Note that it failed to handle https://data.doi.gov/data.json. The dashboard was inconsistent on whether it could handle it or not, it contains around 30K records and file size is around 80M. So consider anything above that to be untestable at this point, unless we really scale up.

**Comment by nickumia-reisys** [comment]
### Increasing RAM to `1200M` allows the above `data.json` to be processed. 
![image](https://user-images.githubusercontent.com/85196563/194721494-b174d35f-46d2-4bbc-89d2-b7d8fde35945.png)

**Comment by jbrown-xentity** [comment]
We will make follow up tickets to match the functionality of dashboard, and decide how important/useful those features are... Looks great!
