### ISSUE TITLE
Solr 8 instance credentials are not bound on cloud.gov

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#3523]
Environment: cloud.gov
Solr Version: 8.6

During our release of Solr on cloud.gov, when an instance of Solr was provisioned and keys were bound, the keys could not be authenticated to get past the login page.

From preliminary research, valid credentials do work.  The default user account credentials successfully authenticate past the login page.  However, the credentials generated from the brokerpak do not exist in the solr security.json and therefore, do not work.  It is an issue of the credentials not binding properly.

## How to reproduce

1. Create an instance of solr with the following commands:
```
cf create-service solr-cloud base [instance-name] -b [broker-name] -c '{"solrImageTag":"8.6"}'
cf create-service-key [instance-name] key
cf service-key [instance-name] key
```
2. Use the outputted credentials to login at the URL.

## Expected behavior

Credentials accepted.  Login successful.

## Actual behavior

Credentials rejected. Login unsuccessful.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
- Useful commands:
```
# Extract kubeconfig from cloud.gov
# Save the config to a file and use that file to run kubectl
cf t -s management; cf env ssb-solr | grep -i kubeconfig
KUBECONFIG=kubeconfig kuebctl get all -n default

# Analyze the secrets to find good user pairs
KUBECONFIG=kubeconfig kubectl get secrets
KUBECONFIG=kubeconfig kubectl get secret [***-solrcloud-basic-auth] -o jsonpath='{.data.password}'  | base64 -d
```
Important resources:
- [Solr Cloud CRD](https://github.com/apache/solr-operator/blob/main/docs/solr-cloud/solr-cloud-crd.md#authentication-and-authorization)

**Comment by mogul** [comment]
So what happens on 6.6.6? There's just no auth, or it works, or...?

**Comment by nickumia-reisys** [comment]
There's a separate issue for 6.6.6.  There's no authentication on 6.6.6 https://github.com/GSA/datagov-deploy/issues/3524

I figured that (1) credentials not working and (2) authentication not enabled were two different bugs..

**Comment by jbrown-xentity** [comment]
CKAN is kind of ready for SOLR 8. Some links:
[CKAN dev tests](https://app.circleci.com/pipelines/github/ckan/ckan?branch=dev-v2.9&filter=all)
[CKAN dev changes](https://github.com/ckan/ckan/compare/ckan-2.9.4...dev-v2.9)
[CKAN SOLR 8 support changes](https://github.com/ckan/ckan/pull/6530)
[CKAN release docs](http://docs.ckan.org/en/latest/contributing/release-process.html)

**Comment by mogul** [comment]
Next steps:

# Reproduce the problem

- [x] Merge this PR, https://github.com/GSA/datagov-brokerpak-eks/pull/62
- [x] Tag a release of the EKS brokerpak (v2.0.0)
- [x] datagov-ssb app-setup-eks.sh should refer to that new v2.0.0 locally
- [x] Manually re-deploy datagov-ssb in the development space, so that we can create an EKS cluster with solr-operator 0.5.0 (solr-debugging-eks)
  - Don't commit/push this change yet!
- [x] Refactor the KinD-specific code out of the environment setup for datagov-brokerpak-solr
- [x] `cf t -s development; cf create-service aws-eks-service raw solr-debugging-eks -b ssb-eks-gsa-datagov-development --wait` 
- [x] `cf create-service-key solr-debugging-eks key`
- [x] `export SOLR_DOMAIN_NAME=$(cf service-key solr-debugging-eks key | tail +2  | jq -r .credentials.domain_name)`
- [x] `cf service-key solr-debugging-eks key | tail +2 | jq -r .credentials.kubeconfig > .kubeconfig`
- [x] export KUBECONFIG=.kubeconfig
- [x] `make .env`
- [x] cd terraform/provision and confirm we can `terraform apply` there successfully
  - I got stuck here... `terraform plan` works, but when I `terraform apply` I get 
  ```bash
  Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: solrclouds.solr.apache.org "solr-50d858e0985ecc7f" is forbidden: User "system:serviceaccount:default:default" cannot get resource "solrclouds" in API group "solr.apache.org" in the namespace "default"
  ```
  This is an indicator that terraform is somehow not properly using the service account we intend, which has a different name:
  ```
  $ kubectl get serviceaccounts
  NAME               SECRETS   AGE
  4b98adc09f1acea7   1         122m
  default            1         155m
  ```
- [x] Confirm we can `make demo-up` in the Solr brokerpak repo
- [x] Try running make test in the solr brokerpak repo... 
  - We expect it to fail because the credentials don't work
  - This will be our reproduction of the bug observed in https://github.com/gsa/datagov-deploy/issues/3523
- [x] (probably stop here; document for Nick)

# Deploy a fix

- [x] Fix the bug!
- [ ] ~Port [the fix that sets `nginx.ingress.kubernetes.io/proxy-body-size` on our  old bespoke Helm chart](https://github.com/GSA/datagov-brokerpak-solr/tree/bugfix/nginx-request-size) to [a new `ingressOptions.annotations` value](https://artifacthub.io/packages/helm/apache-solr/solr#custom-kubernetes-options) value we can set for the Apache-provided Solr helm chart.~
- [ ] ~Make a new tagged release of the Solr brokerpak, v1.0.3~
- [ ] ~Refer to that new tagged release in datagov-ssb~
- [ ] ~NOW push an SSB PR with both the EKS and Solr brokerpak upgrades~
- [ ] ~Merge that PR~
- [ ] ~Test that provisioned creds for a brokered solr in staging now work~

**Comment by mogul** [comment]
Future @nickumia-reisys see the checkboxes above for how far I got... You should be able to retrace my steps on the branch `fix-solr8-suth-with-eks` with these commands:
- `cd datagov-brokerpak-solr`
- `git fetch`
- `get checkout fix-solr8-suth-with-eks`
- `cf t -s development`
- `export SOLR_DOMAIN_NAME=$(cf service-key solr-debugging-eks key | tail +2  | jq -r .credentials.domain_name)`
- `cf service-key solr-debugging-eks key | tail +2 | jq -r .credentials.kubeconfig > .kubeconfig`
- `export KUBECONFIG=.kubeconfig`
- `make .env`
- `cd terraform/provision`
- (run the docker command to get in the Terraform container)
- `terraform init`
- `terraform apply`

**Comment by nickumia-reisys** [comment]
# Local Solr Instance Testing
A test case of Solr Basic Authentication has been created in a [local docker environment gist](https://gist.github.com/nickumia-reisys/18544d2c6aad4160293bda1fec6ead7f).

# Local Interaction with a remote Solr Instance
As part of debugging, we wanted to make sure that `/solr/admin/authentication` API was working identically in both Solr `standalone` and `solrcloud` modes.  It was discovered that the AWS Load Balancer that forwards traffic to the internal NGINX controller redirected requests based on `Status Code 301` which always converts `post` requests to `get` requests.  Since the API route relies on sending the payload in a `post` format, the API was never receiving the user data to create accounts for.  Here's an example of someone having a [similar problem](https://ubiq.co/tech-blog/how-to-redirect-location-to-another-domain-in-nginx/).  This was verified by disabling the "HTTPS upgrade" functionality of the Load Balancer and directly passing data to the internal network.

If we ever want to activate the Solr API for external clients, we would need to have the Load Balancer perform a `307` redirect [preserving post data](https://stackoverflow.com/questions/13628831/apache-301-redirect-and-preserving-post-data).

Side Note: This may be able to be achieved by updating [EKS brokerpak](https://github.com/GSA/datagov-brokerpak-eks/blob/main/terraform/provision/ingress.tf#L168).  However, there's no concrete evidence that [AWS Load Balancer](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/tasks/ssl_redirect/) supports anything other than `301` and `302`

# Fixing bug in Solr EKS environment

The original method was trying to use a `curl` pod deployed in the same EKS cluster as `solrcloud` to activate the API call and update user credentials.  It was determined that the curl pod was not reliably able to talk to the `solrcloud` pods and make the API request.  As a result the API call was shifted to the `solrcloud` master pod which had no issues running the API call.

Research was done into using a different module to [perform API calls through terraform](https://stackoverflow.com/questions/51197781/terraform-rest-api-calls-with-curl); however, there were no good trusted providers 😞 

Note: I think older versions of Solr Image did not have curl installed.. but since we will be on minimum 8 from now on, this does not concern us.


![ezgif com-gif-maker](https://user-images.githubusercontent.com/85196563/147315989-b751b6f6-ce23-490f-a2fa-8eb3cbf149bd.gif)


From the production standpoint, there should not be any reason that the API call will fail with the new implementation.  The issue is that the testing `KiND` environment does things a bit differently from a real `EKS` cluster and the local tests are failing because terraform can't talk to the KiND cluster.  The issue has to be with the `generate-env.sh` variables.

# Next Steps

- [x] Fix local KiND configuration to get tests to pass, https://github.com/GSA/datagov-brokerpak-solr/runs/4623804807?check_suite_focus=true#step:7:36
- [x] Port the fix that sets nginx.ingress.kubernetes.io/proxy-body-size on our old bespoke Helm chart to a new ingressOptions.annotations value value we can set for the Apache-provided Solr helm chart.  Use the same PR
- [x] Merge that PR, https://github.com/GSA/datagov-brokerpak-solr/pull/29
- [x] Make a new tagged release of the Solr brokerpak, v1.0.3
    - Go to commit to tag, run `git tag v1.0.3` and then `git push v1.0.3`
    - If a mistake is made during tagging, delete tag with `git tag -d v1.0.3`
- [x] Refer to that new tagged release in datagov-ssb
- [x] NOW push an SSB PR with both the EKS and Solr brokerpak upgrades
- [x] Merge that PR, https://github.com/GSA/datagov-ssb/pull/112
- [x] Test that provisioned creds for a brokered solr in staging now work

**Comment by nickumia-reisys** [comment]
Thanks to this [documentation ](https://www.ibm.com/docs/en/cloud-paks/cp-management/2.0.0?topic=kubectl-using-service-account-tokens-connect-api-server#kube)for getting the correct token. 👍

**Comment by nickumia-reisys** [comment]
I verified.. unfortunately this fix does not work with Solr 6 😞

**Comment by mogul** [comment]
That's okay, the only way out is through (Solr 8).

**Comment by mogul** [comment]
Confirmed working in staging, screenshot below.
![image](https://user-images.githubusercontent.com/47762/148326675-c5ae0a63-fb39-4f87-b3fd-97f2dae2dcfa.png)

The provided credentials worked when entered in the form at the specified URL.

**Comment by mogul** [comment]
(Note that the Solr image you use must have `curl` available. It's definitely in 8.11.1.)
