### ISSUE TITLE
[Task] Re-sync bad data causing harvest failure

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3546]
Related to https://github.com/GSA/datagov-deploy/issues/3532 discovery...

Some recent changes on harvesting process left datasets from data.json harvest source a bad state in SOLR. Each dataset in SOLR contains two `harvest_object_id` entries. Harvest process has later been fixed, but the bad SOLR state leads to some ValidationError error in the gather stage, as described in #3532, and prevents harvest job to finish successfully. 

## Sketch
- [x] ~~Search in recent gather logs for string `ckan.logic.ValidationError: {'extras_validation': [u'Duplicate key "harvest_object_id"']}`. Find the harvest_job_id related to the error then further find the harvest_source_id~~
- [x] ~~Use SQL query or API to find all ACTIVE dataset ids for all harvest_source, and put them in a text file~~
- [x] ~~Run ckan command `search-index rebuild [dataset-id]` for each entries in the dataset id text file to re-index the dataset.~~

## New Sketch
- [x] Develop a script to loop Solr records and pick out all dataset id with duplicate `harvest_object_id`,  save as text file.
- [x] Run ckan command `search-index rebuild [dataset-id]` for each entries in the dataset id text file to re-index the dataset.

**Comment by FuhuXia** [comment]
The error only arise to surface when a problematic dataset is being deleted. So even we capture all problematic datasets or harvest sources from the harvest log, it wont be a complete list. 

Also tried to find datasets that was updated/added during the bug was introduced, between [Oct 5](https://github.com/GSA/catalog.data.gov/pull/354/files) and [Oct 12](https://github.com/GSA/catalog.data.gov/pull/357/files), it turns out some datasets was touched before that timeframe?

The ultimate way capture all problematic datasets is loop thru all solr records. A python script was developed for this purpose.  https://gist.github.com/FuhuXia/fd82852421c81f42b36ce135a7d3cdb3.

**Comment by FuhuXia** [comment]
22k problematic datasets were found. running search-index command now.

sync script:
https://gist.github.com/FuhuXia/a329c726709d5c7c387ad670c3b34e2e

Estimated 18 hours to finish.

**Comment by FuhuXia** [comment]
It took 18 hours for the sync script to finish the 22k records.  500+ records saw some error, probably due to network glitch. Run the python script again to capture the 500+ record, then run the sync script again. All finished. Now there is 0 dataset with duplicate `harvest_object_id`.
