### ISSUE TITLE
Launch data.gov on Federalist

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3547]
## User Story

In order to migrate data.gov to Federalist as a static site, data.gov wants to update the DNS records to point to Federalist.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN I browse to https://data.gov \
  THEN I see the Federalist site
- [x] WHEN I browse to https://www.data.gov \
  THEN I see the Federalist site
- [x] WHEN I `dig www.data.gov` \
  THEN I see CNAME records that point Federalist/cloud.gov

## Background

This story represents the cut-over launch ticket for the www.data.gov static site.

[Federalist docs for custom domains](https://federalist.18f.gov/documentation/custom-domains/#adding-an-apex-domain). Note that apex domains don't allow for CNAMEs and require special configuration.

Past stories on [how we moved other static sites](https://github.com/gsa/datagov-deploy/issues/641).

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
DNS records should be configured as described in the SSP, using the appropriate DNS system.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
https://federalist.18f.gov/documentation/before-you-launch/

- [x] Notify Federalist team of intent to launch in #federalist-support and initiate the scan
- [x] Resolve any issues in the scan
- [x] Add _acme-challenge CNAME records to DNS
- [x] Federalist team notifies us when the TLS certificate has been created
- [x] Open a DNS ticket to update the CNAME record www.data.gov to www.data.gov.external-domains-production.cloud.gov.

**Comment by adborden** [comment]
Forgot to follow up on the ALIAS thread with GSA DNS. They **do not** support ALIAS records. Instead, the web team can setup a server to redirect to www.data.gov and data.gov would be an A record to this redirect server.

This is not a blocker for Federalist, but would be a blocker for getting out of FCS. Right now data.gov points to Netscaler, ~which redirects to www.data.gov already~ and our wordpress nginx server redirects to www.data.gov. So if we launched today, FCS _wordpress_ would be handling the redirect. To get out of FCS, we'd need to move the redirect somewhere new (like what the DNS team is offering).

Long term, it's probably worth us moving to route53, which drops the dependency on an external team for DNS and then we have ALIAS record support.

**Comment by adborden** [comment]
From [Federalist](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1638811519003900?thread_ts=1638567420.022200&cid=C1NUUGTT5):
> Just ran a static code scan and no major issues, but a couple of smaller things for external links of which there are A LOT of examples:
> 1. http urls instead of https. These may be accurate since not everything is https, but you may want to review these and use https where possible. (see /app/themes/roots-nextdatagov/assets/LeafletMap2/data/us_cities_counties.js)
> 1. missing rel="noopener noreferrer" attributes.
> Ex.
> ```
> <a href="http://leafsnap.com/dataset/#specieslist" target="_blank" class="external ext-link" rel="external" onclick="this.target=&#039;_blank&#039;;">Species List</a>
> ```

**Comment by adborden** [comment]
We addressed the issues from Federalist and requested another scan.

In case we want to run SonarQube locally, you can follow the hints here https://gsa-tts.slack.com/archives/C1NUUGTT5/p1638811519003900?thread_ts=1638567420.022200&cid=C1NUUGTT5

**Comment by adborden** [comment]
Currently waiting on another scan.

**Comment by mogul** [comment]
Still [waiting on ISSM activity](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1640110841003000?thread_ts=1638567420.022200&cid=C1NUUGTT5).

**Comment by mogul** [comment]
Next steps: Probably need to add SRI hashes for CDN-hosted stuff.

**Comment by mogul** [comment]
Here's [a page about adding SRI hashes](https://www.srihash.org/) to our script tags. Basically we just need to generate hashes for each thing we're pulling off of a CDN, then search and replace script tags pointing to that src, being careful to also add the `crossorigin="anonymous"` attribute.

I'm moving this back to the `Sprint Backlog` since this is actionable now, and assigning Robbie since he's likely the one doing it!

**Comment by mogul** [comment]
PR for hashes is in, now just one CORS issue with DAP to address.

**Comment by robert-bryson** [comment]
Commit removing  `?agency=GSA&amp;subagency=TTS` reverted. 


I spoke with Tim Lowden, we basically have two options for the current issue:
- Use the remote DAP host, add an `Access-Control-Allow-Origin` header for it, and update the SRI hash each time there is an update. 
- Use a local copy and update it each time there is an update from DAP.

It seems like using a local version is preferable in our case since if DAP updates the script then data will not be lost. If using the remote, it will fail immediately (due to the now outdated SRI hash) and data will be lost. 

In either case, we will need a developer to update our code any time there is an update. To keep informed of updates we can watch the [DAP repo](https://github.com/digital-analytics-program/gov-wide-code) and subscribe to the DAP listserv on listserv@listserv.gsa.gov by sending it a `subscribe DAP` email.

**Comment by robert-bryson** [comment]
https://github.com/GSA/datagov-website/pull/21 done last night. The CORS issue went away with the last commit removing SRI from the DAP script. 

The site appears to be in a good state (build on [main branch](https://federalist-a1176d2b-cb31-49a0-ba20-a47542ee2ec5.app.cloud.gov/site/gsa/datagov-website/)) and ready to go.

**Comment by jbrown-xentity** [comment]
Our next steps to get this out are as follows:
- [ ] Request that federalist site be "published" (URL doesn't really matter) following [federalist launch guidance](https://federalist.18f.gov/documentation/before-you-launch/)
- [x] Setup a new cloudfront distribution to verify that the cutover will work (dla9wanc1vft1.cloudfront.net)
- [ ] Update datagov-website to use proxy instead of redirect
- [ ] FINAL STEP: update cloudront production to point to proxy server

**Comment by robert-bryson** [comment]
The `*.app.cloud.gov` cert rejects nested subdomains that we need (ie `food.www-redirects-dav-datagov.app.cloud.gov`). We would need to either get cloud.gov to create a wildcard cert for us or to bite the bullet and transition the URLs fully to cloud.gov (with downtime).

**Comment by robert-bryson** [comment]
Currently subdomain redirects are being handled by Aaron's nginx redirect app in prod. We have concerns that pushing a new target domain to production might break those as we can't test without breaking the existing redirections.

**Comment by robert-bryson** [comment]
We also need to schedule a discussion between ourselves, GSA DNS, and cloud.gov to plan for the transition in a way that minimizes downtime.

**Comment by hkdctol** [comment]
@robert-bryson should I try to find someone from GSA DNS team?

**Comment by robert-bryson** [comment]
@hkdctol Yes, if you have a contact, that would be great!

**Comment by robert-bryson** [comment]
[Federalist support launch request thread](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1643214953004800), made this morning but no response yet. Will follow up. 

[Federalist launch checklist docs](https://federalist.18f.gov/documentation/before-you-launch/).

**Comment by robert-bryson** [comment]
Thanks to @jbrown-xentity prodding, request [has been submitted](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1643295355006500).

**Comment by jbrown-xentity** [comment]
Since we are off GSA DNS and onto 18f DNS, this is unblocked. For federalist to be able to provision the domain, we need to remove the Cloudfront middle-man and point our DNS directly to FCS. Then we can remove the Cloudfront record and allow Federalist to provision; and then finally we will update our DNS to point to Federalist instead of FCS.

**Comment by mogul** [comment]
Reopening until we have FCS deprovision the relevant infrastructure in their environment, which we missed in our sketch.
