### ISSUE TITLE
Migrate inventory to cloud.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#3554]
## User Story

In order to stop maintaining the FCS deployment, the data.gov team wants production service to be directed to our deployment on cloud.gov.

## Acceptance Criteria
[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] WHEN we visit inventory.data.gov in our browser \
  THEN we see the expected inventory output \
  AND we see requests in the inventory app's logs on cloud.gov

## Background
[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]
This change will migrate us away from our old environment, which is harder to maintain and for which there are more things that we have to look after. The new environment has already been pen-tested and ATOd so we think it's going to be net win on attack surface overall.

### Pre-launch

In the days leading up to the launch, these tasks should be completed:

- [x] Review application configuration and all values are correct
- [x] Ensure [CAA record](https://github.com/GSA/datagov-deploy/issues/2690) for letsencrypt.org exists for domain
- [x] Familiarize yourself with the [external domain service](https://cloud.gov/docs/services/external-domain-service/)
- [x] Open a DNS ticket for GSA to add _acme-challenge records for DNS validation (RITM0904225)
- [x] Create domain `cf create-private-domain gsa-datagov inventory.data.gov`
- [x] Map the domain route to the application in the prod space `cf map-route inventory inventory.data.gov`
- [x] Create the [external domain service](https://cloud.gov/docs/services/external-domain-service/) in the production space: `cf create-service external-domain domain-with-cdn inventory-cdn -c '{"domains": "inventory.data.gov"}'`
- [x] Confirm the [production-ready checklist](https://cloud.gov/docs/deployment/production-ready/) is complete
  - [x] Application has a manifest.yml and is deployed from CI
  - [x] Production application is running with at least 2 instances
  - [x] Datastores are running "dedicated" or production grade plans
  - [x] cf ssh access is disabled in the production space
  - [x] NR Synthetics alerts are configured for this domain and reporting to #datagov-alerts
- [x] Schedule/announce an outage window with Inventory users
- [x] Script datastore migrations them for repeatability
- [x] Rehearse the launch and rollback plans below in staging, document any commands verbatim
- [x] [Open a ticket with GSA DNS](https://github.com/GSA/datagov-deploy/wiki/DNS) to reduce TTL for domains to 300 immediately and coordinate the DNS switch over and update the DNS `inventory.data.gov CNAME inventory.data.gov.external-domains-production.cloud.gov`
- [x] Validate [login.gov configuration](https://developers.login.gov/production/#production-configuration) is ready for production

### Launch

Tasks to be completed at the time of launch.

- [x] Check the application route is setup `curl -v --resolve inventory.data.gov:443:$ip_address 'https://inventory.data.gov'` should route to the app where `$ip_address` is an IP for `inventory.data.gov.external-domains-production.cloud.gov`
- [x] Stop the web services in FCS to prevent database writes
- [x] Migrate datastores using <script>
- [x] Reindex solr
- [x] Have GSA update the DNS `inventory.data.gov CNAME inventory.data.gov.external-domains-production.cloud.gov`

In the event a rollback is necessary, apply these tasks.

- [ ] Revert DNS changes, should point to original values in FCS
- [ ] Ensure application services are started and running in FCS

### Post-launch

Once the launch is stable and successful, these tasks should be performed.

- [x] Fix login issue (or utilize sandbox login)
- [x] Create issues for decommissioning the FCS environment
- ~[ ] cf ssh access is disabled in the production space~
  - Choosing to leave it enabled until we've finished migrating catalog.data.gov over.
- ~[ ] Consider adding an external domain-with-cdn service for staging environment and create an issue~
  - Choosing not to do this now; we can always do it in future.
- [x] Remove Synthetics check for inventory-prod-datagov.app.cloud.gov
- [x] Submit pull request or create issue to remove inventory code from datagov-deploy (bare minimum, remove from [jenkins](https://github.com/GSA/datagov-deploy/blob/master/ansible/inventories/mgmt/group_vars/all/vars.yml#L107-L118))

**Comment by jbrown-xentity** [comment]
For migrate s3, investigate inventory-next vs inventory but plan on inventory-next, see [gist for details](https://gist.github.com/adborden/1267704283f095c156ca4d504ad666ea)

**Comment by FuhuXia** [comment]
[Scripts](https://github.com/GSA/cf-backup-manager/pull/19/files) created to migrate Inventory databases from FCS to cloud.gov

Steps to replicate:

1. Run `01-fcs-inventory-db-migration.sh` script on `root@inventory-1p` instance to create backup from FCS (needs to run on FCS production server). This instance has `/root/.env` and `/root/.pgpass` ready.
1. Run `02-fcs-inventory-db-migration.sh` script locally to start restore **ckan** database on cloud.gov, choose `50` as storage size.
1. Run `03-fcs-inventory-db-migration-datastore.sh` script locally to start restore **datastore** database on cloud.gov, choose `150` as storage size.
1. Run cf task on s3-migrator as described in [run-task s3-migrator README](https://github.com/GSA/datagov-s3-migrate#readme).
```
$ cf run-task s3-migrator --command "python migrate.py --prefix datagov/inventory-next/ --src-service-name fcs-lifeboat --dest-service-name inventory-s3" --name inventory-s3-task -k 2G -m 1G
```
[update]: should try `aws s3 sync` since now we have same credentials for both src and dest S3 buckets. It is faster.

**Comment by FuhuXia** [comment]
Some conversation left in [slack](https://gsa-tts.slack.com/archives/C2N85536E/p1639184179028600), here is the gist of it.

Step 1 taking db dump took 1 min for ckan db, 30 mins for datastore db.
A SQL query added into migration script `02-fcs-inventory-db-migration.sh` to clean up user table, otherwise some user sees login error due to unsupported chars( eg. @) in name field.
A fix is pushed to https://github.com/GSA/ckanext-usmetadata/pull/58. When this is deployed to inventory, we wont see 500 error on the resource page.
CKAN DB restore took 5-10 mins. Datastore restore finished over night, not sure about the exact time but it is more than 5.5 hour.
Solr reindex also left run overnight and finished next morning. best estimate is 1 -2 hours.

**Comment by mogul** [comment]
After many travails, inventory.data.gov was migrated today!

**Comment by mogul** [comment]
(@nickumia-reisys will make a PR to turn restarts back on.)
