### ISSUE TITLE
Dashboard Validator error on large file upload

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3591]
Error when uploading a large data.json file to the Validate tool on Dashboard.
```
Could not upload file (it may be larger than PHP or application allows)
```
![image](https://user-images.githubusercontent.com/1392461/145610300-d95a5f2d-d857-4b69-a641-b18be5798f7b.png)

## How to reproduce

https://dashboard.data.gov/validate
Upload a json file of greater than 7 MB size, eg DOC or NASA

## Expected behavior

Shows Validation Results

## Actual behavior

Error complaining file 

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by mogul** [comment]
This is happening because the default PHP `upload_max_filesize` default is 2MB or 8MB depending on the kind of post. It can be updated by specifying a new value in php.ini [using the mechanism provided by the buildpack](https://docs.cloudfoundry.org/buildpacks/php/gsg-php-config.html#engine-configurations).
