### ISSUE TITLE
Inventory user screen has two Add a Dataset buttons

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3613]
After logging into inventory.data.gov, at the agency screen, there are two buttons for Add a Dataset. Both go to the metadata entry form.

## How to reproduce

1. Log in to inventory.data.gov with Editor/Admin account, go to any organization

## Expected behavior

List of datasets for the agency, with one Add a Dataset button that leads to metadata entry form.

## Actual behavior

Two buttons for Add a Dataset that both go to the correct metadata entry form.

## Sketch
- [ ] Find cause for duplicate buttons
- [ ] Eliminate duplicate Add a Dataset button![Screen Shot 2021-12-22 at 3.22.05 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/46a937e0-778f-439b-9970-03c995ec3ecf)

**Comment by nickumia-reisys** [comment]
@FuhuXia @jbrown-xentity Which button link is more accurate?

`https://inventory.data.gov/dataset/new-metadata?group=<some-group>`
or
`https://inventory.data.gov/dataset/new-metadata`

I suspect this is also a result of customizations in `ckanext-usmetadata` that did not age well.  I can easily remove the bad one, just not sure which one is bad.

**Comment by jbrown-xentity** [comment]
Keep the one with the group; it autopopulates the organization field (which is kind of nice). However, if you can remove a template from our customization/management, then do that and don't worry about which one to take!

**Comment by nickumia-reisys** [comment]
Fix is (finally) live haha...
![image](https://user-images.githubusercontent.com/85196563/167214691-8bf4feed-83c5-4ef3-a312-03935fb65581.png)

**Comment by nickumia-reisys** [comment]
Summary of work:
- https://github.com/GSA/ckanext-dcat_usmetadata/pull/285
  - `webassets.yml` was fixed (bug from PY2 to PY3 transition)
  - A test that there is only one `add dataset` button was created
  - PY2 tests were removed as a requirement for merge (since we don't have any PY2 systems using this extension anymore)
  - PY2 code still exists in the repo and will need to be cleaned up eventually
- https://github.com/GSA/ckanext-dcat_usmetadata/pull/287
  - PY3 upgrades (specifically the need for `webassets.yml`) weren't captured in the initial definition of the PyPI release
- https://github.com/GSA/inventory-app/pull/441
  - Changes were pulled into inventory.data.gov main app.
