### ISSUE TITLE
Agency logos not properly displaying on inventory

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#3615]
When logged into inventory, some agencies, though not all, do not display proper size of logos

## How to reproduce

1. Sign on to inventory.data.gov, and go to Organizations
2. See organizations where logos are not displaying properly

## Expected behavior

Organizations shown with properly sized logos

## Actual behavior

Improper logo size for certain organizations, both in overall Organizations page and when you go to that organization

## Sketch

- [ ] Go through organizations page and identify all logos that are not displaying properly
- [ ] Look at URL source for organization logos
- [ ] Once cause is identified, implement solution for proper size logos, working with agency POCs if necessary
![Screen Shot 2021-12-22 at 3.30.55 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/c2ceba67-3278-40bf-9968-006a005a7de1)![Screen Shot 2021-12-22 at 3.31.06 PM.png](https://images.zenhubusercontent.com/5d374a506df6e4059e63379d/a37ca2be-72b0-439b-80a6-be16f28c9b03)

**Comment by nickumia-reisys** [comment]
This bug has been fixed by 
- https://github.com/GSA/inventory-app/pull/434

![image](https://user-images.githubusercontent.com/85196563/164518566-754d1924-1db5-4b0b-b233-5454ca93ae13.png)

![image](https://user-images.githubusercontent.com/85196563/164518611-855487a2-cead-4377-9137-95ec06e8c0cc.png)
