### ISSUE TITLE
Catalog shows wrong facet list

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3630]
## How to reproduce

1. Go to https://catalog-stage-datagov.app.cloud.gov/dataset
1. Check the facet list on the left

## Expected behavior

Showing facet list including Topic, Topic Categories, Dataset Type ...

## Actual behavior

Showing CKAN default facet list Organizations, Groups, Tags...

## Sketch
First, should check if able to replicate locally (maybe add cypress test).
If not, check differences and/or cloud.gov logs.
If so, debug locally and fix (with test).

**Comment by nickumia-reisys** [comment]
This is spread across datagovtheme and geodatagov,
- https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/plugin/__init__.py#L22-L73
- https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/plugins/__init__.py#L326-L346
- https://github.com/GSA/ckanext-geodatagov/blob/main/ckanext/geodatagov/plugins/__init__.py#L631-L671

But I didn't dig into it further that that.

**Comment by FuhuXia** [comment]
Facet on dataset page is addressed by above commit.

Facet on organization page is due to a known [CKAN core bug](https://github.com/ckan/ckan/issues/6636) that is currently being worked on. Will re-evaluate after the [ongoing PR](https://github.com/ckan/ckan/pull/6682) is merged and may bring the change in earlier than next stable release.
