### ISSUE TITLE
Enable 307 redirects for EKS load-balancer (using NLBs instead of ALBs)

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#3677]
## User Story

In order to separate L4 from L7 concerns (which fixes issues with 307 redirection not being supported by ALBs), the data.gov team wants provisioned EKS instances to use an NLB for incoming traffic.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN a brokered Solr instance \
  WHEN I make a POST to a /solr endpoint \
  AND the POST is redirected \
  THEN the redirect returns code 307 \
  AND the follow-up request uses POST, not GET

## Background

We are seeing this problem when we run the [`migrate-solrcloud-schema.sh` script in the catalog repository](https://github.com/GSA/catalog.data.gov/blob/main/ckan/setup/migrate-solrcloud-schema.sh). The configset is not uploaded properly and we see that files are missing during the subsequent attempt to create the Solr collection.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
We expect no change in the overall architecture as a result of this work. SSL will continue to be terminated by AWS, just using an NLB instead of an ALB.

## Sketch

- [x] Upgrade to the newest version of the AWS LB Controller
- [x] Provision an NLB using a LoadBalancer service (instead of an ALB using an Ingress)
- [x] Ensure all the attributes we've been setting for our implicit ALB are also set on our implicit NLB.

**Comment by nickumia-reisys** [comment]
This issue was delayed because the update could not be deployed to the SSB cleanly.  Multiple fixes were attempted (memory considerations, eks dual-provisioning race conditions, terraform provider version constaints).  The actual problem was a documentation update that used the subdomain name as the name for the Load Balancer.  The name of an AWS Load Balancer is limited to 32 characters and the SSB was using a 64 character domain name.

To mitigate potential future errors caused by the naming limit, we updated the EKS Brokerpak tests to use a [64 character name](https://github.com/GSA/datagov-brokerpak-eks/blob/main/.github/workflows/test.yml#L50-L53).  This further highlighted naming issues which were then resolved.  See this PR for further details,
- https://github.com/GSA/datagov-brokerpak-eks/pull/76

There is an additional issue that delayed this deployment which dealt with dependency issues during creation and deletion.  Creation should be reliable again; however, destruction is still held back by https://github.com/GSA/datagov-deploy/issues/3617.  See this PR for further details,
- https://github.com/GSA/datagov-brokerpak-eks/pull/77

After these updates are complete.  There is an additional issue of simultaneously supporting Solr 6 and Solr 8 since both of them rely on different versions of the EKS Brokerpak.  This issue was discovered when [trying to deploy](https://github.com/GSA/datagov-ssb/pull/120) the updated EKS Brokerpak to the SSB.  Will update after sprint planning with resolution.

**Comment by mogul** [comment]
This issue is blocked until we finish work on the direct Terraform deployment, which will address the immediate issue.
