### ISSUE TITLE
Inventory: The 'mediaType' field is missing

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3788]
After a dataset was created, it generates an error when exporting the data.json.
```
[('Missing Required Fields', ["The 'mediaType' field is missing. (1 locations)"])]
````
## How to reproduce

Create a dataset, add a resource as such:

- Resource: Link to a file
- URL: https://www.google.com
- Name: Some Resource
- Media Type: HTML -- Web Page

Save the dataset, then go to organization page to export the data.json

## Expected behavior

A data.json file is generated successfully, containing the new dataset.

## Actual behavior

An error.txt with above error message.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia-reisys** [comment]
There seems to have been a bug in the `ckanext-dcat_usmetadata` extension where the front-end deleted a relevant field that the datajson validator needed to do it's validation.  While we have not done a complete test of all cases.  We walked through all of the scenarios theoretically and decided that leaving the field in did not cause any scenarios to break and it did solve the errors documented in this issue.

Relevant Pipeline:
- https://github.com/GSA/ckanext-dcat_usmetadata/pull/284
- https://github.com/GSA/inventory-app/pull/433

Proof that the bug has been resolved in local testing (GIF was too big to attach 😞),
[unredacted(16).zip](https://github.com/GSA/data.gov/files/8531407/unredacted.16.zip)

**Comment by nickumia-reisys** [comment]
This was fixed for the end-user.  However, there needs to be a follow up discussion about the status of the "mediaType" field.  It seems the field is not required from the dcat_usmetadata UI Form for some Resource types.  However, `datajsonvalidator` thinks that it is required, @jbrown-xentity and @hkdctol 

@FuhuXia and I didn't have a clear understanding of the data requirements.

**Comment by jbrown-xentity** [comment]
This is the data requirements: https://resources.data.gov/resources/dcat-us/#distribution-mediaType
Short version, is it required: `Yes, if the file is available for public download.`
The only practical reason for tracking stuff in inventory is for public catalog record of public data, so it seems mostly appropriate to require it in inventory. There are use cases where the dataset record could be public but the data itself is considered private, that's why the confusion on whether it's required or not. I'm fine to either require it in the form, or make the validation less stringent.

**Comment by jbrown-xentity** [comment]
@jbrown-xentity make new ticket for QA on all required fields in inventory metadata form, and if export works as expected after bare minimum data entry.
