### ISSUE TITLE
Catalog sitemap contains private datasets

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#3879]
Catalog has a [sitemap.xml](https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap.xml) defined in the robots.txt to facilitate search engine to crawl the site. When[ 50% of the datasets are private](https://github.com/GSA/data.gov/issues/3593#issuecomment-1175136246), search engine will see 50% of the links in sitemap as 404. 

## How to reproduce

check some links in https://filestore.data.gov/gsa/catalog-next/sitemap/sitemap-1.xml
for example, [this one](https://catalog.data.gov/dataset/usgs-topo-map-vector-data-vector-14726-ewell-maryland-20201007-for-7-5-x-7-5-minute-shapefile).

## Expected behavior

Valid dataset page

## Actual behavior

404 for anonymous user.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by FuhuXia** [comment]
This is still an issue with latest sitemaps. 
`sitemap count = package count(collection *) + harvest count + private count`

we need to either exclude private count in sitemaps, or make all private dataset public, all simply delete all private ones, next harvesting should bring them back.

**Comment by FuhuXia** [comment]
There are 6350 private datasets to be fixed. All active. Attached below:
[private-dataset.txt](https://github.com/GSA/data.gov/files/9892140/private-dataset.txt)

**Comment by nickumia-reisys** [comment]
I remember all of the private datasets being deleted,
- https://github.com/GSA/data.gov/issues/3593

I remember that our sitemap generation (and hosting) has changed,
- https://github.com/GSA/data.gov/issues/3648

The sitemaps are being updated every night, so the sitemap link referenced in this ticket are obsolete.  This was apparently completed since it made it to "done" and then archived.  But if anyone has additional thoughts.  Please share 😄  (because I don't remember the logistics or implementation details.)
