### ISSUE TITLE
Provide data.gov future solutions

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4115]
## User Story

In order to plan the best path forward for the data.gov technical program, data.gov admins want possible paths forward and a scoring system such that we can quantitatively and qualitatively evaluate where we should invest our technical resources.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN the features list, government requirements, and pain points are all detailed \
  WHEN a team review/discussion occurs \
  THEN a well informed recommendation/vote occurs \
  AND a future path is decided upon

## Background

We need to know if we are going to invest heavily in our current CKAN environment, or consider other solutions.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None for this ticket, follow ups will have others...

## Sketch

Provide detailed description of what the 4 paths forward look like:
- Current CKAN solution
- CKAN with external custom harvester
- CKAN alternative (Amundsen) with custom external harvester
- Custom system

Also provide a way to score (with notes) both the amount of work and the amount of expected maintainence by feature on these systems. Also score against pain points, and security documentation changes.

**Comment by nickumia-reisys** [comment]
### A random tangent...

From the point mentioned earlier today about ATO compliance with design changes, I am completely turned off from this effort.  The one constant in all of my experience in cybersecurity is that fact that no project/program has been able to effectively coordinate the technical and non-technical aspects of cybersecurity management and requirements.  I love doing cyber work; but when there's no clear guidance or understanding of what cyber means for a specific application, it makes it truly painful.

With our current system and applications, there is already enough confusion over what our cyber responsibilities are in relation to cloud.gov, login.gov, GSA and other parties.  Our cyber policies and procedures are not well-suited to our mission and open data application.  By this, I mean that we have good general cyber policies and procedures, but because they are general, we always have to re-create the context for cyber with every new problem that we encounter.  We don't have a well-formed stance over how we want to secure open data.  I'm not proposing that we have a complete model, but we should have better definitions for data boundaries and tolerances.  For example, we have our system infrastructure and our data infrastructure.  Our SSPP handles the system aspect, but not our data aspect as much.  It tries to cover it by inheritance since our data lives inside of our system, but the data lifecycle is separate from the system lifecycle.  Our apps restart every 15 mins.  That does not effect our data management in the slightest.  If there's a duplicate in our database, our system policies/procedures don't document how we should handle that.

It would put my heart at ease if we added the cybersecurity impact to this analysis.  However, I know two things:
- It would take too long to create the foundation from which cyber can be categorized and applied to this, and
- When the time comes to decide a path forward, we won't have the resources to fully compensate the cyber side of things.

The best I can do is offer some thoughts about cyber along the way...

**Comment by jbrown-xentity** [comment]
An initial document has been created, and is ready for review. Scheduled for discussion on Wed, 1/11 at 1:30 ET...
https://docs.google.com/document/d/1dUPmE74-nLx4bKOtKpVxoEkADaWPQWb-ufhuAgYuRyk/edit#heading=h.b8ovkfnx4gxa
