### ISSUE TITLE
Caching Solution for Reports

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4116]
## User Story

In order to make the display of CKAN reports performant, the datadotgov-team would like to cache the results.

## Acceptance Criteria

- [x] GIVEN a user visits a report page, \
  THEN datagovteam would like the display of that report to be performant \
  AND not timeout

## Background

Caching of the reports has been enabled at the Cloudfront level, but Cloudfront will only set the TTL at each edge location, so a user hitting `/report/metrics-dashboard` from a new edge location will miss the Cloudfront cache. 

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

Caching at the CKAN level is not realistic due to our restarting of the application every 15minutes. Same applies to an NGINX solution in catalog-proxy.

## Sketch

- One proposed solution would be to build an extension that incorporates the report plugin and augments it to use persistent storage

**Comment by jbrown-xentity** [comment]
We're looking at caching this at the nginx level, and pinging the URL regularly such that the page is *almost* always cached, with the possibility of people hitting in the in-between time. That's an acceptable turn around for this product.
https://www.nginx.com/resources/wiki/modules/redis/

**Comment by jbrown-xentity** [comment]
We would use https://docs.cloudfoundry.org/buildpacks/nginx/index.html, the "Loading Dynamic Modules" section...

**Comment by jbrown-xentity** [comment]
Looks like we setup caching default behavior to be 1 hour, we can either bump this for the whole site to 1 day, or consider customizing for these reports: https://github.com/GSA/catalog.data.gov/blob/main/ckan/setup/ckan.ini#L48-L50

**Comment by nickumia-reisys** [comment]
More references for how to cache using nginx (not sure if it's still relevant):
- https://stackoverflow.com/questions/4556063/using-nginx-to-serve-content-directly-out-of-a-redis-cache
- https://github.com/openresty/redis2-nginx-module

**Comment by hkdctol** [comment]
Since Reports is on the main navigation of the new site, it could get a decent number of clicks. If this ticket is still in progress, can we go forward with the main site at end of week?

**Comment by robert-bryson** [comment]
At the moment, ther is an issue `module "/proxy/ngx_http_redis2_module.so" version 1021003 instead of 1023003 in /proxy/nginx.conf:6`. I can verify that the module [is being compiled by `v1.23.3`](https://github.com/GSA/catalog.data.gov/blob/feature/nginx-modules/vendor-nginx-modules.sh#L26)

![Image](https://user-images.githubusercontent.com/91547795/224176541-4fcd4338-1d0b-4bc2-916a-e0b2ec85a4bf.png)

and the test is running `v1.23.3` [here](https://github.com/GSA/catalog.data.gov/blob/1ee70f26474a2fdf986aaa3ebc6bd8772fe19494/Makefile#L59) (by adding an `nginx -v`), but somehow `21` is sneaking in somewhere.

**Comment by nickumia-reisys** [comment]
An attempt to outline the steps involving redis for this use-case:
- [x] Compile nginx with redis module
- [x] Deploy to cloud.gov
- [ ] Connect `catalog-proxy` to `catalog-redis`
- [ ] Come up with redis commands to get/set cache for specific uri
- [ ] Test and iterate until it works...

**Comment by nickumia-reisys** [comment]
@robert-bryson Any reason we chose `ngx_http_redis2_module` over `ngx_http_redis_module`? Is the non-2 version deprecated?  It seems like the non-2 version is more of what we want..

**Comment by robert-bryson** [comment]
@nickumia-reisys https://github.com/GSA/data.gov/issues/4116#issuecomment-1437100974

**Comment by nickumia-reisys** [comment]
Having done a little more investigating on this issue, it is more complex than originally designed.  It turns out that the nginx redis module's primary goal is to look up preexisting keys in redis.  As such, there are a few routes that we could from here.  To highlight the components that need to exist for this to work:

- Cache Creation
  - Getting the cache of `/report/<blah blah blah>` into redis does not need to be done by NGINX.
  - We could use NGINX to query the route and then cache the results.
  - However, if we wanted to be more deliberate about it.  We could use another program to cache the report in redis (a ckan extension.. or a standalong python app on cloud.gov)
    - I think doing it in NGINX is more complicated and requires more management from us, but if we want to accept that management, then it is okay.
- Cache Management
  - By default, keys that are created in Redis can "live forever" or be associated a "expire" time.  If we use the "expire" time, Redis dedicates additional resources to make sure the key is deleted after it expires.
  - If we wanted to write the custom python app on cloud.gov to manage this "update", we would have finer control over making sure the cache never expires before it has updated information.  We could also just never delete the key and just update the value.
  - Doing this in NGINX, again, would be more complex.
- Cache Retrieval/Serving
  - This part is the normal use case of the NGINX redis module and is just about getting the key from Redis and serving it to end users.
  - If the key does not exist for whatever reason, we can have a "fallback" of just passing through to the actual ckan server.

I think the implementation of this depends on how we want to do the creation and management of the cache.  I guess another part of this is how to scales to multiple reports and how to manage the cache for different routes with parameter arguments.  Our main concern is not timing out for the end user, so if we want to design with that in mind, I would suggest a separate app to create and manage the cache.

P.S. Not to mention the additional nginx modules we would need to attach to get all of the configuration and management to work from NGINX.

References:
- Lots of random internet words
- https://redis.io/commands/expire/
- https://github.com/openresty/srcache-nginx-module/issues/60
- https://github.com/Yongke/ngx_http_redis-0.3.7

**Comment by hkdctol** [comment]
Archiving for now. Work to complete will be in a different or new ticket.

**Comment by nickumia-reisys** [comment]
Semi-final thoughts on this ticket.. Building a python redis application is a decent amount of work, see [real-python tutorial](https://realpython.com/python-redis/).  We technically never proved that nginx could talk to redis on cloud.gov.  It is possible based on other examples, we just never got the connection working with our nginx instance thus far.

Either way, the team has decided that this be superseded by
- https://github.com/GSA/data.gov/issues/4254

**Comment by nickumia-reisys** [comment]
@GSA/data-gov-team Any reason we didn't close this ticket?

**Comment by btylerburton** [comment]
Not sure. Seems like an oversight, or that we wanted to keep the parent ticket open while we evaluated whether the fix in #4254 worked. I think it's fine to close it now.
