### ISSUE TITLE
Disappearing and Reappearing metadata source

### ISSUE THREAD

**Issue by robert-bryson** [GSA/data.gov#4177]
@chris-macdermaid found that [a couple](https://catalog.data.gov/dataset/noaa-next-generation-radar-nexrad-products2) [records](https://catalog.data.gov/dataset/noaa-coastal-mapping-shoreline-products2) that do not have metadata sources. 

Upon revisiting, the issue seems to have resolved itself. At this time, this ticket does not need any action and is intended as a record of this occurring if it rears up in the future.

## How to reproduce

1. Visit the example records
2. See that there is no metadata source listed

## Expected behavior

There is a metadata source: 

![image](https://user-images.githubusercontent.com/91547795/214703729-51508bdf-b4fc-4c9e-8145-ac29a8c1c850.png)

## Actual behavior

No metadata source found

## Sketch

Perhaps associated with a harvest error somewhere along the chain.

**Comment by chris-macdermaid** [comment]
This record is missing its metadata source as of 1/31/2023 5:43 PM MT
https://catalog.data.gov/dataset/series-information-for-state-and-equivalent-entities-national-tiger-line-shapefiles-current

![image](https://user-images.githubusercontent.com/64213093/215915600-52cf29b2-079a-4944-ab05-68ea189e7f8f.png)

Both package_show and package_search have a harvest_source_id

[package_search.txt](https://github.com/GSA/data.gov/files/10552132/package_search.txt)
[package_show.txt](https://github.com/GSA/data.gov/files/10552134/package_show.txt)

Requesting the harvest source object by id returns a 404
![image](https://user-images.githubusercontent.com/64213093/215917242-8ede3814-0908-4834-8374-e089dd54d397.png)

![image](https://user-images.githubusercontent.com/64213093/215916920-f946bc58-d8e2-46d0-8205-506bfb0cc909.png)

**Comment by robert-bryson** [comment]
Similar story to last time. it is back as of now: 
![image](https://user-images.githubusercontent.com/91547795/216139122-787fd475-a5e0-4f77-bf5b-f0b123d2d1ad.png)

**Comment by chris-macdermaid** [comment]
@robert-br If this helps, the harvest_source_id  changed. The record shows the last update as 1/14. Was this record missing the harvest source from 1/14 until it was fixed over night?

broken
https://catalog.data.gov/harvest/object/02d50b34-1cc0-456c-9791-b503aacfa729
now
https://catalog.data.gov/harvest/object/a10de20f-0dd7-401f-87ed-5dcb8283fb0d

**Comment by FuhuXia** [comment]
We are seeing another case of this. Harvest info is missing from the UI for [one dataset](https://catalog.data.gov/dataset/omerniks-level-iii-ecoregions-of-the-conterminous-united-states), then next day it is fixed on its own, without any manual fix, reharvesting or db-solr-sync.

**Comment by FuhuXia** [comment]
Ok, now I have a better understanding of the issue. The issue is caused by Solr containing the wrong harvest_object_id for the dataset. A re-index will fix it. If you find dataset, simply load the dataset page will trigger a reindex by the nightly tracking-update job that is why the dataset always appears to resolve the issue on its own the next day.

We need to figure our why solr contains the wrong harvest_object_id. Or at least we can collect a list of datasets of this kind and run re-indexing on them.

**Comment by jbrown-xentity** [comment]
The only way I can think of to examine the scope of the problem (get a list of datasets of this kind) is to hit the API, and try to hit `/harvest/object/{id}` with the dataset->extras[]->harvest_object_id value from the API. If you get a 404, then this is one of those datasets. Doing this might also give us insight into where, ie if all the datasets that we find are DCAT-US, or all ISO, or a mixture, how many were recently harvested, etc.

**Comment by FuhuXia** [comment]
We are using [db_solr_sync](https://github.com/GSA/ckanext-geodatagov/blob/13eb58680dec6984f240d4575503cb45a2afde31/ckanext/geodatagov/cli.py#L338) to nightly sync db and solr, in which we are comparing a tuple `(dataset_id, last_modified_date)` between db and solr to determine whether a dataset need a reindex. We can add `harvest_object_id` into it, making the tuple `(dataset_id, harvest_object_id, last_modified_date)`  for db and solr comparison. Not a fix on the root cause but a tool to let us understand the scope of the issue and fix on the surface before root fix.

**Comment by FuhuXia** [comment]
There are two challenges to sync `harvest_object_id`. 
1. There can be multiple `HarvestObject` for a package. So we have to come up with a sql query to pick the last one according the some timestamp. To make things worse, upstream ckanext-harvest was using the wrong one ([upstream PR](https://github.com/ckan/ckanext-harvest/pull/519) submitted and merged).
2. `harvest_object_id` is not returned in the solr result. It is inside a `validated_data_dict` json object. Extra steps to get the value, making the script run longer and risk OOM.

**Comment by FuhuXia** [comment]
The steps to [add harvest_object_id](https://github.com/GSA/ckanext-geodatagov/commit/88c1d59d4666cdab0581adb3e02a58ef3ac18a27#diff-e5710e239e81444e7dd15fc58323de11e4517a3456f6da7537b2ecc2294d9096R305-R314) into returned solr results is too much for the app's memory to handle. Scaled to 10G memory but the process still got killed with OOM.

**Comment by FuhuXia** [comment]
At this point we have a few other options to move forward:
1. Modify harvest behaviour so that `harvest_object_id` is indexed on the top level instead of embeding into `validated_data_dict`. This way it is easy to retrieve to avoid OOM. or, 
2. Do a weekly site-wide solr reindex on weekly basis. Based on the current solr speed and package volume, this will take 12-15 hours to finish, not bad for a weekly job.

**Comment by FuhuXia** [comment]
...
3. pagination is the solution to the OOM. Thanks for @nickumia-reisys 's pairing.

**Comment by FuhuXia** [comment]
The issue is alleviated by our revamped nightly db-solr-sync job, which finds the difference for any package's `harvest_object_id` between solr and db and synchronize them. The initial run found 77K packages. After a few runs, those difference are minimal. All NOAA datasets should be good now.

**Comment by FuhuXia** [comment]
After initial cleanup and only a minimal amount of packages remain problematic, yesterday after harvesting 6k+ packages is back to be problematic, as show in the [action log](https://github.com/GSA/catalog.data.gov/actions/runs/4259229968/jobs/7411244398#step:5:90). 

Doing some manual sync and harvesting to replicate....

**Comment by FuhuXia** [comment]
Things seems to be fine if we can avoid running the script when there are harvest activities.

**Comment by chris-macdermaid** [comment]
Found another record without a harvest source
https://catalog.data.gov/dataset/marine-trackline-geophysical-database

![image](https://user-images.githubusercontent.com/64213093/222806534-0db66d26-11d2-4897-8090-934eeedbc43d.png)

**Comment by FuhuXia** [comment]
Did a count there is 31670 packages out of sync. Will keep an eye on this harvest source.
```
2023-03-03T19:36:24.92+0000 [APP/TASK/ckan-auto-4326652923-1/0] 
OUT 2023-03-03 19:36:24,928 INFO  [ckanext.geodatagov] total 369319 solr indexed_package
OUT 2023-03-03 19:36:25,402 INFO  [ckanext.geodatagov] 46 packages need to be removed from Solr
OUT 2023-03-03 19:36:25,402 INFO  [ckanext.geodatagov] 31670 packages need to be updated/added to Solr
```
