### ISSUE TITLE
Remove decommissioned data.gov records from 18f DNS

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4233]
This inventory list should be kept up to date for any subdomain changes.
- [ ] [Touchpoints](https://touchpoints.app.cloud.gov/admin/websites/)

## data.gov subdomains to be removed:
Please click any records that you are sure can be safely removed.

- [ ] `manage.data.gov` A record to an internal ip
- [ ] `origins-smallbusiness.data.gov` A record to unknown ip `198.10.125.51`

The following are CNAME records still pointing to BSP resources.
- [x] `aapi.data.gov`
- [x] `admin-catalog.data.gov`
- [x] `admin-catalog-bsp.data.gov`
- [x] `admin-catalog-next.data.gov`
- [x] `ag.data.gov`
- [x] `agriculture.data.gov`
- [x] `catalog-bsp.data.gov`
- [x] `catalog-next.data.gov`
- [x] `ci.data.gov`
- [x] `cities.data.gov`
- [x] `counties.data.gov`
- [x] `dashboard-bsp.data.gov`
- [x] `dashboard-labs.data.gov`
- [x] `ed.data.gov`
- [x] `education.data.gov`
- [x] `ethics.data.gov`
- [ ] `federation.data.gov`
- [x] `federation-staging.data.gov`
- [x] `filestore.data.gov`
- [x] `foodsecurity.data.gov`
- [x] `geospatial.data.gov`
- [x] `health.data.gov`
- [x] `labs-bsp.data.gov`
- [x] `notice.data.gov`
- [x] `nutrition.data.gov`
- [x] `reference.data.gov`
- [x] `rural.data.gov`
- [x] `sbx.data.gov`
- [x] `search.data.gov`
- [x] `semantic.data.gov`
- [x] `services.data.gov`
- [x] `sites-next.data.gov`
- [x] `states.data.gov`
- [x] `static-bsp.data.gov`
- [x] `wp-bsp.data.gov`

**Comment by robert-bryson** [comment]
Updated list above for removals/couple of missing records. See PR [here](https://github.com/18F/dns/pull/628). As per [Fuhu's edits](https://github.com/18F/dns/pull/622), I just copied over the terraform file to my fork. His work is still captured. I can't create another fork if I already have one, apparently.

**Comment by robert-bryson** [comment]
Moving to blocked, waiting on 18f PR and Touchpoints account reactivated.

**Comment by robert-bryson** [comment]
Just [got merged](https://github.com/18F/dns/pull/628)!

**Comment by FuhuXia** [comment]
federation.data.gov reported down. We should not delete it.

**Comment by robert-bryson** [comment]
Need to be a site point of contact to be able to clean up the list on Touchpoints. I reached out to Ryan Wold to get myself added.

**Comment by robert-bryson** [comment]
@hkdctol, Ryan Wold set me as the Point of Contact for those sites so I am able to manage them myself. I'm communicating with him as per what I should be setting them to and also what the Point of Contact should be long term.

**Comment by robert-bryson** [comment]
I have gone through the list on Touchpoints and there are a number of differences between the list above and Touchpoints. A number of subdomains are not on the list in what would be the sketch for this story. Below are subdomains that are missing.

Subdomains on touchpoints that are not in `18f/dns` terraform (have `DNS_PROBE_FINISHED_NXDOMAIN` error):

- alpha
- businessusa
- consumer
- disaster
- disasters
- ecosystems
- finance
- globaldevelopment
- humanrights
- jobkit
- law
- make
- manufacturing
- next
- research
- safety
- science
- skills
- smallbusiness
- smartdisclosure
- vocab
- weather

Subdomains on touchpoints that are in `18f/dns` terraform (`404`s on data.gov side):

- climate - redirect fails. Note `_acme-challenge.climate` also exists.
- developer - redirect functions, but `/developers/` not found, also `_acme-challenge.developer` exists.
- food - redirect functions, but `/food/` not found, also `_acme-challenge.food` exists.
- highlights - redirect functions, but `/highlights/` not found, also `_acme-challenge.highlights` exists.
- labs - redirect functions, but `/labs/` not found, also `_acme-challenge.labs` exists.
- ocean - redirect functions, but `/ocean/` not found, also `_acme-challenge.ocean` exists.

It is not clear to me either the origin of the list provided in the ticket or why these differences exist. I believe we can remove the former list from Touchpoints with the web ui and the latter with that and a PR to 18f/dns as well. Please let me know if otherwise, @FuhuXia & @hkdctol. If that sounds good, I will make the PR/decommission/archive them. 

Lastly, I decommissioned the records listed in the ticket. I also clicked the archive button (as recommended by Ryan Wold), but I don't think they are indeed archived; the UI returns a message saying 'Authorization is Required' and the button is labelled 'For Registry Managers'.

**Comment by robert-bryson** [comment]
@hkdctol to find the details on Touchpoints go [here](https://touchpoints.app.cloud.gov/admin/websites) (and filter for data.gov to make it a bit more readable). 

When I say in `18f/dns` terraform, I am referring to [this file](https://github.com/18F/dns/blob/main/terraform/data.gov.tf) that is the actual definition of resources in code.

**Comment by hkdctol** [comment]
On climate, we did retain those old posts, could it redirect to https://data.gov/climate/1/? All the rest in that list of 6--I don't think we need.

**Comment by robert-bryson** [comment]
Ok, I will change that redirect and remove the rest. I assume that I'm free to go ahead and decommission/archive the first list?

**Comment by hkdctol** [comment]
let me ask ryan what that means

**Comment by hkdctol** [comment]
@robert-bryson we can proceed--thanks

**Comment by FuhuXia** [comment]
> On climate, we did retain those old posts, could it redirect to https://data.gov/climate/1/? All the rest in that list of 6--I don't think we need.

This is done already in the code [here](https://github.com/GSA/datagov-website/blob/main/redirects/nginx.conf#L26-L30).
I just ran cf command `cf map-route www-redirects climate.data.gov` and now it is live.

**Comment by robert-bryson** [comment]
Looks like this [PR was just approved](https://github.com/18F/dns/pull/631#pullrequestreview-1446475847) (and hopefully merged soon!). Once in, this ticket can be closed.

**Comment by robert-bryson** [comment]
`18f/dns` PR merged! 

Would be closed, but @FuhuXia caught that I missed cleaning up the redirects for these. See [that PR here](https://github.com/GSA/datagov-website/pull/46).
