### ISSUE TITLE
Python Buildpack 1.8.5+ Breaks Our Python Deployments

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4259]
Python Buildpack@1.8.5+

## How to reproduce

1. Specify a buildpack version > 1.8.4
2. Try deploying catalog/inventory to cloud.gov

## Expected behavior

Deployment successful

## Actual behavior

Buildpack failed compilation?

## Sketch

Suspect:
- [Don't fall back to unvendored installs when vendored install fails](https://github.com/cloudfoundry/python-buildpack/blob/master/CHANGELOG#L59-L70) ([cloudfoundry/python-buildpack#638](https://github.com/cloudfoundry/python-buildpack/pull/638))

**Comment by jbrown-xentity** [comment]
Question: we've always tried to vendor in order to speed up the catalog deployments. **If it's causing problems, maybe we just avoid vendoring and utilize the normal build process (since apparently we were rolling back to that anyways)**? Odds are, we got things "working" at some point and assumed that vendor was doing the proper things, but over time it's seemed that we were just getting things passed through by this "anti-feature" that is now biting us.

**Comment by robert-bryson** [comment]
Inventory will be pinned to `v1.8.4` with [this PR](https://github.com/GSA/inventory-app/pull/569/files#diff-24c51d6f58480f0d1e1b3f4068768cbdea5c9896edb96ca0165f8122224217a8R8). Catalog is also pinned to `v1.8.4` as of [this PR](https://github.com/GSA/catalog.data.gov/pull/937). Once this ticket is complete, please unpin both.
