### ISSUE TITLE
`sitemap-0.xml` not loading

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4442]
## How to reproduce

1. Visit https://catalog.data.gov/sitemap/sitemap-0.xml

## Expected behavior

![image](https://github.com/GSA/data.gov/assets/85196563/acd41e61-da77-4d62-851b-04d8621b79d7)

## Actual behavior

![image](https://github.com/GSA/data.gov/assets/85196563/1ea0a6ab-640b-478a-aaee-16b67860d4bb)

## Sketch

Investigate the indexing number of the sitemap code.  Maybe one of the loops starts at 1 and the other loop starts at 0?

**Comment by nickumia-reisys** [comment]
### Google couldn't fetch it either:
![image](https://github.com/GSA/data.gov/assets/85196563/13027fe7-4b58-4d60-9eb7-1c29bd5845cf)

**Comment by btylerburton** [comment]
all sitemaps are 404'ing now

**Comment by btylerburton** [comment]
EDIT: The fix below was for other sitemaps beyond `sitemap-0.xml`

>>>>>>>>>>>>>>>>>>>>>>

Sitemaps are fixed by reverting the location change...

This is best understood as 

`location = /foo {}` exact match for `/foo`
vs
`location /foo {}` is a general match for something which includes path `/foo` and will be superceded by a block with greater specificity, or will be chosen if there's no other specificity 

Background: https://www.digitalocean.com/community/tutorials/nginx-location-directive#3-nginx-location-block-for-a-directory

**Comment by FuhuXia** [comment]
It starts with `sitemap-1.xml`. There is never a `sitemap-0.xml`.
```
File sitemap.xml upload complete to: https://.../sitemap.xml
Sitemap index upload complete to: https://.../sitemap.xml
1 to 10000 of 380944 records done.
done with sitemap/sitemap-1.xml.
...
```

**Comment by FuhuXia** [comment]
`/sitemap/sitemap-0.xml` is receiving bot traffic.
