### ISSUE TITLE
Outline Harvester 2.0 Orchestrator Decision

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4472]
## User Story

For the sake of posterity and transparency, it is important to document design decisions. This ticket will outline the options and decisions that eventually arrived at using Airflow for the Harvester 2.0 Orchestrator.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN technical decisions have been made
  THEN they should be documented for clarity and posterity

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [x] Add decision docs for Airflow to datagov-harvester repo

**Comment by nickumia** [comment]
Good analysis on design paths!  I'd be curious to see how the end result turns out.  The best result would be increased performance and reliability... It feels like the scope might be an increase in reliability.  I'm not as confident in the increase in performance.  And specifically, it does not feel like state management is solid enough to prevent duplicates.  I think a little bit of effort should be put towards better state management (e.g. what is the unified data model that can be hashed to ensure uniqueness).

How state management relates to orchestration...  The things the orchestrator is managing perform data manipulation operations that effect the state of data and the state of the system.  Ensuring what state transitions can occur, what transitions cannot occur and how to recover from bad states will let the orchestrator know what services are needed when.
