### ISSUE TITLE
 HTML5 cross-origin resource sharing (CORS)

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#45]
CORS policy controls whether and how content running on other domains can perform two-way interaction with the domain that published the policy. The application implements a CORS policy from any domain.

## Verifed
- [x] https://data.gov/wp-json/
- [x] https://data.gov/wp-json/oembed/1.0/
- [x] https://data.gov/wp-json/oembed/1.0/oembed

## Remediation
- [ ] Restrict CORS policy to domain

**Comment by dano-reisys** [comment]
I am not entirely sure what the problem is here. The response header seems to have the right X-Frame-Options: `X-Frame-Options:SAMEORIGIN`

Not sure what these three urls are supposed to reveal...
`https://data.gov/wp-json/
https://data.gov/wp-json/oembed/1.0/
https://data.gov/wp-json/oembed/1.0/oembed`

I can disable the rest-api capability as well if needed.

**Comment by kvuppala** [comment]
@dano-reisys 
I think the issue is more for BSP dev environment, we dont have the below header on BSP WP Dev, which needs to be added

X-Frame-Options:SAMEORIGIN

**Comment by dano-reisys** [comment]
added X-Frame-Options:SAMEORIGIN header to the nginx config + disabled wordpress rest api

**Comment by kvuppala** [comment]
@FuhuXia @dano-reisys 
I think we also need the similar configuration on all the other BSP applications (catalog, inventory, dashboard and CRM)

**Comment by FuhuXia** [comment]
Added SAMEORIGIN policy to apache ckan.conf for catalog and inventory.
