### ISSUE TITLE
ckanext-spatial is not load ckan.ini config

### ISSUE THREAD

**Issue by FuhuXia** [GSA/data.gov#4518]
ckanext-spatial's map widget [is configurable](https://github.com/ckan/ckanext-spatial/blob/master/doc/map-widgets.rst#custom), such as this:
```
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom.url = http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg
ckanext.spatial.common_map.attribution = Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY SA</a>.
 ```

This does not work in our catalog. It always use the default, current stamen-tiles. The attribution text is hard coded in the [datagovtheme](https://github.com/GSA/ckanext-datagovtheme/blob/bc4cb0b750ca6e347784242a586c10c1123dcd44/ckanext/datagovtheme/templates/package/search.html#L133-L136).  

## How to reproduce

Add above code block to .env or ckan.ini.

## Expected behavior

Map widget shows new watercolor tiles.

## Actual behavior

No change.

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

**Comment by nickumia** [comment]
Oh... is this the missing link in the following issue?
- https://github.com/GSA/data.gov/issues/4493

**Comment by brownterryn** [comment]
Update: my fault, wasn't putting .ini entries under app:main section, just appending to end of file, leaving comment in case others make the same mistake.  @FuhuXia ?

I'm trying to use the above (type = custom) to point to https://tile.openstreetmap.org/{z}/{x}/{y}.png (with and without the $s OSMs example shows) and it appears to have no effect, i.e. just the "No map provider set. Please check the documentation" text, no failed call to OSM in the log etc.  Don't know if it's not reading .ini, or .ini formatting is wrong, but agree with OP and do not think the problem is an out of date link to Stamen.

**Comment by FuhuXia** [comment]
@brownterryn Thanks for the input. The issue we are having is custom ckan theme not loading latest ckanext-spatial snippet. Fix is on the way.

**Comment by FuhuXia** [comment]
fixed in [datagovtheme PR](https://github.com/GSA/ckanext-datagovtheme/pull/173) by updating to the latest spatial_query snippet. Configured map tile server in [catalog PR](https://github.com/GSA/catalog.data.gov/pull/1135/files#diff-2bb199e339bb6e69993cabfa507b7b84ca146f4b7c52484c3d4902cb8f986c58R232-R242).
