### ISSUE TITLE
Implement Error Handling in Datagov-Harvesting-Logic

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4620]
## User Story

In order to effectively communicate harvesting errors back to our agency partners, datagovteam wants to implement enhanced error handling in datagov-harvesting-logic.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I am processing a harvest source
WHEN I encounter an error during processing
AND it is of adequate severity (CRITICAL OR ERROR, we don't record WARN, INFO, DEBUG)
THEN I record the TYPE of error and the message associated with it

- [ ] GIVEN the error is of an irrecoverable type (ex. malformed source, http error, system error)
WHEN I have logged the error to the database
AND sent an error log to New Relic
THEN I terminate the process and return a non-zero exit code

- [ ] GIVEN the error is at the dataset level
AND it is not irrecoverable for the system
WHEN I receive a validation error
THEN I attempt to correlate that error with a type in a validation lookup table which will also allow us to pair that with an accompanying link to the DCAT spec in resources.data.gov

- [ ] GIVEN the error is at the dataset level
AND is not a validation error
THEN I will record the TYPE, SEVERITY, and MESSAGE in the harvest_error table
AND send an error log to New Relic

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Wire in Harvest DB to datagov-harvesting-logic
- [ ] Implement error handling blocks at every stage
- [ ] Create a lookup table to group validation errors and correlate them with the requisite link in the DCAT-US spec
- [ ] Write tests to process a mock harvest source and confirm errors are generated as expected
- [ ] Process an actual harvest source, compare that with current harvester, and confirm errors are generated as expected

**Comment by btylerburton** [comment]
Notes from grooming. Will update Sketch/AC a little later:
- If DB is not available or not wired in, we should log the errors to the stdout.

**Comment by rshewitt** [comment]
outcome from james/robby/reid discussion:
- creating custom exception classes 
  - potential critical/irrecoverable exceptions
    - harvest source catalog extract exception
      - malformed source, http error, system error
    - ckan source extract exception
      - if we got the harvest source but we can't get our ckan records that means the compare will produce more records to be created which is more demanding on ckan ( we should probably try to avoid this ) 
    - compare exception

   - potential non-critical exceptions
     - validation exception
     - transformation exception
     - dcatus-to-ckan exception ( preparation for ckan )
     - sync ( create, update, delete ) exception

Food-for-thought:
  - in preparation for the compare we store records and their hashes in `HarvestSource.records` in the format `{id_of_record: Record instance}` which means we loop through all the ckan records and the harvest source records. If an exception occurs during this step then we'll have an inaccurate understanding of what work needs to be done. @jbrown-xentity thinks this is an irrecoverable error

db error Implementation ( rough sketch )
```python 
from models import HarvestError
from sqlalchemy import create_engine
from sqlalchemy.orm import Session

engine = create_engine( ...data ) 
db_session = Session( engine ) 

# error/exception occurs somewhere...
harvest_error = HarvestError( ...data )
db_session.add( harvest_error ) 
db_session.commit()

```

**Comment by rshewitt** [comment]
exception handling [branch](https://github.com/GSA/datagov-harvesting-logic/tree/exception-handling)

**Comment by rshewitt** [comment]
~~it's possible to customize a processes exit code using `sys.exit` ( e.g. `sys.exit(1)` )~~ ( the program should handle this without explicitly setting it ). should we create a critical exception class for the calling script to use? for example, 
```python 
# this file is load_source.py. 
# it's run like "cf run-task --command "python load_source.py -s [source_id]""

from harvester.harvest import HarvestSource 

def main():
  # parse args and get source data from api route
  harvest_source = HarvestSource( ...harvest_source_data )

  try: 
    harvest_source.get_record_changes() 
  except CriticalException as e:
    # so sys.exit(1)?  

  # we don't need to wrap this in a try/except because this is non-critical
  # and exception handling occurs in HarvestSource
  harvest_source.synchronize_records()

if __name__ == "__main__":
  main()
```

we also don't necessarily need a calling script. we can implement what we need in `harvest.py` using a `main` function which would parse the incomings arg(s)

**Comment by rshewitt** [comment]
## Exceptions and when they can occur
### critical exceptions
#### an exception which prevents the job from continuing
- ExtractHarvestSourceException
  - after downloading the dcatus catalog we loop through each record to prepare them for the comparison. if a record doesn't have an `identifier` key this exception is raised. This is a record-level exception but if we allow this to happen our comparison will not be accurate ( e.g. a record is excluded because of this but the associated record is on ckan that means this record would be labelled for "deletion" ).
  - we were unable to download the catalog ( e.g. 500 from server ) or there is no `dataset` key containing records
  - an exception in general has occurred in `get_harvest_records_as_id_hash`
- ExtractCKANSourceException
  - an exception in general has occurred in `get_ckan_records_as_id_hash` 
    - `package_search` returns an exception
    - the result of `package_search` doesn't contain a `results` key
    - the original metadata can't be deserialized into a valid python dictionary
- CompareException
  - a general exception has occurred during the compare function
### non-critical exceptions
#### an exception which doesn't prevent the job from continuing but needs to be recorded
- ValidationException
  - a record has failed validation
- TranformationException
  - a record has failed to transform
- DCATUSToCKANException
  - a record has failed to convert from dcatus to ckan
- SynchronizeException
  - a record was unable to be deleted, updated, or created on ckan

**Comment by rshewitt** [comment]
I'd like to figure out a better way to isolate our logs/exceptions, maybe into a function or something. I say logs/exceptions to describe exceptions, logs written to a logger, and errors written to a db. Take for example when a dcatus record doesn't have an `identifier` key, 
```python 
# ...code doing stuff beforehand

if "identifier" not in record: 

    harvest_error = HarvestError( ..data )                      #1 
    db_session.add(harvest_error)
    db_session.commit()

    logger.critical(                                            #2 
        f"{self.title} {self.url} "
        "\n" + "'identifier' key not in record. exiting job"
    )

    raise ExtractHarvestSourceException(                        #3
        "'identifier' key not in record. exiting job"
    )
```

If we don't package these things up elsewhere `harvest.py` will be quickly bloated with this kind of content. Something like this...

```python 

def handle_log_stuff( *args ):
  # write to db 
  # write to logger 
  # return raised exception

# ...code doing stuff beforehand

if "identifier" not in record: 
  handle_log_stuff( *args )
```

Something i'm worried about though is the arguments for `handle_log_stuff` will be an aggregate of all unique situations for the logger, custom exceptions, and harvest error ~~in addition to having to pass the actual logger itself and the db session to write our transactions to~~ ( should just be able to access them globally if the function declaration is in harvest.py? )  

Just something i need to think about...

**Comment by jbrown-xentity** [comment]
@rshewitt consider using the definition of the error itself to do the handling, something [like this](https://stackoverflow.com/questions/16788884/customizing-exceptions-in-python-writing-logs-in-custom-exception-class). We could define a `harvest_critical_exception` base class, and a `harvest_error_exception` base class, and they would do the logging and db object creation there. Then the different types of errors we find just inherit from these 2 classes...

**Comment by rshewitt** [comment]
@jbrown-xentity thanks for this! i'll implement something like this. I'm also thinking of creating a basic custom `DBHandler` logger I can add to the main logger in `harvest.py` so when we call the root logger it emits to the db too. the outcome being when we raise an exception everything is taken care of.

**Comment by btylerburton** [comment]
Just catching up on this. 

So the implementation would be: an importable error module that defines custom error classes, each of which includes an instance of DBHandler? 

Then, when an error occurs: one of these classes is called, which then handles writes to the harvest_error_db and then does sys.exit or pass depending on whether its critical or not?

**Comment by rshewitt** [comment]
the error classes won't have an instance of the dbhandler. the error class will create the log records like `log.critical( ...data )`. we'll add our custom dbhandler to the `harvest.py` logger via `logger.addHandler( DBHandler )` so when the error class creates a record the db creation is handle as well. here's what this can generally look like as one thing ( not separate modules )
```python 

session = Session( create_engine( ..db_connection_stuff ) ) 

# create our custom db log handler 
class DBHandler( logging.handler ):
  def __init__(self, session ):
    self.session = session
  def emit( self, record ):
    harvest_error = HarvestError( ...record ) # this is very simplified. imagine this includes the type, msg, harvest_job_id, etc...
    self.session.add( harvest_error ) 
    self.session.commit() 

logger = logging.getLogger(__name__)
logger.addHandler(DBHandler(session)) # add our db handler here so when we logger.critical(), DBHandler emits as well!

# create our custom exception class
class CriticalErrorException( Exception ):
  def __init__(self, msg )
    logger.critical(msg, extra={"type": "CRITICAL", etc...}) # log records accept a "extra" keyword which we can pass whatever we want

# ...down the line when we're trying to get our harvest source
try: 
  # get our harvest source 
except Exception as e:
  raise CriticalErrorException( "can't get harvest source", more_stuff_here? )
```

i'm still working through this but this is basically the idea. maybe it won't work? However, I paired with @FuhuXia and he thinks we should store our db errors in a queue like redis during processing instead of committing them individually when they occur. we would then have something pop those messages and insert them via the flask app. @FuhuXia correct me if i'm wrong. we're gonna wanna have a stay-after or pair with the team to go over what we spoke about. we also talked about a basic workflow of how all these things come together

**Comment by btylerburton** [comment]
Much clearer now. Thanks!

> logger.addHandler(DBHandler)

This was the part I was missing.

**Comment by rshewitt** [comment]
since we need to discuss more on where error records are going to be stored and what repo is responsible for housing/managing the db and to unblock myself the custom `LogDBHandler` emit method is just going to print the incoming record instead of doing something with it. i've added TODOs next to the relevant lines

**Comment by rshewitt** [comment]
python logging [anti-patterns](https://docs.python.org/3/howto/logging-cookbook.html#patterns-to-avoid)

**Comment by rshewitt** [comment]
`logging.getLogger(name)` follows a singleton pattern so there's no need to share/import it across modules. currently, we use it in our custom exceptions in `exceptions.py` for critical/error logs and info/warn in `harvest.py`.

**Comment by rshewitt** [comment]
we may not want to have critical/error logs occur within our custom exceptions because they may not have access to the full traceback until that point. relevant [SO post](https://stackoverflow.com/questions/53162817/logging-exceptions-in-python-3). need to read more on exceptions/custom exceptions and logging to ensure we're not missing out on information. I think it's fine if we decide to omit details from our logs but I don't want to design something which omits it for us without knowing.

**Comment by rshewitt** [comment]
situation I ran into today. currently, i'm raising an exception when we're unable to download a dcatus harvest source either because the server didn't return a 200 or there's no `dataset` key/array in the source. here's what this looks like...
```python 
#...code doing stuff beforehand
if download_res is None or "dataset" not in download_res:
  raise ExtractHarvestSourceException(
      (
          f"{self.title} {self.url} no valid response from server"
          "or lack of 'dataset' array. exiting job"
      ),
      self.job_id,
  )
```
an exception is raised outside an `except` block so we don't have access to the traceback in the same way. do we want to raise exception like this? [relevant SO post](https://stackoverflow.com/questions/3925248/print-python-stack-trace-without-exception-being-raised)

if we want the traceback similar to how we're getting it in other scenarios we would raise the exception inside of an `except` block like...

```python 
#...code doing stuff beforehand
try:
  # get our harvest source and not including our condition
except Exception as e:
  raise ExtractHarvestSourceException(
      (
          f"{self.title} {self.url} no valid response from server"
          "or lack of 'dataset' array. exiting job"
      ),
      self.job_id,
  )
```

**Comment by rshewitt** [comment]
disabled pytest console capture during [testing](https://github.com/GSA/datagov-harvesting-logic/actions/runs/8162298756/job/22312984844#step:7:21) so we can see what's being logged

**Comment by rshewitt** [comment]
I would prefer to wait until the db stuff from the orchestrator has been migrated over to the DHL repo to finish writing error records instead of copy/pasting previous DB work. i'm gonna leave this as blocked until then

**Comment by rshewitt** [comment]
you can access the arguments passed to a raised exception via `.args`. for example, 
```python 
try:
  # download bogus harvest source which returns "None" 
  # assume the download was successful and access its "dataset" key. resulting in a TypeError
except Exception as e:
 print( e.args ) # ("'NoneType' object is not subscriptable",)
```
this is the simplified reason for why the exception occurred in contrast to an entire stack trace

**Comment by gujral-rei** [comment]
New Relic Logging will be bounded eventually.
