### ISSUE TITLE
Setup/cleanup mdTranslator mini-app

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#4796]
## User Story

In order to get transformer to the [latest code](https://github.com/adiwg/mdTranslator/pull/383), harvest2.0 devs want the transform system setup with latest changes.

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None

## Sketch

We want the following:

- Get [gsa fork](https://github.com/gsa/mdTranslator) of MDTranslator caught up with the latest release (see user story), and make a protected branch.
- Setup mdTranslator datagov version into datagov-harvest-transformer](https://github.com/GSA/datagov-harvest-transformer)
- Integrate this (via Dockerfile, something else?) into [datagov-harvesting-logic](https://github.com/gsa/datagov/harvesting-logic)
- Make sure application is deployed into cloud.gov with latest version (is CI/CD setup?)

**Comment by rshewitt** [comment]
master is synced with upstream master. datagov is synced with upstream develop since most of the activity is on that branch and what i would assume we'd merge into when the time comes

**Comment by rshewitt** [comment]
we have deploy, publish (ghcr), and test ci/cd [actions](https://github.com/GSA/datagov-harvest-transformer/tree/main/.github/workflows)

**Comment by rshewitt** [comment]
removed mdtranslator in the compose file on this [commit](https://github.com/GSA/datagov-harvester/commit/9eac8c63c72562037c75c990963ebd5c7db65381). can add back.

**Comment by rshewitt** [comment]
for anyone unfamiliar with package management in ruby ( not version management ) here's some info... 
```console 
reidhewitt@Reids-MacBook-Pro mdTranslator % gem env 
RubyGems Environment:
  ...
  - INSTALLATION DIRECTORY: /home/bobsmith/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
  - GEM PATHS:
     - /home/bobsmith/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
     - /home/bobsmith/.gem/ruby/3.2.0
  ...
```
- `INSTALLATION DIRECTORY` is the default directory where your gems are gonna be installed. `GEM_PATHS` are where the gems are [searched from](https://guides.rubygems.org/command-reference/#gem-environment:~:text=GEM_PATH%20allows%20multiple%20local%20repositories%20to%20be%20searched%20for%20gems.). in my case, I included a `.ruby-version` file in my root indicating to use ruby v3.2.2 which I had previously installed for another app. I wanted to use the same ruby version but since i'm using a different app i don't want them both to use the same installation directory. 
- if you want to install your gems in a folder in your root directory similar to `node_modules` you can configure `bundle` to do so. 
  - if you don't have a bundle config file create one in your root such that `.bundle/config` is a valid file path
- then add `BUNDLE_PATH: "your_folder_name"` to the file. apparently, naming the folder "vendor" is common practice so `BUNDLE_PATH: "vendor"`. <ins>if `BUNDLE_PATH` is configured it will be used to search for gems regardless of `GEM_HOME` or `GEM_PATH`<ins> ([source](https://bundler.io/v1.12/man/bundle-config.1.html#:~:text=path%20(BUNDLE_PATH)%3A%20The%20location%20on%20disk%20where%20all%20gems%20in%20your%20bundle%20will%20be%20located%20regardless%20of%20%24GEM_HOME%20or%20%24GEM_PATH%20values))
- you'll notice `.bundle` and `vendor/` are included in the [gitignore file](https://github.com/GSA/mdTranslator/blob/master/.gitignore) (not a highlighted link because they're apart so find them)
- install your gems via `bundle install` (you may or may not have to create "vendor" prior to installing. i already created it)
- assuming everything is good your vendor folder should look something like...
<img width="150" alt="Screenshot 2024-06-14 at 4 36 24 PM" src="https://github.com/GSA/data.gov/assets/92057378/e9aa12c1-addd-4768-969c-3c40a8f2f3ab">

**Comment by rshewitt** [comment]
[info on ruby version management](https://stackoverflow.com/questions/32934651/is-it-a-bad-practice-to-list-ruby-version-in-both-gemfile-and-ruby-version-dotf)

**Comment by rshewitt** [comment]
- [IRB](https://github.com/ruby/irb) comes with your ruby installation and can be used to debug
- insert a "breakpoint" by adding `binding.irb` on the line of your choice. here's an example of what that might look like...
```console 
From: /home/bobsmith/.rbenv/versions/3.2.2/lib/ruby/vendor_ruby/gems/3.2.0/gems/adiwg-mdtranslator-2.20.0.pre.beta.5/lib/adiwg/mdtranslator/writers/dcat_us/sections/dcat_us_contact_point.rb @ line 10 :

     5:       module Writers
     6:          module Dcat_us
     7:             module ContactPoint
     8: 
     9:                def self.build(intObj)
 => 10:                   binding.irb
    11:                   resourceInfo = intObj[:metadata][:resourceInfo]
    12:                   pointOfContact = resourceInfo[:pointOfContacts][0]
    13:                   contactId = pointOfContact[:parties][0][:contactId]
    14: 
    15:                   contact = Dcat_us.get_contact_by_id(contactId)

irb(ADIWG::Mdtranslator::Writers:...):001> # execute your expression here...
```
