### ISSUE TITLE
RESEARCH SPIKE: Create a recommended architecture for ZenDesk

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4822]
## Purpose

We want to make it easier to reply to feedback on the catalog via email, but we're not sure how to do that.

Given the current process of copying/pasting is very inefficient and makes it diddicult for us to understand topics/customers in an automated way, conducting research is needed to provide factual knowledge on future steps to either integrate Touchpoints with Zendesk OR replace Touchpoints with Zendesk.

2 weeks of effort has been allocated and once compete, findings will be demonstrated and specific future actions will be decided.

### Acceptance Criteria

- [ ] GIVEN a user submits feedback on a catalog.data.gov \
 AND that user needs to be replied to \
  WHEN 2 weeks expires
  THEN we will have a path to a submission auto-opening a Zendesk ticket
  AND populating the ticket with the submission content
  

### Background

https://support.zendesk.com/hc/en-us/articles/4408846913050-Options-for-letting-end-users-submit-tickets-with-forms

https://developer.zendesk.com/documentation/ticketing/managing-tickets/building-a-custom-ticket-form-with-the-zendesk-api/?_ga=2.256045960.2019841066.1721236510-78374013.1718022148&_gl=1*2vt947*_ga*NzgzNzQwMTMuMTcxODAyMjE0OA..*_ga_0G6FC9CS2V*MTcyMTMwODk4My4xNS4xLjE3MjEzMTA3NTYuNDcuMC4w

https://github.com/GSA/touchpoints/wiki/API

https://developer.zendesk.com/api-reference/ticketing/introduction/

### Sketch

Estimate the LOE in creating a cron job GET request for TP submission data and POSTing into ZD vs creating a custom ZD HTML form that auto-creates a ZD ticket, and embedding that form on the catalog

**Comment by jbrown-xentity** [comment]
Alright, we actually made a lot of progress in session with @tdlowden today!
We confirmed that we can make a widget form, and that form can be embedded on a website with a one-liner in the HTML.
We confirmed that we can customize said form.
We confirmed that the relevant information will be passed into the ticket, including the URL that the form was filled out on.
We can auto-assign the tickets to data.gov group in zendesk (kind of hacky; all of the forms filled out will go to us; no one else will be able to use these forms in the ZenDesk account).

Things to confirm:

- The web form is 503 compliant, and won't get us in trouble with ADA
- Can we limit which form the user can fill out, so they don't have to choose between the "default" and "data.gov" form?

**Comment by jbrown-xentity** [comment]
In my research, I haven't found any reason to assume 503 compliance for ADA will not pass due to this plugin. I tested this by [uploading a test as a PR](https://github.com/GSA/datagov-11ty/pull/345), which you can see [here](https://federalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov/preview/gsa/datagov-11ty/test_zendesk/404.html) (see the bottom right corner Help button). According to [Accessibility Checker .org](https://www.accessibilitychecker.org/audit/?website=https%3A%2F%2Ffederalist-2ac784db-2321-4734-8d02-933835d88304.sites.pages.cloud.gov%2Fpreview%2Fgsa%2Fdatagov-11ty%2Ftest_zendesk%2F404.html&flag=us), we essentially pass (the one issue is related to the current 404 page, not the plugin). I'm not positive the scan is assessing the help button and tool, but it should pass any other scans...
To answer the other question, I'll need to pair with @tdlowden .
This will require somewhat re-working the layout. From what I can tell, there are[ options to customize](https://support.zendesk.com/hc/en-us/articles/4408832257562-Advanced-customization-of-Web-Widget-Classic#topic_nzd_cbq_mx) where and how the overlay help text occurs, you can customize the following:

- The icon
- The button text
- The location of the button (typically in any of the 4 corners, or you can specify a pixel count moved from one of the corners, but I doubt that would be very dynamic)

However, this is always overlayed on the screen. It's not a static point on the webpage, like our current ones are.
I think this could work well, but I would rework the layout in the following way:

- Move the User Guide to be one of the tabs on the header, maybe in place of where "Contact" is today.
- Use the top-right corner for the help button.
- Remove the idea of 2 forms: generic and dataset specific (they are essentially the same already in touchpoints: name, email, message), and don't have the contact data.gov landing page at all anymore.

**Comment by jbrown-xentity** [comment]
We intend to take on this work, it's detailed [here](https://github.com/GSA/data.gov/issues/4935). This research and discovery is complete.
