### ISSUE TITLE
Refactor ISO19115_2_datagov reader against catalog sources

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4924]
## User Story

In order to prepare our new MDTranslator for its real job of tranlating catalog documents, and in order not to fail a majority of documents that currently exist on catalog, datagov team wants to run tests against its new `ISO19115_2_datagov` reader and make changes where necessary to allow documents we believe to be functionally correct to pass validation.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN I have a document which already exists on catalog
AND it's metadata is not wildly incorrect or missing 
THEN I want to loosen the validation in the ISO19115_2_datagov reader accordingly to allow certain non-spec compliant attributes to pass

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Agree on a list of sample documents that should pass validation
- [ ] Run those through the MDTranslator
- [ ] Make changes to the ISO19115_2_datagov reader to allow the documents to pass validation

**Comment by rshewitt** [comment]
`gml` has basic types within the [namespace](https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/validation/xml/iso19139ngdc/schema/gml/basicTypes.xsd) (the link provided points to an xsd doc we use currently to validate our -2 documents). i think this is a good starting point for loosening our validation by allowing elements with `gco:nilReason` values listed in the enumeration ( i.e. `['inapplicable', 'missing', 'template', 'unknown', 'withheld', "other:\w{2,}"]` ).

**Comment by rshewitt** [comment]
i downloaded this [document](https://catalog.data.gov/harvest/object/3ff96e7c-7276-4fdd-a88e-dcfd133ba345) from catalog. I wanted to modify a required element by giving it a `nilReason` attribute to see what happens. `gmd:date` is required in a citation element so I modified the first citation in the document such that the date element looks like...
```xml 
<gmd:date gco:nilReason="something"/>
```
this passed validation which I didn't expect. I thought the `nilReason` enumeration ( see link from comment above ) would limit the acceptable values but in this case since it passed validation maybe a non-empty string is acceptable? i removed the `nilReason` entirely and just included a self-enclosing tag and it passed validation. removing the element failed validation. i'm validating the document locally using the same xsd used in [ckan-spatial](https://github.com/ckan/ckanext-spatial/blob/8a00a2b5cff7ebbe5ba0ea96f2a2b58ae7d09218/ckanext/spatial/validation/validation.py#L160)

here's the validation error log after i removed the `gmd:date` element from citation
```terminal
valid-doc.xml:145:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.isotc211.org/2005/gmd}identifier': This element is not expected. Expected is one of ( {http://www.isotc211.org/2005/gmd}alternateTitle, {http://www.isotc211.org/2005/gmd}date ).
```

child elements representing the type the parent is inherits its requirement ( [comment](https://github.com/GSA/data.gov/issues/4862#issuecomment-2400695966) ). In the case of `gmd:date` within a citation `gmd:CI_Date` should exist as its child but validation passes if `gmd:date` is self-enclosing which is concerning. After looking into `gmd:CI_Date`, this element [isn't required](https://github.com/ckan/ckanext-spatial/blob/8a00a2b5cff7ebbe5ba0ea96f2a2b58ae7d09218/ckanext/spatial/validation/xml/iso19139ngdc/schema/gmd/citation.xsd#L196C3-L196C30). we haven't dug this deep into the xsd tree with our work so far. this is something we should implement.

**Comment by btylerburton** [comment]
To clarify, it passes validation when validated against the XSD from ckan-spatial, but won't transform to DCAT due to the strictness in MDTranslator?

**Comment by rshewitt** [comment]
> To clarify, it passes validation when validated against the XSD from ckan-spatial, but won't transform to DCAT due to the strictness in MDTranslator?

I haven't tried to transform it into dcatus yet. I wanted to know whether `nilReason` had any impact on the validity of the document. If `nilReason` had an impact then I would consider including that in mdtranslator.

**Comment by rshewitt** [comment]
here's a test case where a parent element is required but the element it's a type of isn't. in this example, we're looking at `gmd:date` within `gmd:CI_Citation`. the `gmd:date` element is required but the element it is a type of isn't ( i.e. `gmd:CI_Date` ). here's the element definition in the xsd. this explains why a citation with a self-enclosing `gmd:date` tag is valid. `gmd:CI_Date` has a minimum sequence occurrence of 0. 
```xml
<!-- ... -->
<xs:element name="date" type="gmd:CI_Date_PropertyType" maxOccurs="unbounded"/> <!-- this element is required in citation-->
<!-- ... -->

<!-- ... -->
<xs:complexType name="CI_Date_PropertyType">
	<xs:sequence minOccurs="0"> <!-- minimum occurrence is 0 -->
		<xs:element ref="gmd:CI_Date"/>
	</xs:sequence>
	<xs:attributeGroup ref="gco:ObjectReference"/>
	<xs:attribute ref="gco:nilReason"/>
</xs:complexType>
 <!-- ... -->
```

if i change this definition to

```xml
<!-- ... -->
<xs:complexType name="CI_Date_PropertyType">
	<xs:sequence> <!-- default minimum occurrence is 1 now -->
		<xs:element ref="gmd:CI_Date"/>
	</xs:sequence>
	<xs:attributeGroup ref="gco:ObjectReference"/>
	<xs:attribute ref="gco:nilReason"/>
</xs:complexType>
 <!-- ... -->
```

validation fails and produces the following errors
```terminal
valid-doc.xml:114:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element '{http://www.isotc211.org/2005/gmd}date': Missing child element(s). Expected is ( {http://www.isotc211.org/2005/gmd}CI_Date ).

# omitting same error but in different places
```

**Comment by rshewitt** [comment]
from what i can gather any element which can have a `gco:nilReason` attribute should have a value that's either in `['inapplicable', 'missing', 'template', 'unknown', 'withheld']` or conforms to the following regular expressions: `other:\w{2,}` or `([a-zA-Z][a-zA-Z0-9\-\+\.]*:|\.\.\/|\.\/|#).*` ( the actual expression is `([a-zA-Z][a-zA-Z0-9\-\+\.]*:|\.\./|\./|#).*` which doesn't escape the backslashes. i've used both and nothing changes ). i've used a value that doesn't conform to these rules and validation still passes. validation also passes on a self-enclosed tag with no `gco:nilReason` attribute.

**Comment by rshewitt** [comment]
a pattern in xsd's is to have elements extend from an abstract element ( [related comment](https://github.com/orgs/GSA/projects/11/views/1?pane=issue&itemId=76183680&issue=GSA%7Cdata.gov%7C4862#:~:text=determine%20full%20list%20of%20siblings%20for%20a%20given%20extension%20parent.%20related%20to%20comment ) ) which allows for a variety of elements to occur within a specific element. a recent example i've found for `gmd:geographicElement` allows for a bounding polygon element, a bounding box element, and a geographic description element. all three of these extend `gmd:AbstractEX_GeographicExtent_Type`.

**Comment by rshewitt** [comment]
the `-2` & `-2_datagov` work ( including tests ) haven't been included in linting. i'm gonna include that as a separate pr. i also changed the indentation width to 2 spaces rather than 3. i can't look at 3 anymore and idk why i had it that way from the beginning.

**Comment by rshewitt** [comment]
i'm implementing the following [improvements](https://github.com/GSA/data.gov/issues/4862#:~:text=the%20selected%20approach%5D-,Improvements,-determine%20which%20modules) in this refactor: `1, 2, 3, 4, & 6`

1:  i'm returning nil if the module can't find the root element it's responsible for processing and hash otherwise. i figure if the module can find the root but nothing else the starting state of the hash might better reflect the data than nil. 
2:  doing structure and validation messages
3: no comment. implementing as-is.
4: no comment. implementing as-is.
6: no comment. implementing as-is.

**Comment by rshewitt** [comment]
here's a breakdown of use cases for a required element ( i.e. `keyword` ) which can occur many times ( i.e. `unbounded` ). the minimum number of occurrences is 1. we're also allowing an acceptable `gco:nilReason` as an exception to the requirement rule by  simply skipping them during processing. 

```xml
<!-- use case 1 (valid) -->
<gmd:keyword gco:nilReason="missing"/>
<gmd:keyword />
<gmd:keyword>
  <gco:CharacterString>Nautical Charting</gco:CharacterString>
</gmd:keyword>  

<!-- use case 2 (valid) -->
<gmd:keyword gco:nilReason="missing"/>

<!-- use case 3 (invalid) -->
<gmd:keyword />

<!-- use case 4 (invalid) -->
<gmd:keyword gco:nilReason="missing"/>
<gmd:keyword />

<!-- use case 5 (valid) -->
<gmd:keyword>
  <gco:CharacterString>Nautical Charting</gco:CharacterString>
</gmd:keyword>  

<!-- use case 6 (valid) -->
<gmd:keyword />
<gmd:keyword>
  <gco:CharacterString>Nautical Charting</gco:CharacterString>
</gmd:keyword> 

<!-- use case 7 (invalid) -->
<gmd:keyword gco:nilReason="invalid nil reason"/>

```

one easy approach to this problem is to simply complain if the document doesn't have at least 1 valid keyword. anything else is invalid. however, that breaks our rule of considering `gco:nilReason`
```xml
<gmd:keyword>
  <gco:CharacterString>Nautical Charting</gco:CharacterString>
</gmd:keyword> 
```

another approach would be to check if there's at least 1 valid element or 1 element with an acceptable `nilReason`?

**Comment by shuvosarker22** [comment]
https://github.com/GSA/data.gov/issues/4924#issuecomment-2444795773

**Comment by rshewitt** [comment]
497 of the 500 datasets from this [query](https://catalog.data.gov/api/action/package_search?fq=(organization:noaa-gov+res_format:XML)&rows=500) passed validation with the latest `-2` translator. here's the validation messages per invalid document. expanding this failure rate of `0.6%` to all `-2` 291017 documents ( this number may have changed ) in catalog means 1747 are invalid according to mdtranslator. another nice thing about this test shows mdtranslator is able to process 500 production documents from start to finish without error.

1
```ruby
["INFO: ISO19115-2 reader: element 'westBoundLongitude' contains acceptable nilReason: 'unknown'",
 "INFO: ISO19115-2 reader: element 'eastBoundLongitude' contains acceptable nilReason: 'unknown'",
 "INFO: ISO19115-2 reader: element 'northBoundLatitude' contains acceptable nilReason: 'unknown'",
 "INFO: ISO19115-2 reader: element 'southBoundLatitude' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: Element gml:beginPosition or gml:begin is missing in gml:TimePeriod"]
```

2 
```ruby 
["INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present."]
```

3
```ruby 
["WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "WARNING: ISO19115-2 reader: element 'gmd:keyword' is missing in 'MD_Keywords'",
 "INFO: ISO19115-2 reader: element 'date' contains acceptable nilReason: 'inapplicable'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "INFO: ISO19115-2 reader: element 'role' contains acceptable nilReason: 'unknown'",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present.",
 "WARNING: ISO19115-2 reader: 'gmd:CI_ResponsibleParty' must have at least an individual or organization. neither are present."]
```

**Comment by rshewitt** [comment]
latest [action](https://github.com/GSA/mdTranslator/actions/runs/11632092432) has passed. need to add `nilReason` tests now.

**Comment by rshewitt** [comment]
of the 34195 xml files in [ioos](https://data.noaa.gov/waf/NOAA/ioos/iso/xml/) 22382 timed out ( default connect & read time outs are both 60 seconds for `net/http` gem ) and the remaining 11809 were valid documents with some additions i've made.

**Comment by rshewitt** [comment]
ran into an error when processing this [file](https://data.noaa.gov/waf/NOAA/nos/ocm/iso/xml/47598.xml). it involved how we're processing distributions. distributions in `-2` have distributors, transfer options, and distribution formats as siblings but in the mdjson they are parent-child. distributors, transfer options, and distribution formats are all optional and unbounded within a distribution which complicates things. 

```ruby
# data structure in the xml file
{ :distributions => [ :distributors => [], :transferOptions => [] , :distributionFormats => [] ]  }

# data structure in mdjson ( simplfied )
{ :distributions => [ 
  { :distributors => [ 
    {:transferOptions => [ 
      {:distributionFormats => [] } 
    ] } 
  ] } 
] }
```
i'm going to continue using the currently implemented shared index between transfer options and distribution formats because it appears to make sense in the data. taking this [file](https://github.com/GSA/mdTranslator/blob/master/test/datagov/WIP__office-of-coast-survey-wrecks-and-obstructions-database.xml) as an example, the 2nd transfer option describes a map server [url](https://wrecks.nauticalcharts.noaa.gov/arcgis/rest/services/public_wrecks/Wrecks_And_Obstructions/MapServer) and the 2nd distribution format is `ESRI REST Service`.

**Comment by rshewitt** [comment]
ran into an issue with this [file](https://data.noaa.gov/waf/NOAA/nos/ocm/iso/xml/47845.xml). basically, temporal extents only handle time periods not time instances ( they're siblings within `gmd:extent` so either can occur ). the dcatus writer derives its temporal value via time periods. it tries to find a start/end range then either a start or end. because of this, returning a start or an end, i think it's okay to use a time instance which uses a single `timePosition`.

**Comment by rshewitt** [comment]
here's an example of a [doc](https://data.noaa.gov/waf/NOAA/nos/ocm/iso/xml/47711.xml) which passed validation against how we currently do it but didn't pass validation in mdtranslator. the reason is because i've added logic to verify absent values ( i.e. nil reasons ) in mdtranslator. nil reasons don't appear to be considered currently (related [comment](https://github.com/GSA/data.gov/issues/4924#issuecomment-2429845945)). in this case, there's no value for a `gml:endPosition` and no reason for why it's missing. i consider this an improvement to how we currently do it. 

[example2](https://data.noaa.gov/waf/NOAA/nos/ocm/iso/xml/47712.xml)
[example3](https://data.noaa.gov/waf/NOAA/nos/ocm/iso/xml/47713.xml)

**Comment by rshewitt** [comment]
ran into an issue involving an undeclared namespace which prompted me to think whether certain namespaces within a standard are required? for example, the gmd and gco namespaces are your bread and butter for -2 documents. pick any document and a majority of elements are in either of those namespaces. are there rules to require declaration of namespaces?

**Comment by jbrown-xentity** [comment]
Consider adding logging in the application/MDTranslator, or create a ticket to do this work.
