### ISSUE TITLE
CKAN Broken Link Report is Broken

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#537]
https://catalog.data.gov/report

Is rendering a 404 and harvester2p is unresponsive to ssh for the 3rd time in 2 weeks

**Comment by hkdctol** [comment]
OBE; we will continue work on the catalog report on agency harvests

**Comment by nickumia-reisys** [comment]
This was fixed by
- https://github.com/GSA/data.gov/issues/3957

But then disabled by disabling the `ckanext-archiver` due to it creating a Redis Overflow issue,
- https://github.com/GSA/data.gov/issues/4188

The only issue right now is operating at scale
- https://github.com/GSA/data.gov/issues/3986
