### ISSUE TITLE
Investigate Harvester Re-duplication of already removed duplicates

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#601]
After we ran the dedupe removal, there are still WAF and data.json sources that the harvester is still improperly detecting records as being new and is creating new duplicate records for what should be an updated existing dataset:

## Investigate potential root cause in codebase
- [ ] Rerun depupe in dry mode to detect still duplicate records for sources that have been reharvested since the dedupe ran.
- [ ] Investigate list of still duplicate dataset to cross-reference fields like uuid/publisher/title being different enough causing a new duplicate record rather than an update/modification.
- [ ] investigate harvest code logic to determine root cause.

## Investigate potential root cause in redis queue backlog
- [ ] Harvests that fail to complete can be reharvested, it may be that the records are backing up and each dataset is being added as a duplicate record.

**Comment by adborden** [comment]
I did some analysis of ckanext-datajson and identified some potential issues a while back but I can't find the issue. Maybe I never wrote up the findings.

I don't know if this is really the root cause of ckanext-datajson creating duplicates, but it did look like the harvest process could end up linking to the wrong harvest_object, causing issues.

Here is a partial analysis for ckanext-datajson. Unfortunately, I didn't describe the issues with the existing algorithm, so I don't recall why I wanted to rewrite the algorithm, maybe just to simplify it. Anyway, I'm including it here mostly for my own notes, not that it will be of much help to anyone picking up this story. https://gist.github.com/adborden/ec2c7a1b315177eacd43624b733d351c
