### ISSUE TITLE
Update Data.gov Metrics dataset

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#655]
https://catalog.data.gov/dataset/data-gov-visitor-metrics is a dataset that has not been updated since late 2017. Page views of catalog pages for datasets. Through GA? We have several requests for updated version of this dataset.

**Comment by adborden** [comment]
I did a github search for the header in the dataset's csv, it looks like it's coming from one of our extensions https://github.com/GSA/ckanext-geodatagov/blob/80b72945926134f0d9d3fb59741284332672cac4/ckanext/geodatagov/commands.py#L1252

**Comment by hkdctol** [comment]
@adborden if you can get an idea of workload on this and whether we can do this this month, USDA is very interested.

**Comment by adborden** [comment]
I tried running the metrics-csv job on production. It uploaded an empty csv to S3. It looks like this job pulls data from the tracking tables, and those jobs haven't run in a while. The tracking update job is what would update the data to display [most recent datasets](https://github.com/GSA/datagov-deploy/issues/663) on the front page.

However, I tried running the tracking update job and ran into [this error](https://github.com/GSA/datagov-deploy/issues/707). I'm going to open a ticket with BSP to investigate space issues on the database. I'm also going to look into getting these [cleanup jobs going again](https://github.com/GSA/ckanext-geodatagov/pull/115), since this is just a disaster waiting to happen if we run out of space.

**Comment by hkdctol** [comment]
@adborden Phil and I are on a call with USDA and they asked about this. They understand we have other priorities but it's something they are still very interested in. If it's possible to work on this without getting too off track on Ubuntu upgrade, would be great if we can include in next sprint.

**Comment by adborden** [comment]
@philipashlock how does this look? I think it only has data from the past three months. It's much smaller than the last one at 84MB. The one from 2017 is over 200MB. Is it supposed to be cumulative over all time or is that a manual step?
https://filestore.data.gov/gsa/catalog/metrics/metrics-2019-04-30.csv

**Comment by adborden** [comment]
We forwarded this to USDA.

**Comment by adborden** [comment]
This job should be running regularly now, but there is still a manual step to combine new datasets with the existing ones. There is also a task to back-fill data from last year. Agencies can request the latest data from us and we can provide them with the latest URL.

**Comment by hkdctol** [comment]
Closing as this will be dealt with in upcoming epic on metrics
