### ISSUE TITLE
Error message when trying to alter harvest frequency in catalog admin UI

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#874]
<Getting an error when in catalog admin UI, trying to change frequency of harvest for a harvest source>

## How to reproduce

1. Log in to catalog as admin and go to State of California organization: https://admin-catalog.data.gov/organization/ca-gov

## Expected behavior

<UI should permit change from manual to daily on a harvest source>

## Actual behavior

<See attached screenshot of error
![500 error](https://user-images.githubusercontent.com/3236989/62486470-64beac00-b78d-11e9-91d5-1af264aee555.png)
>

**Comment by adborden** [comment]
This happened again when editing the frequency for one of the Department of Energy harvest sources.
![Screen Shot 2019-09-03 at 10 34 00 AM](https://user-images.githubusercontent.com/509703/64188255-e9e9bf00-ce26-11e9-924e-64966a00f222.png)

**Comment by adborden** [comment]
This could be a CKAN bug, since the solr fields should be configured to be an appropriate size. We should check that what we're putting in the `status` field is correct (and not absurdly large).

**Comment by hkdctol** [comment]
@adborden I just tried this with two harvest sources and it worked. Would we have done something that fixed this?? If you think issue can be closed, go ahead.

**Comment by adborden** [comment]
I think the issue is specific to these harvest sources, so try it with DOE and CA.gov and see what happens 🤞

**Comment by FuhuXia** [comment]
A bug was found that will get large harvest source stuck if there are many newly added datasets, as describe in issue https://github.com/GSA/datagov-deploy/issues/1367,  and the harvest source will gives UI error when being edited as described in this ticket.

In the harvest `status` field there is an item `summary`, this item contains a **summary** of `added` records as well as `errors`. Since it is a summary, we dont need to show more that 20 records. The `error` records was limited at 20, but put all `added` records into the summary, making `status` field too large to be indexed by Solr.

Put the 20 limit in the query should solve this issue as well as other harvesting job getting stuck issue as in https://github.com/GSA/datagov-deploy/issues/1367.

**Comment by FuhuXia** [comment]
We are removing the summary altogether as a fix.
