### ISSUE TITLE
deploy php applications through ansible

### ISSUE THREAD

**Issue by kvuppala** [GSA/data.gov#9]
Need to convert the below from Capistrano to Ansible script, and create the AMI using packer
- Data.gov WordPress
- Labs Dashboard
- Labs CRM

**Comment by alex-perfilov-reisys** [comment]
WordPress ansible & packer done.
No SSL, No SAML (only basic WP auth) so far.

All the changes are in the https://github.com/GSA/datagov-deploy/tree/ansible/ansible branch.

I didn't remove Capistrano scripts yet, but didn't test them either.  Something may broke since I've updated most of datagov-deploy to latest https://github.com/roots/bedrock.

It's running on Nginx + PHP7.0-FPM.
Example is running on http://54.236.200.161/ (some old SQL backup was deployed on temporary AuroraDB RDS)
